-- ------------------------------
-- desc: generated by xls2data.py
-- source: ai.xls
-- sheet: ai
-- ------------------------------


local ai_35_info = {
	[1] = {
		['event'] = 'battle_start',
		['event_param'] = nil,
		['target_id'] = '',
		['target_x'] = 0,
		['target_y'] = 0,
		['target_range'] = 0,
		['next_ai'] = 0,
		['ai_event'] = 'playPlot',
		['ai_param'] = {1,2,3,4,5,6,7,8,9,10,11,12,13},
		['des'] = '',
	},
	[2] = {
		['event'] = 'kill',
		['event_param'] = nil,
		['target_id'] = '敌二',
		['target_x'] = 0,
		['target_y'] = 0,
		['target_range'] = 0,
		['next_ai'] = 0,
		['ai_event'] = 'say',
		['ai_param'] = {name = "$(usename)", txt = "嗯！一大箱火腿！"},
		['des'] = '',
	},
	[3] = {
		['event'] = 'kill',
		['event_param'] = nil,
		['target_id'] = '敌三',
		['target_x'] = 0,
		['target_y'] = 0,
		['target_range'] = 0,
		['next_ai'] = 0,
		['ai_event'] = 'say',
		['ai_param'] = {name = "$(usename)", txt = "上等的葡萄酒！哈哈！"},
		['des'] = '',
	},
	[4] = {
		['event'] = 'kill',
		['event_param'] = nil,
		['target_id'] = '敌四',
		['target_x'] = 0,
		['target_y'] = 0,
		['target_range'] = 0,
		['next_ai'] = 0,
		['ai_event'] = 'say',
		['ai_param'] = {name = "$(usename)", txt = "精美的瓷器！这可值不少钱呢！"},
		['des'] = '',
	},
	[5] = {
		['event'] = 'hp_ratio_less',
		['event_param'] = {50},
		['target_id'] = '',
		['target_x'] = 0,
		['target_y'] = 0,
		['target_range'] = 0,
		['next_ai'] = 0,
		['ai_event'] = 'say',
		['ai_param'] = {name = "巴里", txt = "干掉他们！每人奖励10个第纳尔！"},
		['des'] = '',
	},
}

return ai_35_info