-- ------------------------------
-- desc: generated by xls2data.py
-- source: plot.xls
-- sheet: Sheet1
-- ------------------------------


local plot_134_info = {
	[1] = {
		['plot'] = 'camera',
		['param'] = {{1600,640,2}},
	},
	[2] = {
		['plot'] = 'dialog',
		['param'] = {51,"汪直",2,"你们真是阴魂不散呢，如此苦苦相逼……",ship_id=2},
	},
	[3] = {
		['plot'] = 'dialog',
		['param'] = {51,"汪直",2,"让你们看看我手下浪人的厉害！来人啊，把他们切碎了丢海里喂鱼去！",ship_id=2},
	},
}

return plot_134_info