-- ------------------------------
-- desc: generated by xls2data.py
-- source: plot.xls
-- sheet: Sheet1
-- ------------------------------


local plot_15_jy_info = {
	[1] = {
		['plot'] = 'add_sprite',
		['param'] = {"ui/story/story_101.jpg",{0,0},1,1,1,0,1,"RGB565",{0.5,"VOICE_BATTLE_1064"}},
	},
	[2] = {
		['plot'] = 'delay',
		['param'] = {10},
	},
	[3] = {
		['plot'] = 'remove_sprite',
		['param'] = {1,1,2.5,0},
	},
	[4] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,"拉比斯！你插翅难飞了！",3,true,"","VOICE_BATTLE_1065"},
	},
	[5] = {
		['plot'] = 'dialog',
		['param'] = {64,"拉比斯",1,"哈！靠这些不堪一击的船能拦住我？满帆，准备突击！",7,true,"VOICE_BATTLE_1056"},
	},
	[6] = {
		['plot'] = 'dialog',
		['param'] = {64,"拉比斯",1,"阿芒德！你总是在我不想见你的时候出现！虽然我从不想见到你……",8,true,"VOICE_BATTLE_1057"},
	},
	[7] = {
		['plot'] = 'dialog',
		['param'] = {67,"海盗阿芒德",2,"啊！今天真是我的幸运日！拉比斯竟然像一只受伤的小猫向我的怀里扑过来！",10,true,"VOICE_BATTLE_1054"},
	},
	[8] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,"混蛋！拉比斯是我打败的！把他交给我！",5,true,"","VOICE_BATTLE_1066"},
	},
	[9] = {
		['plot'] = 'dialog',
		['param'] = {67,"海盗阿芒德",2,"你的？如果你不想和他一起在亚历山大的监牢里腐烂的话，就趁我没改变主意前滚吧，弱小的虫子！",11,true,"VOICE_BATTLE_1055"},
	},
	[10] = {
		['plot'] = 'add_sprite',
		['param'] = {"ui/story/story_100.jpg",{0,0},1,1,1,1,3,"RGB565",{0.5,"VOICE_BATTLE_1067"}},
	},
	[11] = {
		['plot'] = 'remove_sprite',
		['param'] = {1,0,1,1},
	},
	[12] = {
		['plot'] = 'btn_click',
		['param'] = {{875,80},1,{"#skill_9999.png"}," ",true,true,"VOICE_BATTLE_1004",{825,30}},
	},
	[13] = {
		['plot'] = 'camera',
		['param'] = {{1000,1200,1}},
	},
	[14] = {
		['plot'] = 'delay',
		['param'] = {7},
	},
}

return plot_15_jy_info