-- ------------------------------
-- desc: generated by xls2data.py
-- source: plot.xls
-- sheet: Sheet1
-- ------------------------------


local plot_23_info = {
	[1] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,"终于攻入摩尔海盗的老巢！",ship_id=1},
	},
	[2] = {
		['plot'] = 'camera',
		['param'] = {{600,600,0},{1800,600,1},},
	},
	[3] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,"这些犬牙交错的小岛不仅可以掩护伏击，也可以分散船阵！",ship_id=1},
	},
	[4] = {
		['plot'] = 'camera',
		['param'] = {{1800,600,0},{600,600,1},},
	},
	[5] = {
		['plot'] = 'dialog',
		['param'] = {5,"汉娜",2,"敌人的舰队装备精良，我们难有胜算。向上方航行，利用岛礁障碍分散海盗阵形，然后逐个击破吧！",ship_id=1},
	},
}

return plot_23_info