-- ------------------------------
-- desc: generated by xls2data.py
-- source: plot.xls
-- sheet: Sheet1
-- ------------------------------


local plot_51_jy_info = {
	[1] = {
		['plot'] = 'dialog',
		['param'] = {7,"水手",1,"报告！前方就是维斯瓦河口，但泽到了。",ship_id=1},
	},
	[2] = {
		['plot'] = 'camera',
		['param'] = {{1200,680,1}},
	},
	[3] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,"已经进入汉萨同盟的势力范围，大家小心！",ship_id=1},
	},
	[4] = {
		['plot'] = 'camera',
		['param'] = {{1800,1080,1}},
	},
	[5] = {
		['plot'] = 'dialog',
		['param'] = {30,"汉萨守备队长",2,"河口已被封锁，非汉萨同盟船只禁止进入！",ship_id=2},
	},
	[6] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,"北欧并不只属于汉萨同盟，任何人都有进出的自由。",ship_id=1},
	},
	[7] = {
		['plot'] = 'dialog',
		['param'] = {30,"汉萨守备队长",2,"敢与强大的汉萨同盟为敌，真是自寻死路。突击队前进，消灭汉萨的敌人！",ship_id=2},
	},
	[8] = {
		['plot'] = 'dialog',
		['param'] = {30,"汉萨守备队长",2,"没用的废物，下一艘突击船前进！",ship_id=2},
	},
	[9] = {
		['plot'] = 'camera',
		['param'] = {{1800,1080,1}},
	},
	[10] = {
		['plot'] = 'dialog',
		['param'] = {30,"汉萨守备队长",2,"很多时候，只能自己亲自动手了！跟我来！",ship_id=2},
	},
}

return plot_51_jy_info