-- ------------------------------
-- desc: generated by xls2data.py
-- source: arena_bot.xls
-- sheet: bot
-- ------------------------------


local arena_bot_info = {
	[1] = {
		['formationCfg'] = {3,1,2},
		['skills_list'] = {{},{},{}},
		['name'] = '艾伦·鲁',
		['level'] = 15,
		['role'] = 101,
		['formationId'] = 1,
	},
	[2] = {
		['formationCfg'] = {2,3,1},
		['skills_list'] = {{},{},{}},
		['name'] = '林清和',
		['level'] = 12,
		['role'] = 101,
		['formationId'] = 2,
	},
	[3] = {
		['formationCfg'] = {3,1,2},
		['skills_list'] = {{},{},{}},
		['name'] = '约翰法雷尔',
		['level'] = 11,
		['role'] = 101,
		['formationId'] = 3,
	},
	[4] = {
		['formationCfg'] = {3,2,4},
		['skills_list'] = {{},{},{}},
		['name'] = '来看看',
		['level'] = 9,
		['role'] = 103,
		['formationId'] = 4,
	},
	[5] = {
		['formationCfg'] = {2,1,3},
		['skills_list'] = {{[1002] = 1},{},{}},
		['name'] = '七秀',
		['level'] = 10,
		['role'] = 103,
		['formationId'] = 5,
	},
	[6] = {
		['formationCfg'] = {2,1,3},
		['skills_list'] = {{[1030] = 1},{},{}},
		['name'] = '明月心',
		['level'] = 8,
		['role'] = 101,
		['formationId'] = 6,
	},
	[7] = {
		['formationCfg'] = {3,1,2},
		['skills_list'] = {{[1018] = 1},{},{}},
		['name'] = '法伦海特',
		['level'] = 9,
		['role'] = 101,
		['formationId'] = 7,
	},
	[8] = {
		['formationCfg'] = {2,3,1},
		['skills_list'] = {{[1010] = 1},{},{}},
		['name'] = '草帽海贼団',
		['level'] = 8,
		['role'] = 101,
		['formationId'] = 1,
	},
	[9] = {
		['formationCfg'] = {3,2,4},
		['skills_list'] = {{[1026] = 1},{},{}},
		['name'] = '随便取个名字',
		['level'] = 8,
		['role'] = 103,
		['formationId'] = 2,
	},
	[10] = {
		['formationCfg'] = {1,2,3},
		['skills_list'] = {{[1002] = 1},{},{}},
		['name'] = '卡特琳娜',
		['level'] = 9,
		['role'] = 103,
		['formationId'] = 3,
	},
}

return arena_bot_info