-- ------------------------------
-- desc: generated by xls2data.py
-- source: arena_reward.xls
-- sheet: 奖励
-- ------------------------------


local arena_time_reward_info = {
	[1] = {
		['start_time'] = '2014-12-20 0:0:0',
		['end_time'] = '2014-12-31 23:59:59',
		['need_point'] = 80,
		['reward_table'] = '1003001',
	},
	[2] = {
		['start_time'] = '2015-01-01 10:0:0',
		['end_time'] = '2015-01-31 23:59:59',
		['need_point'] = 300,
		['reward_table'] = '1003002',
	},
	[3] = {
		['start_time'] = '2015-02-01 10:0:0',
		['end_time'] = '2015-02-28 23:59:59',
		['need_point'] = 420,
		['reward_table'] = '1003003',
	},
	[4] = {
		['start_time'] = '2015-03-01 10:0:0',
		['end_time'] = '2015-03-31 23:59:59',
		['need_point'] = 420,
		['reward_table'] = '1003004',
	},
}

return arena_time_reward_info