-- ------------------------------
-- desc: generated by xls2data.py
-- source: boat.xls
-- sheet: 船经验
-- ------------------------------


local boat_reform_exp = {
	[1] = {
		['two'] = 90,
		['one'] = 30,
		['zero'] = 10,
	},
	[2] = {
		['two'] = 180,
		['one'] = 60,
		['zero'] = 10,
	},
	[3] = {
		['two'] = 540,
		['one'] = 180,
		['zero'] = 60,
	},
	[4] = {
		['two'] = 720,
		['one'] = 240,
		['zero'] = 80,
	},
	[5] = {
		['two'] = 900,
		['one'] = 300,
		['zero'] = 100,
	},
	[6] = {
		['two'] = 1080,
		['one'] = 360,
		['zero'] = 120,
	},
	[7] = {
		['two'] = 1260,
		['one'] = 420,
		['zero'] = 140,
	},
}

return boat_reform_exp