-- ------------------------------
-- desc: generated by xls2data.py
-- source: boat.xls
-- sheet: 改造
-- ------------------------------


local boat_reform = {
	[] = {
	},
	[] = {
	},
	[] = {
	},
	[] = {
	},
	[] = {
	},
	[] = {
	},
	[] = {
	},
}

return boat_reform