-- ------------------------------
-- desc: generated by xls2data.py
-- source: campsite.xls
-- sheet: foundry
-- ------------------------------


local campsite_foundry_info = {
	[1] = {
		['build_time'] = 0,
		['user_level'] = 0,
		['sail'] = 0,
		['consume'] = nil,
		['rewards'] = nil,
		['sailor_amount'] = 3,
		['sailor_type'] = {6},
		['sailor_exp'] = 0,
		['desc'] = '铸造厂可用于生产装备船只的配件',
		['condition'] = 10,
		['image'] = '#foundry_camp_1.png',
		['maxLevel'] = 4,
	},
	[2] = {
		['build_time'] = 10800,
		['user_level'] = 10,
		['sail'] = 210,
		['consume'] = nil,
		['rewards'] = nil,
		['sailor_amount'] = 3,
		['sailor_type'] = {6},
		['sailor_exp'] = 1000,
		['desc'] = '铸造厂可用于生产装备船只的配件',
		['condition'] = 25,
		['image'] = '#foundry_camp_2.png',
		['maxLevel'] = 4,
	},
	[3] = {
		['build_time'] = 21600,
		['user_level'] = 30,
		['sail'] = 750,
		['consume'] = nil,
		['rewards'] = nil,
		['sailor_amount'] = 3,
		['sailor_type'] = {6},
		['sailor_exp'] = 2000,
		['desc'] = '铸造厂可用于生产装备船只的配件',
		['condition'] = 35,
		['image'] = '#foundry_camp_3.png',
		['maxLevel'] = 4,
	},
	[4] = {
		['build_time'] = 32400,
		['user_level'] = 50,
		['sail'] = 1750,
		['consume'] = nil,
		['rewards'] = nil,
		['sailor_amount'] = 3,
		['sailor_type'] = {6},
		['sailor_exp'] = 4000,
		['desc'] = '铸造厂可用于生产装备船只的配件',
		['condition'] = 40,
		['image'] = '#foundry_camp_4.png',
		['maxLevel'] = 4,
	},
}

return campsite_foundry_info