-- ------------------------------
-- desc: generated by xls2data.py
-- source: chongzhi_reward.xls
-- sheet: 奖励
-- ------------------------------


local payReward = {
	[1] = {
		['value'] = 10,
		['reward'] = {47,35},
		['name'] = 'VIP 1',
		['kind'] = 0,
		['subType'] = {2},
	},
	[2] = {
		['value'] = 50,
		['reward'] = "委任次数+1,体力购买次数+1",
		['name'] = 'VIP 2',
		['kind'] = 0,
		['subType'] = {4},
	},
	[3] = {
		['value'] = 100,
		['reward'] = {45,35},
		['name'] = 'VIP 3',
		['kind'] = 0,
		['subType'] = {2},
	},
	[4] = {
		['value'] = 200,
		['reward'] = "委任次数+2,体力购买次数+2",
		['name'] = 'VIP 4',
		['kind'] = 0,
		['subType'] = {4},
	},
	[5] = {
		['value'] = 500,
		['reward'] = {71,23},
		['name'] = 'VIP 5',
		['kind'] = 0,
		['subType'] = {2},
	},
	[6] = {
		['value'] = 1000,
		['reward'] = "委任次数+3,体力购买次数+3",
		['name'] = 'VIP 6',
		['kind'] = 0,
		['subType'] = {4},
	},
	[7] = {
		['value'] = 2000,
		['reward'] = "委任次数+4,体力购买次数+4",
		['name'] = 'VIP 7',
		['kind'] = 0,
		['subType'] = {4},
	},
	[8] = {
		['value'] = 5000,
		['reward'] = {20,15},
		['name'] = 'VIP 8',
		['kind'] = 0,
		['subType'] = {3},
	},
}

return payReward