-- ------------------------------
-- desc: generated by xls2data.py
-- source: 配置cofig.xls
-- sheet: 任务
-- ------------------------------


local chuanyun_huodong = {
	[1] = {
		['general'] = {1,2,3},
		['senior'] = {4,5,6},
	},
	[2] = {
		['general'] = {1,2,3},
		['senior'] = {4,5,6},
	},
}

return chuanyun_huodong