-- ------------------------------
-- desc: generated by xls2data.py
-- source: equip.xls
-- sheet: 装备属性icon
-- ------------------------------


local equip_attrib_info = {
	['gun_value'] = {
		['name'] = '火炮火力',
		['res'] = '#bo_cannon2.png',
	},
	['gun_range'] = {
		['name'] = '火炮射程',
		['res'] = '#eq_gunrange.png',
	},
	['target_hit'] = {
		['name'] = '火炮命中',
		['res'] = '#eq_targethit.png',
	},
	['damage_range'] = {
		['name'] = '伤害范围',
		['res'] = '#eq_damagerange.png',
	},
	['sailor_damage'] = {
		['name'] = '水手伤害',
		['res'] = '#bo_sword2.png',
	},
	['attack_speed'] = {
		['name'] = '攻击速度',
		['res'] = '#eq_attackspeed.png',
	},
	['boat_damage'] = {
		['name'] = '船体破坏',
		['res'] = '#eq_boatdamage.png',
	},
	['goods_plunder'] = {
		['name'] = '货物掠夺',
		['res'] = '#eq_goodsplunder.png',
	},
	['boat_durable'] = {
		['name'] = '船体耐久',
		['res'] = '#bo_armor2.png',
	},
	['move_speed'] = {
		['name'] = '行进速度',
		['res'] = '#eq_speed2.png',
	},
	['turn_speed'] = {
		['name'] = '转向速度',
		['res'] = '#eq_turnspeed.png',
	},
	['speed_control'] = {
		['name'] = '速度操控',
		['res'] = '#eq_speedcontrol.png',
	},
	['miss_attack'] = {
		['name'] = '闪避攻击',
		['res'] = '#eq_missattack.png',
	},
	['sailor_hp'] = {
		['name'] = '水手血量',
		['res'] = '#eq_sailorhp.png',
	},
}

return equip_attrib_info