-- ------------------------------
-- desc: generated by xls2data.py
-- source: guild_mission.xls
-- sheet: 任务
-- ------------------------------


local guild_mission = {
	[1] = {
		['maxTimes'] = 1,
		['name'] = '公会任务：公会每日签到',
	},
	[2] = {
		['maxTimes'] = 3,
		['name'] = '公会任务：完成营地情报屋任务%s次',
	},
	[3] = {
		['maxTimes'] = 3,
		['name'] = '公会任务：完成招募水手%s次',
	},
	[4] = {
		['maxTimes'] = 5,
		['name'] = '公会任务：完成战役%s次',
	},
	[5] = {
		['maxTimes'] = 5,
		['name'] = '公会任务：完成讨伐%s次',
	},
	[6] = {
		['maxTimes'] = 5,
		['name'] = '公会任务：完成竞技场%s次',
	},
	[7] = {
		['maxTimes'] = 5,
		['name'] = '公会任务：完成装备强化%s次',
	},
	[8] = {
		['maxTimes'] = 10,
		['name'] = '公会任务：完成经商(港口倾销商品)%s次',
	},
}

return guild_mission