-- ------------------------------
-- desc: generated by xls2data.py
-- source: 洞府配置.xls
-- sheet: 功能
-- ------------------------------


local fabao_depend_info = {
	['F001'] = {
		['name'] = TEXT('1级灵兽培育'),
		['Btype'] = TEXT('进行'),
		['yb_quick'] = '',
	},
	['F002'] = {
		['name'] = TEXT('2级灵兽培育'),
		['Btype'] = TEXT('进行'),
		['yb_quick'] = '',
	},
	['F003'] = {
		['name'] = TEXT('3级灵兽培育'),
		['Btype'] = TEXT('进行'),
		['yb_quick'] = '',
	},
	['F004'] = {
		['name'] = TEXT('4级灵兽培育'),
		['Btype'] = TEXT('进行'),
		['yb_quick'] = '',
	},
	['F101'] = {
		['name'] = TEXT('1级法宝温养'),
		['Btype'] = TEXT('进行'),
		['yb_quick'] = 'env["cnt"]<=5?5:(env["cnt"]<=10?10:(env["cnt"]<=15?15:20))',
	},
	['F102'] = {
		['name'] = TEXT('2级法宝温养'),
		['Btype'] = TEXT('进行'),
		['yb_quick'] = 'env["cnt"]<=5?5:(env["cnt"]<=10?10:(env["cnt"]<=15?15:20))',
	},
	['F103'] = {
		['name'] = TEXT('3级法宝温养'),
		['Btype'] = TEXT('进行'),
		['yb_quick'] = 'env["cnt"]<=5?5:(env["cnt"]<=10?10:(env["cnt"]<=15?15:20))',
	},
	['F104'] = {
		['name'] = TEXT('4级法宝温养'),
		['Btype'] = TEXT('进行'),
		['yb_quick'] = 'env["cnt"]<=5?5:(env["cnt"]<=10?10:(env["cnt"]<=15?15:20))',
	},
}

return fabao_depend_info