-- ------------------------------
-- desc: generated by xls2data.py
-- source: 洞府配置.xls
-- sheet: 妖仆
-- ------------------------------


local yaopu_depend_info = {
	['Y001'] = {
		['name'] = TEXT('妖仆'),
		['Btype'] = TEXT('繁衍'),
		['yb_quick'] = 'env["time"]/360',
	},
	['Y002'] = {
		['name'] = TEXT('妖仆'),
		['Btype'] = TEXT('繁衍'),
		['yb_quick'] = 'env["time"]/360',
	},
	['Y003'] = {
		['name'] = TEXT('妖仆'),
		['Btype'] = TEXT('繁衍'),
		['yb_quick'] = 'env["time"]/360',
	},
	['Y004'] = {
		['name'] = TEXT('妖仆'),
		['Btype'] = TEXT('繁衍'),
		['yb_quick'] = 'env["time"]/360',
	},
	['Y005'] = {
		['name'] = TEXT('妖仆'),
		['Btype'] = TEXT('繁衍'),
		['yb_quick'] = 'env["time"]/360',
	},
	['Y006'] = {
		['name'] = TEXT('妖仆'),
		['Btype'] = TEXT('繁衍'),
		['yb_quick'] = 'env["time"]/360',
	},
	['Y007'] = {
		['name'] = TEXT('妖仆'),
		['Btype'] = TEXT('繁衍'),
		['yb_quick'] = 'env["time"]/360',
	},
	['Y008'] = {
		['name'] = TEXT('妖仆'),
		['Btype'] = TEXT('繁衍'),
		['yb_quick'] = 'env["time"]/360',
	},
	['Y009'] = {
		['name'] = TEXT('妖仆'),
		['Btype'] = TEXT('繁衍'),
		['yb_quick'] = 'env["time"]/360',
	},
	['Y010'] = {
		['name'] = TEXT('妖仆'),
		['Btype'] = TEXT('繁衍'),
		['yb_quick'] = 'env["time"]/360/1.8',
	},
	['Y011'] = {
		['name'] = TEXT('妖仆'),
		['Btype'] = TEXT('繁衍'),
		['yb_quick'] = 'env["time"]/360/1.7',
	},
	['Y012'] = {
		['name'] = TEXT('妖仆'),
		['Btype'] = TEXT('繁衍'),
		['yb_quick'] = 'env["time"]/360/2.4',
	},
	['Y013'] = {
		['name'] = TEXT('妖仆'),
		['Btype'] = TEXT('繁衍'),
		['yb_quick'] = 'env["time"]/360/2.2',
	},
	['Y014'] = {
		['name'] = TEXT('妖仆'),
		['Btype'] = TEXT('繁衍'),
		['yb_quick'] = 'env["time"]/360/3.8',
	},
	['Y015'] = {
		['name'] = TEXT('妖仆'),
		['Btype'] = TEXT('繁衍'),
		['yb_quick'] = 'env["time"]/360/3',
	},
	['Y016'] = {
		['name'] = TEXT('妖仆'),
		['Btype'] = TEXT('繁衍'),
		['yb_quick'] = 'env["time"]/360/5',
	},
	['Y017'] = {
		['name'] = TEXT('妖仆'),
		['Btype'] = TEXT('繁衍'),
		['yb_quick'] = 'env["time"]/360/4.8',
	},
	['Y018'] = {
		['name'] = TEXT('妖仆'),
		['Btype'] = TEXT('繁衍'),
		['yb_quick'] = 'env["time"]/360/6.5',
	},
	['Y019'] = {
		['name'] = TEXT('妖仆'),
		['Btype'] = TEXT('繁衍'),
		['yb_quick'] = 'env["time"]/360/6.3',
	},
	['Y020'] = {
		['name'] = TEXT('妖仆'),
		['Btype'] = TEXT('繁衍'),
		['yb_quick'] = 'env["time"]/360/8.5',
	},
	['Y021'] = {
		['name'] = TEXT('妖仆'),
		['Btype'] = TEXT('繁衍'),
		['yb_quick'] = 'env["time"]/360/8.3',
	},
	['Y022'] = {
		['name'] = TEXT('妖仆'),
		['Btype'] = TEXT('繁衍'),
		['yb_quick'] = 'env["time"]/360/10',
	},
	['Y023'] = {
		['name'] = TEXT('妖仆'),
		['Btype'] = TEXT('繁衍'),
		['yb_quick'] = 'env["time"]/360/10',
	},
	['Y024'] = {
		['name'] = TEXT('妖仆'),
		['Btype'] = TEXT('繁衍'),
		['yb_quick'] = 'env["time"]/360/10',
	},
	['Y025'] = {
		['name'] = TEXT('妖仆'),
		['Btype'] = TEXT('繁衍'),
		['yb_quick'] = 'env["time"]/360/10',
	},
	['Y026'] = {
		['name'] = TEXT('妖仆'),
		['Btype'] = TEXT('繁衍'),
		['yb_quick'] = 'env["time"]/360/10',
	},
	['Y027'] = {
		['name'] = TEXT('妖仆'),
		['Btype'] = TEXT('繁衍'),
		['yb_quick'] = 'env["time"]/360/10',
	},
	['Y028'] = {
		['name'] = TEXT('妖仆'),
		['Btype'] = TEXT('繁衍'),
		['yb_quick'] = 'env["time"]/360/10',
	},
	['Y029'] = {
		['name'] = TEXT('妖仆'),
		['Btype'] = TEXT('繁衍'),
		['yb_quick'] = 'env["time"]/360/10',
	},
	['Y030'] = {
		['name'] = TEXT('妖仆'),
		['Btype'] = TEXT('繁衍'),
		['yb_quick'] = 'env["time"]/360/10',
	},
	['Y031'] = {
		['name'] = TEXT('妖仆'),
		['Btype'] = TEXT('繁衍'),
		['yb_quick'] = 'env["time"]/360/10',
	},
}

return yaopu_depend_info