-- ------------------------------
-- desc: generated by xls2data.py
-- source: plot.xls
-- sheet: plot
-- ------------------------------


local plot_105_info = {
	[1] = {
		['plot'] = 'camera',
		['param'] = {{1480,840,0}},
	},
	[2] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,"连皇家海军的战舰都出动了，英国佬这下玩真的了。"},
	},
	[3] = {
		['plot'] = 'camera',
		['param'] = {{1480,840,0},{1080,440,1}},
	},
	[4] = {
		['plot'] = 'dialog',
		['param'] = {66,"萨姆.贝拉米",1,"重生的维达号可不怕普通的火炮，我来拖延他们，你尽快把他们逐个击破！"},
	},
}

return plot_105_info