-- ------------------------------
-- desc: generated by xls2data.py
-- source: plot.xls
-- sheet: Sheet1
-- ------------------------------


local plot_102_info = {
	[1] = {
		['plot'] = 'text_display',
		['param'] = {{"杰克从亚齐酒馆……旁的猪圈找到了一名间谍，让他潜入马六甲城打探军情。"}},
	},
	[2] = {
		['plot'] = 'dialog',
		['param'] = {71,"杰克·斯帕罗",2,"吉布斯，希望我信任你是正确的。",ship_id=7},
	},
	[3] = {
		['plot'] = 'dialog',
		['param'] = {17,"吉布斯",2,"放心吧船长，我很高兴你又找到了我，不会让你们失望的。",ship_id=8},
	},
	[4] = {
		['plot'] = 'dialog',
		['param'] = {17,"吉布斯",2,"他们以为我仅是个酗酒的普通商人罢了。",ship_id=8},
	},
	[5] = {
		['plot'] = 'camera',
		['param'] = {{475,1028,2}},
	},
	[6] = {
		['plot'] = 'text_display',
		['param'] = {{"吉布斯成功潜入马六甲城待命。"}},
	},
	[7] = {
		['plot'] = 'text_display',
		['param'] = {{"杰克·斯帕罗的船被击沉了，先撤退吧！"}},
	},
	[8] = {
		['plot'] = 'text_display',
		['param'] = {{"与炮塔保持距离，击沉所有的巡逻舰，直到吉布斯潜入马六甲。"}},
	},
}

return plot_102_info