-- ------------------------------
-- desc: generated by xls2data.py
-- source: plot.xls
-- sheet: Sheet1
-- ------------------------------


local plot_13_info = {
	[1] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,"你所说的运奴船，就是正在远去的那一艘吗？",5,fail,"VOICE_BATTLE_1048","VOICE_BATTLE_1049"},
	},
	[2] = {
		['plot'] = 'camera',
		['param'] = {{600,800,0},{1200,800,2},},
	},
	[3] = {
		['plot'] = 'dialog',
		['param'] = {6,"安杰丽卡·蒂奇",2,"是的！未免惊动对方，我们趁着夜色和风雨掩护，躲开护卫船悄悄接近【摩尔运奴船】吧。",7,fail,"VOICE_BATTLE_1069"},
	},
	[4] = {
		['plot'] = 'cameraScale',
		['param'] = {{1200,800},0.7,2},
	},
	[5] = {
		['plot'] = 'mask_fadeIn',
		['param'] = {0.8},
	},
	[6] = {
		['plot'] = 'cameraScale',
		['param'] = {{600,800},1,0},
	},
	[7] = {
		['plot'] = 'camera',
		['param'] = {{600,800,0}},
	},
	[8] = {
		['plot'] = 'mask_fadeOut',
		['param'] = {0.8},
	},
	[9] = {
		['plot'] = 'dialog',
		['param'] = {6,"安杰丽卡·蒂奇",2,"敌人的装甲很厚，继续拉近距离，我们用接弦战打败它！",5,fail,"VOICE_BATTLE_1070"},
	},
	[10] = {
		['plot'] = 'dialog',
		['param'] = {6,"安杰丽卡·蒂奇",2,"我们的目标是【摩尔运奴船】，别去招惹那些船坚炮利的护卫舰！",6,fail},
	},
	[11] = {
		['plot'] = 'dialog',
		['param'] = {6,"安杰丽卡·蒂奇",2,"如果距离足够近，请让我带领水手向敌舰发起【突击】！",5,fail,"VOICE_BATTLE_1071"},
	},
	[12] = {
		['plot'] = 'guide',
		['param'] = {40,{825,92}},
	},
}

return plot_13_info