-- ------------------------------
-- desc: generated by xls2data.py
-- source: 水手config.xls
-- sheet: proj_eff
-- ------------------------------


local proj_eff = {
	['2'] = {
		['bullet_id'] = 1,
		['bullet_depend_on_ship'] = 1,
		['start_effect'] = 'tx_kaihuo',
		['speed'] = 80,
		['rotate'] = 0,
		['shoot_dt'] = 150,
		['shoot_setting'] = {"center"},
	},
	['qishe'] = {
		['bullet_id'] = 1,
		['bullet_depend_on_ship'] = 1,
		['start_effect'] = 'tx_kaihuo2',
		['speed'] = 100,
		['rotate'] = 0,
		['shoot_dt'] = 120,
		['shoot_setting'] = {"head", "center", "tail", "head", "center", "tail", "head", "center", "tail", "head","center", "tail"},
	},
	['qishe_2'] = {
		['bullet_id'] = 1,
		['bullet_depend_on_ship'] = 1,
		['start_effect'] = 'tx_kaihuo2',
		['speed'] = 100,
		['rotate'] = 0,
		['shoot_dt'] = 300,
		['shoot_setting'] = {"head", "center", "tail", "head", "center", "tail"},
	},
	['qishe_3'] = {
		['bullet_id'] = 1,
		['bullet_depend_on_ship'] = 1,
		['start_effect'] = 'tx_kaihuo2',
		['speed'] = 60,
		['rotate'] = 0,
		['shoot_dt'] = 400,
		['shoot_setting'] = {"head", "center", "tail"},
	},
	['liandan'] = {
		['bullet_id'] = 4,
		['bullet_depend_on_ship'] = 0,
		['start_effect'] = 'tx_kaihuo2',
		['speed'] = 35,
		['rotate'] = 360,
		['shoot_dt'] = 500,
		['shoot_setting'] = {"head", "center", "tail"},
	},
	['sk10001'] = {
		['bullet_id'] = 1,
		['bullet_depend_on_ship'] = 1,
		['start_effect'] = 'tx_kaihuo2',
		['speed'] = 80,
		['rotate'] = 0,
		['shoot_dt'] = 150,
		['shoot_setting'] = {"head", "center", "tail", "head", "center", "tail", "head", "center", "tail", "head","center", "tail", "head", "center", "tail", "head", "center", "tail"},
	},
	['ice'] = {
		['bullet_id'] = 5,
		['bullet_depend_on_ship'] = '0',
		['start_effect'] = 'tx_kaihuo2',
		['speed'] = 35,
		['rotate'] = 360,
		['shoot_dt'] = 500,
		['shoot_setting'] = {"head", "center", "tail"},
	},
}

return proj_eff