-- ------------------------------
-- desc: generated by xls2data.py
-- source: prosper.xls
-- sheet: stage
-- ------------------------------


local prosper_stage = {
	[1] = {
		['level'] = 1,
	},
	[2] = {
		['level'] = 1,
	},
	[3] = {
		['level'] = 10,
	},
	[4] = {
		['level'] = 20,
	},
	[5] = {
		['level'] = 30,
	},
	[6] = {
		['level'] = 40,
	},
	[7] = {
		['level'] = 50,
	},
}

return prosper_stage