-- ------------------------------
-- desc: generated by xls2data.py
-- source: prosper.xls
-- sheet: prosper
-- ------------------------------


local prosper_info = {
	[1] = {
		['sailor_limit'] = 5,
		['cash_list'] = 15000,
		['boat_id'] = '1,23',
		['prosper'] = 0,
	},
	[2] = {
		['sailor_limit'] = 10,
		['cash_list'] = 30000,
		['boat_id'] = '2,24',
		['prosper'] = 30,
	},
	[3] = {
		['sailor_limit'] = 13,
		['cash_list'] = 60000,
		['boat_id'] = '3,25',
		['prosper'] = 60,
	},
	[4] = {
		['sailor_limit'] = 16,
		['cash_list'] = 100000,
		['boat_id'] = '6,28',
		['prosper'] = 270,
	},
	[5] = {
		['sailor_limit'] = 18,
		['cash_list'] = 150000,
		['boat_id'] = '5,27',
		['prosper'] = 700,
	},
	[6] = {
		['sailor_limit'] = 20,
		['cash_list'] = 210000,
		['boat_id'] = '7,8,29,30',
		['prosper'] = 1350,
	},
	[7] = {
		['sailor_limit'] = 23,
		['cash_list'] = 300000,
		['boat_id'] = '9,20,31,42',
		['prosper'] = 2190,
	},
	[8] = {
		['sailor_limit'] = 26,
		['cash_list'] = 360000,
		['boat_id'] = '11,33',
		['prosper'] = 3850,
	},
	[9] = {
		['sailor_limit'] = 30,
		['cash_list'] = 500000,
		['boat_id'] = '12,34',
		['prosper'] = 6000,
	},
	[10] = {
		['sailor_limit'] = 33,
		['cash_list'] = 750000,
		['boat_id'] = '10,32',
		['prosper'] = 8500,
	},
	[11] = {
		['sailor_limit'] = 36,
		['cash_list'] = 1000000,
		['boat_id'] = '13,35',
		['prosper'] = 13000,
	},
	[12] = {
		['sailor_limit'] = 40,
		['cash_list'] = 2000000,
		['boat_id'] = '14,36',
		['prosper'] = 19000,
	},
	[13] = {
		['sailor_limit'] = 42,
		['cash_list'] = 3000000,
		['boat_id'] = '15,37',
		['prosper'] = 29120,
	},
	[14] = {
		['sailor_limit'] = 44,
		['cash_list'] = 4000000,
		['boat_id'] = '16,38',
		['prosper'] = 45000,
	},
	[15] = {
		['sailor_limit'] = 47,
		['cash_list'] = 5000000,
		['boat_id'] = '17,39',
		['prosper'] = 63000,
	},
	[16] = {
		['sailor_limit'] = 50,
		['cash_list'] = 6000000,
		['boat_id'] = '18,40',
		['prosper'] = 85000,
	},
	[17] = {
		['sailor_limit'] = 52,
		['cash_list'] = 7000000,
		['boat_id'] = '19,41',
		['prosper'] = 109680,
	},
	[18] = {
		['sailor_limit'] = 54,
		['cash_list'] = 8000000,
		['boat_id'] = '21,43',
		['prosper'] = 140000,
	},
	[19] = {
		['sailor_limit'] = 56,
		['cash_list'] = 9000000,
		['boat_id'] = '22,44',
		['prosper'] = 180000,
	},
	[20] = {
		['sailor_limit'] = 58,
		['cash_list'] = 9500000,
		['boat_id'] = '',
		['prosper'] = 230000,
	},
	[21] = {
		['sailor_limit'] = 60,
		['cash_list'] = 10000000,
		['boat_id'] = '',
		['prosper'] = 294420,
	},
}

return prosper_info