-- ------------------------------
-- desc: generated by xls2data.py
-- source: random.xls
-- sheet: 随机表
-- ------------------------------


local random_loot_info = {
	['1001001'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1001,random=400,amount=15}},
	},
	['1001002'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1002,random=400,amount=15}},
	},
	['1001003'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1003,random=400,amount=15}},
	},
	['1001004'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1004,random=400,amount=15}},
	},
	['1001005'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1005,random=400,amount=15}},
	},
	['1001006'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1006,random=400,amount=15}},
	},
	['1001011'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1101,random=400,amount=15}},
	},
	['1001012'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1102,random=400,amount=15}},
	},
	['1001013'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1103,random=400,amount=15}},
	},
	['1001014'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1104,random=400,amount=15}},
	},
	['1001015'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1105,random=400,amount=15}},
	},
	['1001016'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1106,random=400,amount=15}},
	},
	['1001021'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1201,random=400,amount=15}},
	},
	['1001022'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1202,random=400,amount=15}},
	},
	['1001023'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1203,random=400,amount=15}},
	},
	['1001024'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1204,random=400,amount=15}},
	},
	['1001025'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1205,random=400,amount=15}},
	},
	['1001026'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1206,random=400,amount=15}},
	},
	['1001031'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1301,random=400,amount=15}},
	},
	['1001032'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1302,random=400,amount=15}},
	},
	['1001033'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1303,random=400,amount=15}},
	},
	['1001034'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1304,random=400,amount=15}},
	},
	['1001035'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1305,random=400,amount=15}},
	},
	['1001036'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1306,random=400,amount=15}},
	},
	['1001021a'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1201,random=400,amount=3}},
	},
	['1001022a'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1202,random=400,amount=3}},
	},
	['1001023a'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1203,random=400,amount=3}},
	},
	['1001024a'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1204,random=400,amount=3}},
	},
	['1001025a'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1205,random=400,amount=3}},
	},
	['1001026a'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1206,random=400,amount=3}},
	},
	['1001031a'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1301,random=400,amount=3}},
	},
	['1001032a'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1302,random=400,amount=3}},
	},
	['1001033a'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1303,random=400,amount=3}},
	},
	['1001034a'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1304,random=400,amount=3}},
	},
	['1001035a'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1305,random=400,amount=3}},
	},
	['1001036a'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1306,random=400,amount=3}},
	},
	['1001111'] = {
		['mode'] = 'RANDOM_ALL',
		['loot_table'] = {{type='item',id=4,random=60,amount=6}},
	},
	['1001112'] = {
		['mode'] = 'RANDOM_ALL',
		['loot_table'] = {{type='item',id=4,random=60,amount=9}},
	},
	['1001113'] = {
		['mode'] = 'RANDOM_ALL',
		['loot_table'] = {{type='item',id=4,random=60,amount=12}},
	},
	['1001114'] = {
		['mode'] = 'RANDOM_ALL',
		['loot_table'] = {{type='item',id=4,random=60,amount=15}},
	},
	['1001115'] = {
		['mode'] = 'RANDOM_ALL',
		['loot_table'] = {{type='item',id=4,random=60,amount=18}},
	},
	['1001116'] = {
		['mode'] = 'RANDOM_ALL',
		['loot_table'] = {{type='item',id=4,random=60,amount=20}},
	},
	['1002006'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1001,random=100,amount=2},{type='material',id=1101,random=100,amount=3}},
	},
	['1002007'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1301,random=100,amount=1},{type='material',id=1201,random=100,amount=1},{type='material',id=1101,random=100,amount=1}},
	},
	['1003001'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='baowu',id=1,random=8,amount=1},{type='baowu',id=2,random=8,amount=1},{type='baowu',id=3,random=8,amount=1},{type='baowu',id=31,random=8,amount=1},{type='baowu',id=32,random=8,amount=1},{type='baowu',id=33,random=8,amount=1},{type='baowu',id=61,random=8,amount=1},{type='baowu',id=62,random=8,amount=1},{type='baowu',id=63,random=8,amount=1},{type='baowu',id=168,random=8,amount=1},{type='baowu',id=178,random=8,amount=1},{type='baowu',id=188,random=8,amount=1},{type='baowu',id=198,random=8,amount=1},{type='baowu',id=208,random=8,amount=1},{type='baowu',id=218,random=8,amount=1}},
	},
	['1003002'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='baowu',id=1,random=8,amount=1},{type='baowu',id=2,random=8,amount=1},{type='baowu',id=3,random=8,amount=1},{type='baowu',id=31,random=8,amount=1},{type='baowu',id=32,random=8,amount=1},{type='baowu',id=33,random=8,amount=1},{type='baowu',id=61,random=8,amount=1},{type='baowu',id=62,random=8,amount=1},{type='baowu',id=63,random=8,amount=1},{type='baowu',id=168,random=8,amount=1},{type='baowu',id=178,random=8,amount=1},{type='baowu',id=188,random=8,amount=1},{type='baowu',id=198,random=8,amount=1},{type='baowu',id=208,random=8,amount=1},{type='baowu',id=218,random=8,amount=1}},
	},
	['1003003'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='baowu',id=4,random=8,amount=1},{type='baowu',id=5,random=8,amount=1},{type='baowu',id=6,random=8,amount=1},{type='baowu',id=34,random=8,amount=1},{type='baowu',id=35,random=8,amount=1},{type='baowu',id=36,random=8,amount=1},{type='baowu',id=64,random=8,amount=1},{type='baowu',id=65,random=8,amount=1},{type='baowu',id=66,random=8,amount=1},{type='baowu',id=169,random=8,amount=1},{type='baowu',id=179,random=8,amount=1},{type='baowu',id=189,random=8,amount=1},{type='baowu',id=199,random=8,amount=1},{type='baowu',id=209,random=8,amount=1},{type='baowu',id=219,random=8,amount=1}},
	},
	['1003004'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='baowu',id=4,random=8,amount=1},{type='baowu',id=5,random=8,amount=1},{type='baowu',id=6,random=8,amount=1},{type='baowu',id=34,random=8,amount=1},{type='baowu',id=35,random=8,amount=1},{type='baowu',id=36,random=8,amount=1},{type='baowu',id=64,random=8,amount=1},{type='baowu',id=65,random=8,amount=1},{type='baowu',id=66,random=8,amount=1},{type='baowu',id=169,random=8,amount=1},{type='baowu',id=179,random=8,amount=1},{type='baowu',id=189,random=8,amount=1},{type='baowu',id=199,random=8,amount=1},{type='baowu',id=209,random=8,amount=1},{type='baowu',id=219,random=8,amount=1}},
	},
	['1003005'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='exp',random=100,amount=100},{type='cash',random=100,amount=200},{type='gold',random=100,amount=300}},
	},
	['1003006'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='cash',random=100,amount=10000},{type='honour',random=100,amount=200}},
	},
	['1003007'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='cash',random=100,amount=8000},{type='honour',random=100,amount=135}},
	},
	['1003008'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='cash',random=100,amount=5000},{type='honour',random=100,amount=100}},
	},
	['1003009'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='cash',random=100,amount=3000},{type='honour',random=100,amount=65}},
	},
	['1003010'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='cash',random=100,amount=1000}},
	},
	['1003011'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='baowu',id=4,random=8,amount=1},{type='baowu',id=5,random=8,amount=1},{type='baowu',id=6,random=8,amount=1},{type='baowu',id=34,random=8,amount=1},{type='baowu',id=35,random=8,amount=1},{type='baowu',id=36,random=8,amount=1},{type='baowu',id=64,random=8,amount=1},{type='baowu',id=65,random=8,amount=1},{type='baowu',id=66,random=8,amount=1},{type='baowu',id=169,random=8,amount=1},{type='baowu',id=179,random=8,amount=1},{type='baowu',id=189,random=8,amount=1},{type='baowu',id=199,random=8,amount=1},{type='baowu',id=209,random=8,amount=1},{type='baowu',id=219,random=8,amount=1}},
	},
	['1003012'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='baowu',id=4,random=8,amount=1},{type='baowu',id=5,random=8,amount=1},{type='baowu',id=6,random=8,amount=1},{type='baowu',id=34,random=8,amount=1},{type='baowu',id=35,random=8,amount=1},{type='baowu',id=36,random=8,amount=1},{type='baowu',id=64,random=8,amount=1},{type='baowu',id=65,random=8,amount=1},{type='baowu',id=66,random=8,amount=1},{type='baowu',id=169,random=8,amount=1},{type='baowu',id=179,random=8,amount=1},{type='baowu',id=189,random=8,amount=1},{type='baowu',id=199,random=8,amount=1},{type='baowu',id=209,random=8,amount=1},{type='baowu',id=219,random=8,amount=1}},
	},
	['1003013'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='baowu',id=7,random=8,amount=1},{type='baowu',id=8,random=8,amount=1},{type='baowu',id=9,random=8,amount=1},{type='baowu',id=37,random=8,amount=1},{type='baowu',id=38,random=8,amount=1},{type='baowu',id=39,random=8,amount=1},{type='baowu',id=67,random=8,amount=1},{type='baowu',id=68,random=8,amount=1},{type='baowu',id=69,random=8,amount=1},{type='baowu',id=170,random=8,amount=1},{type='baowu',id=180,random=8,amount=1},{type='baowu',id=190,random=8,amount=1},{type='baowu',id=200,random=8,amount=1},{type='baowu',id=210,random=8,amount=1},{type='baowu',id=220,random=8,amount=1}},
	},
	['1003014'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='baowu',id=10,random=4,amount=1},{type='baowu',id=11,random=4,amount=1},{type='baowu',id=12,random=4,amount=1},{type='baowu',id=13,random=4,amount=1},{type='baowu',id=14,random=4,amount=1},{type='baowu',id=15,random=4,amount=1},{type='baowu',id=40,random=4,amount=1},{type='baowu',id=41,random=4,amount=1},{type='baowu',id=42,random=4,amount=1},{type='baowu',id=43,random=4,amount=1},{type='baowu',id=44,random=4,amount=1},{type='baowu',id=45,random=4,amount=1},{type='baowu',id=70,random=4,amount=1},{type='baowu',id=71,random=4,amount=1},{type='baowu',id=72,random=4,amount=1},{type='baowu',id=73,random=4,amount=1},{type='baowu',id=74,random=4,amount=1},{type='baowu',id=75,random=4,amount=1},{type='baowu',id=171,random=4,amount=1},{type='baowu',id=181,random=4,amount=1},{type='baowu',id=182,random=4,amount=1},{type='baowu',id=191,random=4,amount=1},{type='baowu',id=192,random=4,amount=1},{type='baowu',id=201,random=4,amount=1},{type='baowu',id=202,random=4,amount=1},{type='baowu',id=211,random=4,amount=1},{type='baowu',id=212,random=4,amount=1},{type='baowu',id=221,random=4,amount=1},{type='baowu',id=222,random=4,amount=1}},
	},
	['1003015'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='baowu',id=7,random=8,amount=1},{type='baowu',id=8,random=8,amount=1},{type='baowu',id=9,random=8,amount=1},{type='baowu',id=37,random=8,amount=1},{type='baowu',id=38,random=8,amount=1},{type='baowu',id=39,random=8,amount=1},{type='baowu',id=67,random=8,amount=1},{type='baowu',id=68,random=8,amount=1},{type='baowu',id=69,random=8,amount=1},{type='baowu',id=170,random=8,amount=1},{type='baowu',id=180,random=8,amount=1},{type='baowu',id=190,random=8,amount=1},{type='baowu',id=200,random=8,amount=1},{type='baowu',id=210,random=8,amount=1},{type='baowu',id=220,random=8,amount=1}},
	},
	['1003016'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='baowu',id=7,random=8,amount=1},{type='baowu',id=8,random=8,amount=1},{type='baowu',id=9,random=8,amount=1},{type='baowu',id=37,random=8,amount=1},{type='baowu',id=38,random=8,amount=1},{type='baowu',id=39,random=8,amount=1},{type='baowu',id=67,random=8,amount=1},{type='baowu',id=68,random=8,amount=1},{type='baowu',id=69,random=8,amount=1},{type='baowu',id=170,random=8,amount=1},{type='baowu',id=180,random=8,amount=1},{type='baowu',id=190,random=8,amount=1},{type='baowu',id=200,random=8,amount=1},{type='baowu',id=210,random=8,amount=1},{type='baowu',id=220,random=8,amount=1}},
	},
	['1003017'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='baowu',id=10,random=4,amount=1},{type='baowu',id=11,random=4,amount=1},{type='baowu',id=12,random=4,amount=1},{type='baowu',id=13,random=4,amount=1},{type='baowu',id=14,random=4,amount=1},{type='baowu',id=15,random=4,amount=1},{type='baowu',id=40,random=4,amount=1},{type='baowu',id=41,random=4,amount=1},{type='baowu',id=42,random=4,amount=1},{type='baowu',id=43,random=4,amount=1},{type='baowu',id=44,random=4,amount=1},{type='baowu',id=45,random=4,amount=1},{type='baowu',id=70,random=4,amount=1},{type='baowu',id=71,random=4,amount=1},{type='baowu',id=72,random=4,amount=1},{type='baowu',id=73,random=4,amount=1},{type='baowu',id=74,random=4,amount=1},{type='baowu',id=75,random=4,amount=1},{type='baowu',id=171,random=4,amount=1},{type='baowu',id=181,random=4,amount=1},{type='baowu',id=182,random=4,amount=1},{type='baowu',id=191,random=4,amount=1},{type='baowu',id=192,random=4,amount=1},{type='baowu',id=201,random=4,amount=1},{type='baowu',id=202,random=4,amount=1},{type='baowu',id=211,random=4,amount=1},{type='baowu',id=212,random=4,amount=1},{type='baowu',id=221,random=4,amount=1},{type='baowu',id=222,random=4,amount=1}},
	},
	['1003018'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='baowu',id=16,random=4,amount=1},{type='baowu',id=17,random=4,amount=1},{type='baowu',id=18,random=4,amount=1},{type='baowu',id=19,random=4,amount=1},{type='baowu',id=20,random=4,amount=1},{type='baowu',id=21,random=4,amount=1},{type='baowu',id=46,random=4,amount=1},{type='baowu',id=47,random=4,amount=1},{type='baowu',id=48,random=4,amount=1},{type='baowu',id=49,random=4,amount=1},{type='baowu',id=50,random=4,amount=1},{type='baowu',id=51,random=4,amount=1},{type='baowu',id=76,random=4,amount=1},{type='baowu',id=77,random=4,amount=1},{type='baowu',id=78,random=4,amount=1},{type='baowu',id=79,random=4,amount=1},{type='baowu',id=80,random=4,amount=1},{type='baowu',id=81,random=4,amount=1},{type='baowu',id=172,random=4,amount=1},{type='baowu',id=183,random=4,amount=1},{type='baowu',id=184,random=4,amount=1},{type='baowu',id=193,random=4,amount=1},{type='baowu',id=194,random=4,amount=1},{type='baowu',id=203,random=4,amount=1},{type='baowu',id=204,random=4,amount=1},{type='baowu',id=213,random=4,amount=1},{type='baowu',id=214,random=4,amount=1},{type='baowu',id=223,random=4,amount=1},{type='baowu',id=224,random=4,amount=1}},
	},
	['1003019'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='cash',random=100,amount=3750}},
	},
	['1003020'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='cash',random=100,amount=4725}},
	},
	['1003021'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='cash',random=100,amount=5400}},
	},
	['1003022'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='cash',random=100,amount=6562}},
	},
	['1003023'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='cash',random=100,amount=7425}},
	},
	['1003024'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='cash',random=100,amount=8437}},
	},
	['1003025'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='cash',random=100,amount=30000}},
	},
	['1003026'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='honour',random=100,amount=200}},
	},
	['1003027'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=4,random=100,amount=30}},
	},
	['1003028'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=4,random=100,amount=15}},
	},
	['1003029'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=4,random=100,amount=10}},
	},
	['1003030'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=4,random=100,amount=6}},
	},
	['1003031'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=4,random=100,amount=3}},
	},
	['1003032'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=4,random=100,amount=40}},
	},
	['1003033'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=4,random=100,amount=25}},
	},
	['1003034'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=4,random=100,amount=15}},
	},
	['1003035'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=4,random=100,amount=8}},
	},
	['1003036'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=4,random=100,amount=4}},
	},
	['1003037'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=4,random=100,amount=60}},
	},
	['1003038'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=4,random=100,amount=30}},
	},
	['1003039'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=4,random=100,amount=20}},
	},
	['1003040'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=4,random=100,amount=12}},
	},
	['1003041'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=4,random=100,amount=6}},
	},
	['1003042'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=4,random=100,amount=70}},
	},
	['1003043'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=4,random=100,amount=40}},
	},
	['1003044'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=4,random=100,amount=25}},
	},
	['1003045'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=4,random=100,amount=15}},
	},
	['1003046'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=4,random=100,amount=7}},
	},
	['1003047'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=4,random=100,amount=90}},
	},
	['1003048'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=4,random=100,amount=45}},
	},
	['1003049'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=4,random=100,amount=30}},
	},
	['1003050'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=4,random=100,amount=18}},
	},
	['1003051'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=4,random=100,amount=9}},
	},
	['1003052'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=4,random=100,amount=100}},
	},
	['1003053'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=4,random=100,amount=50}},
	},
	['1003054'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=4,random=100,amount=35}},
	},
	['1003055'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=4,random=100,amount=20}},
	},
	['1003056'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=4,random=100,amount=10}},
	},
	['1004001'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1001,random=100,amount=6},{type='cash',random=100,amount=500}},
	},
	['1004002'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1101,random=100,amount=6},{type='cash',random=100,amount=500}},
	},
	['1004003'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1201,random=100,amount=6},{type='cash',random=100,amount=500}},
	},
	['1004004'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1301,random=100,amount=6},{type='cash',random=100,amount=500}},
	},
	['1004005'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1001,random=25,amount=6},{type='material',id=1101,random=25,amount=6},{type='material',id=1201,random=25,amount=6},{type='material',id=1301,random=25,amount=6}},
	},
	['1004006'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1002,random=100,amount=6},{type='cash',random=100,amount=1000}},
	},
	['1004007'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1102,random=100,amount=6},{type='cash',random=100,amount=1000}},
	},
	['1004008'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1202,random=100,amount=6},{type='cash',random=100,amount=1000}},
	},
	['1004009'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1302,random=100,amount=6},{type='cash',random=100,amount=1000}},
	},
	['1004010'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1002,random=25,amount=6},{type='material',id=1102,random=25,amount=6},{type='material',id=1202,random=25,amount=6},{type='material',id=1302,random=25,amount=6}},
	},
	['1004011'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1003,random=100,amount=6},{type='cash',random=100,amount=2500}},
	},
	['1004012'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1103,random=100,amount=6},{type='cash',random=100,amount=2500}},
	},
	['1004013'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1203,random=100,amount=6},{type='cash',random=100,amount=2500}},
	},
	['1004014'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1303,random=100,amount=6},{type='cash',random=100,amount=2500}},
	},
	['1004015'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1003,random=25,amount=6},{type='material',id=1103,random=25,amount=5},{type='material',id=1203,random=25,amount=5},{type='material',id=1303,random=25,amount=5}},
	},
	['1004016'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1004,random=100,amount=6},{type='cash',random=100,amount=3500}},
	},
	['1004017'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1104,random=100,amount=6},{type='cash',random=100,amount=3500}},
	},
	['1004018'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1204,random=100,amount=6},{type='cash',random=100,amount=3500}},
	},
	['1004019'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1304,random=100,amount=6},{type='cash',random=100,amount=3500}},
	},
	['1004020'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1004,random=25,amount=6},{type='material',id=1104,random=25,amount=6},{type='material',id=1204,random=25,amount=6},{type='material',id=1304,random=25,amount=6}},
	},
	['1004021'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1005,random=100,amount=6},{type='cash',random=100,amount=5000}},
	},
	['1004022'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1105,random=100,amount=6},{type='cash',random=100,amount=5000}},
	},
	['1004023'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1205,random=100,amount=6},{type='cash',random=100,amount=5000}},
	},
	['1004024'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1305,random=100,amount=6},{type='cash',random=100,amount=5000}},
	},
	['1004025'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1005,random=25,amount=6},{type='material',id=1105,random=25,amount=6},{type='material',id=1205,random=25,amount=6},{type='material',id=1305,random=25,amount=6}},
	},
	['1004026'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1006,random=100,amount=6},{type='cash',random=100,amount=6500}},
	},
	['1004027'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1106,random=100,amount=6},{type='cash',random=100,amount=6500}},
	},
	['1004028'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1206,random=100,amount=6},{type='cash',random=100,amount=6500}},
	},
	['1004029'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1306,random=100,amount=6},{type='cash',random=100,amount=6500}},
	},
	['1004030'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1006,random=25,amount=6},{type='material',id=1106,random=25,amount=6},{type='material',id=1206,random=25,amount=6},{type='material',id=1306,random=25,amount=6}},
	},
	['1004031'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1301,random=100,amount=3}},
	},
	['1014001'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1001,random=100,amount=12},{type='cash',random=100,amount=500}},
	},
	['1014002'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1101,random=100,amount=12},{type='cash',random=100,amount=500}},
	},
	['1014003'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1201,random=100,amount=12},{type='cash',random=100,amount=500}},
	},
	['1014004'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1301,random=100,amount=12},{type='cash',random=100,amount=500}},
	},
	['1014005'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1001,random=25,amount=12},{type='material',id=1101,random=25,amount=12},{type='material',id=1201,random=25,amount=12},{type='material',id=1301,random=25,amount=12}},
	},
	['1014006'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1002,random=100,amount=12},{type='cash',random=100,amount=1000}},
	},
	['1014007'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1102,random=100,amount=12},{type='cash',random=100,amount=1000}},
	},
	['1014008'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1202,random=100,amount=12},{type='cash',random=100,amount=1000}},
	},
	['1014009'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1302,random=100,amount=12},{type='cash',random=100,amount=1000}},
	},
	['1014010'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1002,random=25,amount=12},{type='material',id=1102,random=25,amount=12},{type='material',id=1202,random=25,amount=12},{type='material',id=1302,random=25,amount=12}},
	},
	['1014011'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1003,random=100,amount=12},{type='cash',random=100,amount=2500}},
	},
	['1014012'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1103,random=100,amount=12},{type='cash',random=100,amount=2500}},
	},
	['1014013'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1203,random=100,amount=12},{type='cash',random=100,amount=2500}},
	},
	['1014014'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1303,random=100,amount=12},{type='cash',random=100,amount=2500}},
	},
	['1014015'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1003,random=25,amount=12},{type='material',id=1103,random=25,amount=12},{type='material',id=1203,random=25,amount=12},{type='material',id=1303,random=25,amount=12}},
	},
	['1014016'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1004,random=100,amount=12},{type='cash',random=100,amount=3500}},
	},
	['1014017'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1104,random=100,amount=12},{type='cash',random=100,amount=3500}},
	},
	['1014018'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1204,random=100,amount=12},{type='cash',random=100,amount=3500}},
	},
	['1014019'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1304,random=100,amount=12},{type='cash',random=100,amount=3500}},
	},
	['1014020'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1004,random=25,amount=12},{type='material',id=1104,random=25,amount=12},{type='material',id=1204,random=25,amount=12},{type='material',id=1304,random=25,amount=12}},
	},
	['1014021'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1005,random=100,amount=12},{type='cash',random=100,amount=5000}},
	},
	['1014022'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1105,random=100,amount=12},{type='cash',random=100,amount=5000}},
	},
	['1014023'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1205,random=100,amount=12},{type='cash',random=100,amount=5000}},
	},
	['1014024'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1305,random=100,amount=12},{type='cash',random=100,amount=5000}},
	},
	['1014025'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1005,random=25,amount=12},{type='material',id=1105,random=25,amount=12},{type='material',id=1205,random=25,amount=12},{type='material',id=1305,random=25,amount=12}},
	},
	['1014026'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1006,random=100,amount=12},{type='cash',random=100,amount=6500}},
	},
	['1014027'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1106,random=100,amount=12},{type='cash',random=100,amount=6500}},
	},
	['1014028'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1206,random=100,amount=12},{type='cash',random=100,amount=6500}},
	},
	['1014029'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1306,random=100,amount=12},{type='cash',random=100,amount=6500}},
	},
	['1014030'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1006,random=25,amount=12},{type='material',id=1106,random=25,amount=12},{type='material',id=1206,random=25,amount=12},{type='material',id=1306,random=25,amount=12}},
	},
	['1014031'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1301,random=100,amount=3}},
	},
	['1004101'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='exp',random=100,amount=12}},
	},
	['1004102'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='exp',random=100,amount=12},{type='item',id=4,random=100,amount=6}},
	},
	['1004103'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='exp',random=100,amount=14}},
	},
	['1004104'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='exp',random=100,amount=14},{type='item',id=4,random=100,amount=6}},
	},
	['1004105'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='exp',random=100,amount=14}},
	},
	['1004106'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='exp',random=100,amount=14},{type='item',id=4,random=100,amount=9}},
	},
	['1004107'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='exp',random=100,amount=16}},
	},
	['1004108'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='exp',random=100,amount=16},{type='item',id=4,random=100,amount=9}},
	},
	['1004109'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='exp',random=100,amount=20}},
	},
	['1004110'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='exp',random=100,amount=20},{type='item',id=4,random=100,amount=9}},
	},
	['1004111'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='exp',random=100,amount=24}},
	},
	['1004112'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='exp',random=100,amount=24},{type='item',id=4,random=100,amount=9}},
	},
	['1004113'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='exp',random=100,amount=33}},
	},
	['1004114'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='exp',random=100,amount=33},{type='item',id=4,random=100,amount=12}},
	},
	['1004115'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='exp',random=100,amount=38}},
	},
	['1004116'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='exp',random=100,amount=38},{type='item',id=4,random=100,amount=12}},
	},
	['1004117'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='exp',random=100,amount=42}},
	},
	['1004118'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='exp',random=100,amount=42},{type='item',id=4,random=100,amount=12}},
	},
	['1004119'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='exp',random=100,amount=48}},
	},
	['1004120'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='exp',random=100,amount=48},{type='item',id=4,random=100,amount=12}},
	},
	['1004121'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='exp',random=100,amount=55}},
	},
	['1004122'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='exp',random=100,amount=55},{type='item',id=4,random=100,amount=15}},
	},
	['1004123'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='exp',random=100,amount=63}},
	},
	['1004124'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='exp',random=100,amount=63},{type='item',id=4,random=100,amount=15}},
	},
	['1004125'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='exp',random=100,amount=73}},
	},
	['1004126'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='exp',random=100,amount=73},{type='item',id=4,random=100,amount=15}},
	},
	['1004127'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='exp',random=100,amount=83}},
	},
	['1004128'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='exp',random=100,amount=83},{type='item',id=4,random=100,amount=15}},
	},
	['1004129'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='exp',random=100,amount=95}},
	},
	['1004130'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='exp',random=100,amount=95},{type='item',id=4,random=100,amount=15}},
	},
	['1004131'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='exp',random=100,amount=109}},
	},
	['1004132'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='exp',random=100,amount=109},{type='item',id=4,random=100,amount=18}},
	},
	['1004133'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='exp',random=100,amount=125}},
	},
	['1004134'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='exp',random=100,amount=125},{type='item',id=4,random=100,amount=18}},
	},
	['1004135'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='exp',random=100,amount=143}},
	},
	['1004136'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='exp',random=100,amount=143},{type='item',id=4,random=100,amount=18}},
	},
	['1004137'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='exp',random=100,amount=164}},
	},
	['1004138'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='exp',random=100,amount=164},{type='item',id=4,random=100,amount=18}},
	},
	['1004139'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='exp',random=100,amount=187}},
	},
	['1004140'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='exp',random=100,amount=187},{type='item',id=4,random=100,amount=18}},
	},
	['1004141'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='exp',random=100,amount=214}},
	},
	['1004142'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='exp',random=100,amount=214},{type='item',id=4,random=100,amount=20}},
	},
	['1004143'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='exp',random=100,amount=245}},
	},
	['1004144'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='exp',random=100,amount=245},{type='item',id=4,random=100,amount=20}},
	},
	['1004145'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='exp',random=100,amount=281}},
	},
	['1004146'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='exp',random=100,amount=281},{type='item',id=4,random=100,amount=20}},
	},
	['1004147'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='exp',random=100,amount=322}},
	},
	['1004148'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='exp',random=100,amount=322},{type='item',id=4,random=100,amount=20}},
	},
	['1004149'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='exp',random=100,amount=368}},
	},
	['1004150'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='exp',random=100,amount=368},{type='item',id=4,random=100,amount=20}},
	},
	['1004151'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='exp',random=100,amount=422}},
	},
	['1004152'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='exp',random=100,amount=422},{type='item',id=4,random=100,amount=20}},
	},
	['1004153'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='exp',random=100,amount=422}},
	},
	['1004154'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='exp',random=100,amount=422},{type='item',id=4,random=100,amount=20}},
	},
	['1004155'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='exp',random=100,amount=422}},
	},
	['1004156'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='exp',random=100,amount=422},{type='item',id=4,random=100,amount=20}},
	},
	['1005001'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='exp',random=100}},
	},
	['1005002'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='cash',random=100}},
	},
	['1005003'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='honour',random=100,amount=10}},
	},
	['1005004'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=1,random=100,amount=4}},
	},
	['1005005'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=1,random=100,amount=6}},
	},
	['1005006'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=2,random=100,amount=4}},
	},
	['1005007'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=2,random=100,amount=6}},
	},
	['1005008'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='keepsake',id=2,random=100,amount=1}},
	},
	['1005009'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='keepsake',id=3,random=100,amount=1}},
	},
	['1005010'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1001,random=25,amount=4},{type='material',id=1101,random=25,amount=4},{type='material',id=1201,random=25,amount=4},{type='material',id=1301,random=25,amount=4}},
	},
	['1005011'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1001,random=25,amount=8},{type='material',id=1101,random=25,amount=8},{type='material',id=1201,random=25,amount=8},{type='material',id=1301,random=25,amount=8}},
	},
	['1006001'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='gold',random=100,amount=50}},
	},
	['1006002'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='gold',random=100,amount=100}},
	},
	['1006003'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='gold',random=100,amount=50},{type='keepsake',id=3,random=100,amount=3}},
	},
	['1006004'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='gold',random=100,amount=50},{type='keepsake',id=4,random=100,amount=3}},
	},
	['1006005'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='gold',random=100,amount=50},{type='keepsake',id=5,random=100,amount=3}},
	},
	['1007001'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='gold',random=100,amount=10},{type='keepsake',id=4,random=100,amount=1}},
	},
	['1007002'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='gold',random=100,amount=50},{type='keepsake',id=5,random=100,amount=1}},
	},
	['EXP_BOOK'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=1,random=100,amount=1}},
	},
	['MATERIAL_1TO10'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1001,random=25,amount=2},{type='material',id=1101,random=25,amount=2},{type='material',id=1201,random=25,amount=2},{type='material',id=1301,random=25,amount=2}},
	},
	['MATERIAL_11TO20'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1002,random=25,amount=2},{type='material',id=1102,random=25,amount=2},{type='material',id=1202,random=25,amount=2},{type='material',id=1302,random=25,amount=2}},
	},
	['MATERIAL_21TO30'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1003,random=25,amount=2},{type='material',id=1103,random=25,amount=2},{type='material',id=1203,random=25,amount=2},{type='material',id=1303,random=25,amount=2}},
	},
	['MATERIAL_31TO40'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1004,random=25,amount=2},{type='material',id=1104,random=25,amount=2},{type='material',id=1204,random=25,amount=2},{type='material',id=1304,random=25,amount=2}},
	},
	['MATERIAL_41TO50'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1005,random=25,amount=2},{type='material',id=1105,random=25,amount=2},{type='material',id=1205,random=25,amount=2},{type='material',id=1305,random=25,amount=2}},
	},
	['MATERIAL_51TO60'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1006,random=25,amount=2},{type='material',id=1106,random=25,amount=2},{type='material',id=1206,random=25,amount=2},{type='material',id=1306,random=25,amount=2}},
	},
	['CATCH_PIRANHA'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=3,random=100,amount=3}},
	},
	['CATCH_MARMAID'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='item',id=1,random=75,amount=7},{type='item',id=3,random=25,amount=3}},
	},
	['FULL_SPEED_BUFF'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='status',id='explore_boat_speed',time=1800,args={}}},
	},
	['CATCH_MONSTER'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='item',id=3,random=100,amount=6}},
	},
	['SALVAGE_BOX'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='cash',random=90,amount=150},{type='item',id=3,random=10,amount=3}},
	},
	['SALVAGE_CASK'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='goods',random=50,amount=5},{type='food',random=50,amount=5}},
	},
	['GET_TREASURE'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = nil,
	},
	['SALVAGE_WRECK'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='cash',random=60,amount=2700},{type='item',id=3,random=20,amount=9},{type='item',id=4,random=20,amount=4.5}},
	},
	['TREASURE_PIECES_01'] = {
		['mode'] = 'RANDOM_ALL',
		['loot_table'] = {{type='item',id=3,random=5,amount=1}},
	},
	['TREASURE_PIECES_02'] = {
		['mode'] = 'RANDOM_ALL',
		['loot_table'] = {{type='item',id=3,random=5,amount=2}},
	},
	['TREASURE_PIECES_03'] = {
		['mode'] = 'RANDOM_ALL',
		['loot_table'] = {{type='item',id=3,random=5,amount=4}},
	},
	['TREASURE_PIECES_04'] = {
		['mode'] = 'RANDOM_ALL',
		['loot_table'] = {{type='item',id=3,random=5,amount=8}},
	},
	['TREASURE_PIECES_05'] = {
		['mode'] = 'RANDOM_ALL',
		['loot_table'] = {{type='item',id=3,random=5,amount=16}},
	},
	['plunder_win_1'] = {
		['mode'] = 'RANDOM_ALL',
		['loot_table'] = {{type='item',id=4,random=25,amount=1}},
	},
	['workshop_task1'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1001,random=100,amount=7}},
	},
	['workshop_task2'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1101,random=100,amount=7}},
	},
	['workshop_task3'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1201,random=100,amount=7}},
	},
	['workshop_task4'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1301,random=100,amount=7}},
	},
	['workshop_task5'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1002,random=100,amount=7}},
	},
	['workshop_task6'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1102,random=100,amount=7}},
	},
	['workshop_task7'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1202,random=100,amount=7}},
	},
	['workshop_task8'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1302,random=100,amount=7}},
	},
	['workshop_task9'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1003,random=100,amount=7}},
	},
	['workshop_task10'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1103,random=100,amount=7}},
	},
	['workshop_task11'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1203,random=100,amount=7}},
	},
	['workshop_task12'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1303,random=100,amount=7}},
	},
	['workshop_task13'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1004,random=100,amount=7}},
	},
	['workshop_task14'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1104,random=100,amount=7}},
	},
	['workshop_task15'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1204,random=100,amount=7}},
	},
	['workshop_task16'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1304,random=100,amount=7}},
	},
	['workshop_task17'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1005,random=100,amount=7}},
	},
	['workshop_task18'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1105,random=100,amount=7}},
	},
	['workshop_task19'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1205,random=100,amount=7}},
	},
	['workshop_task20'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1305,random=100,amount=7}},
	},
	['workshop_task21'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1006,random=100,amount=7}},
	},
	['workshop_task22'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1106,random=100,amount=7}},
	},
	['workshop_task23'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1206,random=100,amount=7}},
	},
	['workshop_task24'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='material',id=1306,random=100,amount=7}},
	},
	['mission1'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=6,amount=1}},
	},
	['mission2'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='honour',amount=40}},
	},
	['mission3'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='gold',random=100,amount=5}},
	},
	['mission4'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=1,amount=1}},
	},
	['mission5'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1001,random=100,amount=6},{type='material',id=1101,random=100,amount=6},{type='material',id=1201,random=100,amount=6},{type='material',id=1301,random=100,amount=6}},
	},
	['mission6'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='keepsake',id=2,random=100,amount=1}},
	},
	['mission7'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=1,amount=2}},
	},
	['mission8'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1002,random=100,amount=6},{type='material',id=1102,random=100,amount=6},{type='material',id=1202,random=100,amount=6},{type='material',id=1302,random=100,amount=6}},
	},
	['mission9'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='keepsake',id=2,random=100,amount=2}},
	},
	['mission10'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=1,amount=3}},
	},
	['mission11'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1003,random=100,amount=6},{type='material',id=1103,random=100,amount=6},{type='material',id=1203,random=100,amount=6},{type='material',id=1303,random=100,amount=6}},
	},
	['mission12'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='keepsake',id=3,random=100,amount=1}},
	},
	['mission13'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=1,amount=4}},
	},
	['mission14'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1004,random=100,amount=6},{type='material',id=1104,random=100,amount=6},{type='material',id=1204,random=100,amount=6},{type='material',id=1304,random=100,amount=6}},
	},
	['mission15'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='keepsake',id=3,random=100,amount=2}},
	},
	['mission16'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=1,amount=5}},
	},
	['mission17'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1005,random=100,amount=6},{type='material',id=1105,random=100,amount=6},{type='material',id=1205,random=100,amount=6},{type='material',id=1305,random=100,amount=6}},
	},
	['mission18'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='keepsake',id=3,random=100,amount=3}},
	},
	['mission19'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=1,amount=6}},
	},
	['mission20'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1006,random=100,amount=6},{type='material',id=1106,random=100,amount=6},{type='material',id=1206,random=100,amount=6},{type='material',id=1306,random=100,amount=6}},
	},
	['mission21'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='keepsake',id=4,random=100,amount=1}},
	},
	['mission22'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=1,amount=7}},
	},
	['mission23'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1006,random=100,amount=6},{type='material',id=1106,random=100,amount=6},{type='material',id=1206,random=100,amount=6},{type='material',id=1306,random=100,amount=6}},
	},
	['mission24'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='keepsake',id=4,random=100,amount=1}},
	},
	['foundry_task1'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='baowu',id=168,amount=1}},
	},
	['foundry_task2'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='baowu',id=178,amount=1}},
	},
	['foundry_task3'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='baowu',id=188,amount=1},{type='baowu',id=218,amount=1}},
	},
	['foundry_task4'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='baowu',id=208,amount=1}},
	},
	['foundry_task5'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='baowu',id=198,amount=1}},
	},
	['foundry_task6'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='baowu',id=169,amount=1}},
	},
	['foundry_task7'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='baowu',id=179,amount=1}},
	},
	['foundry_task8'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='baowu',id=189,amount=1},{type='baowu',id=219,amount=1}},
	},
	['foundry_task9'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='baowu',id=209,amount=1}},
	},
	['foundry_task10'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='baowu',id=199,amount=1}},
	},
	['foundry_task11'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='baowu',id=170,amount=1}},
	},
	['foundry_task12'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='baowu',id=180,amount=1}},
	},
	['foundry_task13'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='baowu',id=190,amount=1},{type='baowu',id=220,amount=1}},
	},
	['foundry_task14'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='baowu',id=210,amount=1}},
	},
	['foundry_task15'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='baowu',id=200,amount=1}},
	},
	['foundry_task16'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='baowu',id=171,amount=1}},
	},
	['foundry_task17'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='baowu',id=181,amount=1},{type='baowu',id=182,amount=1}},
	},
	['foundry_task18'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='baowu',id=191,amount=1},{type='baowu',id=192,amount=1},{type='baowu',id=221,amount=1},{type='baowu',id=222,amount=1}},
	},
	['foundry_task19'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='baowu',id=211,amount=1},{type='baowu',id=212,amount=1}},
	},
	['foundry_task20'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='baowu',id=201,amount=1},{type='baowu',id=202,amount=1}},
	},
	['foundry_task21'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='baowu',id=172,amount=1}},
	},
	['foundry_task22'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='baowu',id=183,amount=1},{type='baowu',id=184,amount=1}},
	},
	['foundry_task23'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='baowu',id=193,amount=1},{type='baowu',id=194,amount=1},{type='baowu',id=223,amount=1},{type='baowu',id=224,amount=1}},
	},
	['foundry_task24'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='baowu',id=213,amount=1},{type='baowu',id=214,amount=1}},
	},
	['foundry_task25'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='baowu',id=203,amount=1},{type='baowu',id=204,amount=1}},
	},
	['recruit_d1'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1002,random=25,amount=5},{type='material',id=1102,random=25,amount=5},{type='material',id=1202,random=25,amount=5},{type='material',id=1302,random=25,amount=5}},
	},
	['recruit_d2'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=1,random=100,amount=8}},
	},
	['recruit_d3'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=4,random=100,amount=1}},
	},
	['recruit_d4'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=3,random=100,amount=2}},
	},
	['recruit_d5'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='keepsake',id=3,random=100,amount=1}},
	},
	['recruit_c1'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1003,random=25,amount=5},{type='material',id=1103,random=25,amount=5},{type='material',id=1203,random=25,amount=5},{type='material',id=1303,random=25,amount=5}},
	},
	['recruit_c2'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=1,random=100,amount=16}},
	},
	['recruit_c3'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=4,random=100,amount=2}},
	},
	['recruit_c4'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=3,random=100,amount=5}},
	},
	['recruit_c5'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='keepsake',id=4,random=100,amount=1}},
	},
	['recruit_b1'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1004,random=25,amount=5},{type='material',id=1104,random=25,amount=5},{type='material',id=1204,random=25,amount=5},{type='material',id=1304,random=25,amount=5}},
	},
	['recruit_b2'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=1,random=100,amount=24}},
	},
	['recruit_b3'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=4,random=100,amount=3}},
	},
	['recruit_b4'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=3,random=100,amount=10}},
	},
	['recruit_b5'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='keepsake',id=5,random=100,amount=1}},
	},
	['recruit_a1'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1005,random=25,amount=5},{type='material',id=1105,random=25,amount=5},{type='material',id=1205,random=25,amount=5},{type='material',id=1305,random=25,amount=5}},
	},
	['recruit_a2'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=1,random=100,amount=32}},
	},
	['recruit_a3'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=4,random=100,amount=4}},
	},
	['recruit_a4'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=3,random=100,amount=20}},
	},
	['recruit_a5'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='keepsake',id=6,random=100,amount=1}},
	},
	['recruit_s1'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1006,random=25,amount=5},{type='material',id=1106,random=25,amount=5},{type='material',id=1206,random=25,amount=5},{type='material',id=1306,random=25,amount=5}},
	},
	['recruit_s2'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=1,random=100,amount=40}},
	},
	['recruit_s3'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=4,random=100,amount=5}},
	},
	['recruit_s4'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=3,random=100,amount=40}},
	},
	['recruit_s5'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='baowu',id=10,random=10,amount=1},{type='baowu',id=11,random=10,amount=1},{type='baowu',id=12,random=10,amount=1},{type='baowu',id=13,random=10,amount=1},{type='baowu',id=14,random=10,amount=1},{type='baowu',id=15,random=10,amount=1},{type='baowu',id=40,random=10,amount=1},{type='baowu',id=41,random=10,amount=1},{type='baowu',id=42,random=10,amount=1},{type='baowu',id=43,random=10,amount=1},{type='baowu',id=44,random=10,amount=1},{type='baowu',id=45,random=10,amount=1},{type='baowu',id=70,random=10,amount=1},{type='baowu',id=71,random=10,amount=1},{type='baowu',id=72,random=10,amount=1},{type='baowu',id=73,random=10,amount=1},{type='baowu',id=74,random=10,amount=1},{type='baowu',id=75,random=10,amount=1},},
	},
	['guild_boss1'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='baowu',id=1,random=8,amount=1},{type='baowu',id=2,random=8,amount=1},{type='baowu',id=3,random=8,amount=1},{type='baowu',id=31,random=8,amount=1},{type='baowu',id=32,random=8,amount=1},{type='baowu',id=33,random=8,amount=1},{type='baowu',id=61,random=8,amount=1},{type='baowu',id=62,random=8,amount=1},{type='baowu',id=63,random=8,amount=1},{type='baowu',id=168,random=8,amount=1},{type='baowu',id=178,random=8,amount=1},{type='baowu',id=188,random=8,amount=1},{type='baowu',id=198,random=8,amount=1},{type='baowu',id=208,random=8,amount=1},{type='baowu',id=218,random=8,amount=1}},
	},
	['guild_boss2'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='baowu',id=4,random=8,amount=1},{type='baowu',id=5,random=8,amount=1},{type='baowu',id=6,random=8,amount=1},{type='baowu',id=34,random=8,amount=1},{type='baowu',id=35,random=8,amount=1},{type='baowu',id=36,random=8,amount=1},{type='baowu',id=64,random=8,amount=1},{type='baowu',id=65,random=8,amount=1},{type='baowu',id=66,random=8,amount=1},{type='baowu',id=169,random=8,amount=1},{type='baowu',id=179,random=8,amount=1},{type='baowu',id=189,random=8,amount=1},{type='baowu',id=199,random=8,amount=1},{type='baowu',id=209,random=8,amount=1},{type='baowu',id=219,random=8,amount=1}},
	},
	['guild_boss3'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='baowu',id=7,random=8,amount=1},{type='baowu',id=8,random=8,amount=1},{type='baowu',id=9,random=8,amount=1},{type='baowu',id=37,random=8,amount=1},{type='baowu',id=38,random=8,amount=1},{type='baowu',id=39,random=8,amount=1},{type='baowu',id=67,random=8,amount=1},{type='baowu',id=68,random=8,amount=1},{type='baowu',id=69,random=8,amount=1},{type='baowu',id=170,random=8,amount=1},{type='baowu',id=180,random=8,amount=1},{type='baowu',id=190,random=8,amount=1},{type='baowu',id=200,random=8,amount=1},{type='baowu',id=210,random=8,amount=1},{type='baowu',id=220,random=8,amount=1}},
	},
	['guild_boss4'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='baowu',id=10,random=4,amount=1},{type='baowu',id=11,random=4,amount=1},{type='baowu',id=12,random=4,amount=1},{type='baowu',id=13,random=4,amount=1},{type='baowu',id=14,random=4,amount=1},{type='baowu',id=15,random=4,amount=1},{type='baowu',id=40,random=4,amount=1},{type='baowu',id=41,random=4,amount=1},{type='baowu',id=42,random=4,amount=1},{type='baowu',id=43,random=4,amount=1},{type='baowu',id=44,random=4,amount=1},{type='baowu',id=45,random=4,amount=1},{type='baowu',id=70,random=4,amount=1},{type='baowu',id=71,random=4,amount=1},{type='baowu',id=72,random=4,amount=1},{type='baowu',id=73,random=4,amount=1},{type='baowu',id=74,random=4,amount=1},{type='baowu',id=75,random=4,amount=1},{type='baowu',id=171,random=4,amount=1},{type='baowu',id=181,random=4,amount=1},{type='baowu',id=182,random=4,amount=1},{type='baowu',id=191,random=4,amount=1},{type='baowu',id=192,random=4,amount=1},{type='baowu',id=201,random=4,amount=1},{type='baowu',id=202,random=4,amount=1},{type='baowu',id=211,random=4,amount=1},{type='baowu',id=212,random=4,amount=1},{type='baowu',id=221,random=4,amount=1},{type='baowu',id=222,random=4,amount=1}},
	},
	['guild_boss5'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='baowu',id=16,random=4,amount=1},{type='baowu',id=17,random=4,amount=1},{type='baowu',id=18,random=4,amount=1},{type='baowu',id=19,random=4,amount=1},{type='baowu',id=20,random=4,amount=1},{type='baowu',id=21,random=4,amount=1},{type='baowu',id=46,random=4,amount=1},{type='baowu',id=47,random=4,amount=1},{type='baowu',id=48,random=4,amount=1},{type='baowu',id=49,random=4,amount=1},{type='baowu',id=50,random=4,amount=1},{type='baowu',id=51,random=4,amount=1},{type='baowu',id=76,random=4,amount=1},{type='baowu',id=77,random=4,amount=1},{type='baowu',id=78,random=4,amount=1},{type='baowu',id=79,random=4,amount=1},{type='baowu',id=80,random=4,amount=1},{type='baowu',id=81,random=4,amount=1},{type='baowu',id=172,random=4,amount=1},{type='baowu',id=183,random=4,amount=1},{type='baowu',id=184,random=4,amount=1},{type='baowu',id=193,random=4,amount=1},{type='baowu',id=194,random=4,amount=1},{type='baowu',id=203,random=4,amount=1},{type='baowu',id=204,random=4,amount=1},{type='baowu',id=213,random=4,amount=1},{type='baowu',id=214,random=4,amount=1},{type='baowu',id=223,random=4,amount=1},{type='baowu',id=224,random=4,amount=1}},
	},
	['guild_boss6'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='keepsake',id=5,random=100,amount=1}},
	},
	['guild_boss7'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=3,random=100,amount=10}},
	},
	['guild_boss8'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=3,random=100,amount=15}},
	},
	['guild_boss9'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=3,random=100,amount=25}},
	},
	['guild_boss10'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=3,random=100,amount=50}},
	},
	['guild_boss11'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=3,random=100,amount=100}},
	},
	['guild_boss12'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=3,random=100,amount=200}},
	},
	['guild_boss13'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=4,random=100,amount=8}},
	},
	['guild_boss14'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='honour',random=100,amount=80}},
	},
	['guild_boss15'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1001,random=25,amount=80},{type='material',id=1101,random=25,amount=80},{type='material',id=1201,random=25,amount=80},{type='material',id=1301,random=25,amount=80}},
	},
	['guild_boss16'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1002,random=25,amount=80},{type='material',id=1102,random=25,amount=80},{type='material',id=1202,random=25,amount=80},{type='material',id=1302,random=25,amount=81}},
	},
	['guild_boss17'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1003,random=25,amount=80},{type='material',id=1103,random=25,amount=80},{type='material',id=1203,random=25,amount=80},{type='material',id=1303,random=25,amount=81}},
	},
	['guild_boss18'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1004,random=25,amount=80},{type='material',id=1104,random=25,amount=80},{type='material',id=1204,random=25,amount=80},{type='material',id=1304,random=25,amount=81}},
	},
	['guild_boss19'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1005,random=25,amount=80},{type='material',id=1105,random=25,amount=80},{type='material',id=1205,random=25,amount=80},{type='material',id=1305,random=25,amount=81}},
	},
	['guild_boss20'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1006,random=25,amount=80},{type='material',id=1106,random=25,amount=80},{type='material',id=1206,random=25,amount=80},{type='material',id=1306,random=25,amount=81}},
	},
	['guild_misson1'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = nil,
	},
	['guild_misson2'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = nil,
	},
	['guild_misson3'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = nil,
	},
	['boatdrawings_sell1'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='cash',random=100,amount=1200}},
	},
	['boatdrawings_sell2'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='cash',random=100,amount=1400}},
	},
	['boatdrawings_sell3'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='cash',random=100,amount=2200}},
	},
	['boatdrawings_sell5'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='cash',random=100,amount=2400}},
	},
	['boatdrawings_sell6'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='cash',random=100,amount=2600}},
	},
	['boatdrawings_sell7'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='cash',random=100,amount=3400}},
	},
	['boatdrawings_sell8'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='cash',random=100,amount=3600}},
	},
	['boatdrawings_sell9'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='cash',random=100,amount=3800}},
	},
	['boatdrawings_sell10'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='cash',random=100,amount=4800}},
	},
	['boatdrawings_sell11'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='cash',random=100,amount=5000}},
	},
	['boatdrawings_sell12'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='cash',random=100,amount=5200}},
	},
	['boatdrawings_sell13'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='cash',random=100,amount=7300}},
	},
	['boatdrawings_sell14'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='cash',random=100,amount=7400}},
	},
	['boatdrawings_sell15'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='cash',random=100,amount=7500}},
	},
	['boatdrawings_sell16'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='cash',random=100,amount=7600}},
	},
	['boatdrawings_sell17'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='cash',random=100,amount=9000}},
	},
	['boatdrawings_sell18'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='cash',random=100,amount=10000}},
	},
	['boatdrawings_sell19'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='cash',random=100,amount=11000}},
	},
	['boatdrawings_sell20'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='cash',random=100,amount=12500}},
	},
	['boatdrawings_sell21'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='cash',random=100,amount=13500}},
	},
	['boatdrawings_sell22'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='cash',random=100,amount=14500}},
	},
	['boatdrawings_sell23'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='honour',random=100,amount=20}},
	},
	['boatdrawings_sell24'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='honour',random=100,amount=30}},
	},
	['boatdrawings_sell25'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='honour',random=100,amount=35}},
	},
	['boatdrawings_sell26'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='honour',random=100,amount=40}},
	},
	['boatdrawings_sell27'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='honour',random=100,amount=45}},
	},
	['boatdrawings_sell28'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='honour',random=100,amount=55}},
	},
	['boatdrawings_sell29'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='honour',random=100,amount=60}},
	},
	['boatdrawings_sell30'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='honour',random=100,amount=65}},
	},
	['boatdrawings_sell31'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='honour',random=100,amount=75}},
	},
	['boatdrawings_sell32'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='honour',random=100,amount=80}},
	},
	['boatdrawings_sell33'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='honour',random=100,amount=85}},
	},
	['boatdrawings_sell34'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='honour',random=100,amount=95}},
	},
	['boatdrawings_sell35'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='honour',random=100,amount=100}},
	},
	['boatdrawings_sell36'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='honour',random=100,amount=105}},
	},
	['boatdrawings_sell37'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='honour',random=100,amount=110}},
	},
	['boatdrawings_sell38'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='honour',random=100,amount=115}},
	},
	['boatdrawings_sell39'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='honour',random=100,amount=120}},
	},
	['boatdrawings_sell40'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='honour',random=100,amount=125}},
	},
	['boatdrawings_sell41'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='honour',random=100,amount=135}},
	},
	['boatdrawings_sell42'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='honour',random=100,amount=140}},
	},
	['boatdrawings_sell43'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='honour',random=100,amount=145}},
	},
	['boatdrawings_qinmu'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='item',id=8,random=95,amount=1},{type='item',id=29,random=5,amount=1}},
	},
	['boatdrawings_sanjiao'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='item',id=9,random=95,amount=1},{type='item',id=30,random=5,amount=1}},
	},
	['boatdrawings_kalaweier'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='item',id=10,random=95,amount=1},{type='item',id=31,random=5,amount=1}},
	},
	['boatdrawings_hansa'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='item',id=11,random=95,amount=1},{type='item',id=32,random=5,amount=1}},
	},
	['boatdrawings_wuzhuang'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='item',id=12,random=95,amount=1},{type='item',id=33,random=5,amount=1}},
	},
	['boatdrawings_alabo'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='item',id=13,random=95,amount=1},{type='item',id=34,random=5,amount=1}},
	},
	['boatdrawings_lvmeimao'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='item',id=14,random=95,amount=1},{type='item',id=35,random=5,amount=1}},
	},
	['boatdrawings_anzhai'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='item',id=15,random=95,amount=1},{type='item',id=36,random=5,amount=1}},
	},
	['boatdrawings_jialai'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='item',id=16,random=95,amount=1},{type='item',id=37,random=5,amount=1}},
	},
	['boatdrawings_dachang'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='item',id=17,random=95,amount=1},{type='item',id=38,random=5,amount=1}},
	},
	['boatdrawings_guijia'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='item',id=18,random=95,amount=1},{type='item',id=39,random=5,amount=1}},
	},
	['boatdrawings_xibanyadafan'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='item',id=19,random=95,amount=1},{type='item',id=40,random=5,amount=1}},
	},
	['boatdrawings_weinisi'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='item',id=20,random=95,amount=1},{type='item',id=41,random=5,amount=1}},
	},
	['boatdrawings_dafu'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='item',id=21,random=95,amount=1},{type='item',id=42,random=5,amount=1}},
	},
	['boatdrawings_wudipaojian'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='item',id=22,random=95,amount=1},{type='item',id=43,random=5,amount=1}},
	},
	['boat_breakup1'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1001,random=25,amount=6},{type='material',id=1101,random=25,amount=6},{type='material',id=1201,random=25,amount=6},{type='material',id=1301,random=25,amount=6}},
	},
	['boat_breakup2'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1002,random=25,amount=6},{type='material',id=1102,random=25,amount=6},{type='material',id=1202,random=25,amount=6},{type='material',id=1302,random=25,amount=6}},
	},
	['boat_breakup3'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1003,random=25,amount=6},{type='material',id=1103,random=25,amount=6},{type='material',id=1203,random=25,amount=6},{type='material',id=1303,random=25,amount=6}},
	},
	['boat_breakup4'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1004,random=25,amount=6},{type='material',id=1104,random=25,amount=6},{type='material',id=1204,random=25,amount=6},{type='material',id=1304,random=25,amount=6}},
	},
	['boat_breakup5'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1005,random=25,amount=6},{type='material',id=1105,random=25,amount=6},{type='material',id=1205,random=25,amount=6},{type='material',id=1305,random=25,amount=6}},
	},
	['boat_breakup6'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1006,random=25,amount=6},{type='material',id=1106,random=25,amount=6},{type='material',id=1206,random=25,amount=6},{type='material',id=1306,random=25,amount=6}},
	},
	['boat_breakup7'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1006,random=25,amount=12},{type='material',id=1106,random=25,amount=12},{type='material',id=1206,random=25,amount=12},{type='material',id=1306,random=25,amount=12}},
	},
	['boat_breakup8'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1001,random=25,amount=6},{type='material',id=1101,random=25,amount=6},{type='material',id=1201,random=25,amount=6},{type='material',id=1301,random=25,amount=6}},
	},
	['boat_breakup9'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1002,random=25,amount=6},{type='material',id=1102,random=25,amount=6},{type='material',id=1202,random=25,amount=6},{type='material',id=1302,random=25,amount=6}},
	},
	['boat_breakup10'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1003,random=25,amount=6},{type='material',id=1103,random=25,amount=6},{type='material',id=1203,random=25,amount=6},{type='material',id=1303,random=25,amount=6}},
	},
	['boat_breakup11'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1004,random=25,amount=6},{type='material',id=1104,random=25,amount=6},{type='material',id=1204,random=25,amount=6},{type='material',id=1304,random=25,amount=6}},
	},
	['boat_breakup12'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1005,random=25,amount=6},{type='material',id=1105,random=25,amount=6},{type='material',id=1205,random=25,amount=6},{type='material',id=1305,random=25,amount=6}},
	},
	['boat_breakup13'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1006,random=25,amount=6},{type='material',id=1106,random=25,amount=6},{type='material',id=1206,random=25,amount=6},{type='material',id=1306,random=25,amount=6}},
	},
	['boat_breakup14'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='material',id=1006,random=25,amount=12},{type='material',id=1106,random=25,amount=12},{type='material',id=1206,random=25,amount=12},{type='material',id=1306,random=25,amount=12}},
	},
	['LOGIN_REWARD_1'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = nil,
	},
	['LOGIN_REWARD_2'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = nil,
	},
	['LOGIN_REWARD_3'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = nil,
	},
	['LOGIN_REWARD_4'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = nil,
	},
	['LOGIN_REWARD_5'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = nil,
	},
	['LOGIN_REWARD_6'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = nil,
	},
	['LOGIN_REWARD_7'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = nil,
	},
	['guildshop_baowu1'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='baowu',id=1,random=8,amount=1},{type='baowu',id=2,random=8,amount=1},{type='baowu',id=3,random=8,amount=1},{type='baowu',id=31,random=8,amount=1},{type='baowu',id=32,random=8,amount=1},{type='baowu',id=33,random=8,amount=1},{type='baowu',id=61,random=8,amount=1},{type='baowu',id=62,random=8,amount=1},{type='baowu',id=63,random=8,amount=1},{type='baowu',id=168,random=8,amount=1},{type='baowu',id=178,random=8,amount=1},{type='baowu',id=188,random=8,amount=1},{type='baowu',id=198,random=8,amount=1},{type='baowu',id=208,random=8,amount=1},{type='baowu',id=218,random=8,amount=1}},
	},
	['guildshop_baowu2'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='baowu',id=4,random=8,amount=1},{type='baowu',id=5,random=8,amount=1},{type='baowu',id=6,random=8,amount=1},{type='baowu',id=34,random=8,amount=1},{type='baowu',id=35,random=8,amount=1},{type='baowu',id=36,random=8,amount=1},{type='baowu',id=64,random=8,amount=1},{type='baowu',id=65,random=8,amount=1},{type='baowu',id=66,random=8,amount=1},{type='baowu',id=169,random=8,amount=1},{type='baowu',id=179,random=8,amount=1},{type='baowu',id=189,random=8,amount=1},{type='baowu',id=199,random=8,amount=1},{type='baowu',id=209,random=8,amount=1},{type='baowu',id=219,random=8,amount=1}},
	},
	['guildshop_baowu3'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='baowu',id=7,random=8,amount=1},{type='baowu',id=8,random=8,amount=1},{type='baowu',id=9,random=8,amount=1},{type='baowu',id=37,random=8,amount=1},{type='baowu',id=38,random=8,amount=1},{type='baowu',id=39,random=8,amount=1},{type='baowu',id=67,random=8,amount=1},{type='baowu',id=68,random=8,amount=1},{type='baowu',id=69,random=8,amount=1},{type='baowu',id=170,random=8,amount=1},{type='baowu',id=180,random=8,amount=1},{type='baowu',id=190,random=8,amount=1},{type='baowu',id=200,random=8,amount=1},{type='baowu',id=210,random=8,amount=1},{type='baowu',id=220,random=8,amount=1}},
	},
	['guildshop_baowu4'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='baowu',id=10,random=4,amount=1},{type='baowu',id=11,random=4,amount=1},{type='baowu',id=12,random=4,amount=1},{type='baowu',id=13,random=4,amount=1},{type='baowu',id=14,random=4,amount=1},{type='baowu',id=15,random=4,amount=1},{type='baowu',id=40,random=4,amount=1},{type='baowu',id=41,random=4,amount=1},{type='baowu',id=42,random=4,amount=1},{type='baowu',id=43,random=4,amount=1},{type='baowu',id=44,random=4,amount=1},{type='baowu',id=45,random=4,amount=1},{type='baowu',id=70,random=4,amount=1},{type='baowu',id=71,random=4,amount=1},{type='baowu',id=72,random=4,amount=1},{type='baowu',id=73,random=4,amount=1},{type='baowu',id=74,random=4,amount=1},{type='baowu',id=75,random=4,amount=1},{type='baowu',id=171,random=4,amount=1},{type='baowu',id=181,random=4,amount=1},{type='baowu',id=182,random=4,amount=1},{type='baowu',id=191,random=4,amount=1},{type='baowu',id=192,random=4,amount=1},{type='baowu',id=201,random=4,amount=1},{type='baowu',id=202,random=4,amount=1},{type='baowu',id=211,random=4,amount=1},{type='baowu',id=212,random=4,amount=1},{type='baowu',id=221,random=4,amount=1},{type='baowu',id=222,random=4,amount=1}},
	},
	['guildshop_baowu5'] = {
		['mode'] = 'RANDOM_ONE',
		['loot_table'] = {{type='baowu',id=16,random=4,amount=1},{type='baowu',id=17,random=4,amount=1},{type='baowu',id=18,random=4,amount=1},{type='baowu',id=19,random=4,amount=1},{type='baowu',id=20,random=4,amount=1},{type='baowu',id=21,random=4,amount=1},{type='baowu',id=46,random=4,amount=1},{type='baowu',id=47,random=4,amount=1},{type='baowu',id=48,random=4,amount=1},{type='baowu',id=49,random=4,amount=1},{type='baowu',id=50,random=4,amount=1},{type='baowu',id=51,random=4,amount=1},{type='baowu',id=76,random=4,amount=1},{type='baowu',id=77,random=4,amount=1},{type='baowu',id=78,random=4,amount=1},{type='baowu',id=79,random=4,amount=1},{type='baowu',id=80,random=4,amount=1},{type='baowu',id=81,random=4,amount=1},{type='baowu',id=172,random=4,amount=1},{type='baowu',id=183,random=4,amount=1},{type='baowu',id=184,random=4,amount=1},{type='baowu',id=193,random=4,amount=1},{type='baowu',id=194,random=4,amount=1},{type='baowu',id=203,random=4,amount=1},{type='baowu',id=204,random=4,amount=1},{type='baowu',id=213,random=4,amount=1},{type='baowu',id=214,random=4,amount=1},{type='baowu',id=223,random=4,amount=1},{type='baowu',id=224,random=4,amount=1}},
	},
	['dailyrace1'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=4,amount=40}},
	},
	['dailyrace2'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=4,amount=30}},
	},
	['dailyrace3'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=4,amount=20}},
	},
	['dailyrace4'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=4,amount=10}},
	},
	['dailyrace5'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='honour',random=100,amount=200}},
	},
	['dailyrace6'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='honour',random=100,amount=150}},
	},
	['dailyrace7'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='honour',random=100,amount=100}},
	},
	['dailyrace8'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='honour',random=100,amount=50}},
	},
	['yiji_rongyu_01'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='honour',amount=50}},
	},
	['yiji_rongyu_02'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='honour',amount=100}},
	},
	['yiji_rongyu_03'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='honour',amount=150}},
	},
	['yiji_rongyu_04'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='honour',amount=200}},
	},
	['yiji_zicai_01'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=4,amount=10}},
	},
	['yiji_zicai_02'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=4,amount=20}},
	},
	['yiji_zicai_03'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=4,amount=30}},
	},
	['yiji_zicai_04'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=4,amount=40}},
	},
	['yiji_jinghua_01'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=3,amount=2}},
	},
	['yiji_jinghua_02'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=3,amount=6}},
	},
	['yiji_jinghua_03'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=3,amount=24}},
	},
	['yiji_jinghua_04'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='item',id=3,amount=96}},
	},
	['yiji_baowu_01'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='baowu',id=39,amount=1}},
	},
	['yiji_baowu_02'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='baowu',id=8,amount=1}},
	},
	['yiji_baowu_03'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='baowu',id=14,amount=1}},
	},
	['yiji_baowu_04'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='baowu',id=19,amount=1}},
	},
	['yiji_baowu_05'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='baowu',id=68,amount=1}},
	},
	['yiji_baowu_06'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='baowu',id=220,amount=1}},
	},
	['yiji_baowu_07'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='baowu',id=10,amount=1}},
	},
	['yiji_baowu_08'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='baowu',id=49,amount=1}},
	},
	['yiji_baowu_09'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='baowu',id=200,amount=1}},
	},
	['yiji_baowu_10'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='baowu',id=171,amount=1}},
	},
	['yiji_baowu_11'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='baowu',id=16,amount=1}},
	},
	['yiji_baowu_12'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='baowu',id=9,amount=1}},
	},
	['yiji_baowu_13'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='baowu',id=210,amount=1}},
	},
	['yiji_baowu_14'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='baowu',id=11,amount=1}},
	},
	['yiji_baowu_15'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='baowu',id=78,amount=1}},
	},
	['yiji_baowu_16'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='baowu',id=7,amount=1}},
	},
	['yiji_baowu_17'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='baowu',id=190,amount=1}},
	},
	['yiji_baowu_18'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='baowu',id=69,amount=1}},
	},
	['yiji_baowu_19'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='baowu',id=71,amount=1}},
	},
	['yiji_baowu_20'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='baowu',id=21,amount=1}},
	},
	['yiji_baowu_21'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='baowu',id=170,amount=1}},
	},
	['yiji_baowu_22'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='baowu',id=41,amount=1}},
	},
	['yiji_baowu_23'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='baowu',id=44,amount=1}},
	},
	['yiji_baowu_24'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='baowu',id=46,amount=1}},
	},
	['yiji_baowu_25'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='baowu',id=180,amount=1}},
	},
	['yiji_baowu_26'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='baowu',id=191,amount=1}},
	},
	['yiji_baowu_27'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='baowu',id=74,amount=1}},
	},
	['yiji_baowu_28'] = {
		['mode'] = 'GET_ALL',
		['loot_table'] = {{type='baowu',id=194,amount=1}},
	},
}

return random_loot_info