-- ------------------------------
-- desc: generated by xls2data.py
-- source: config.xls
-- sheet: 遗迹星级
-- ------------------------------


local relic_star_info = {
	[1] = {
		['explorePoint'] = 10,
		['cash'] = 2000,
		['skill'] = 70,
	},
	[2] = {
		['explorePoint'] = 30,
		['cash'] = 4000,
		['skill'] = 140,
	},
	[3] = {
		['explorePoint'] = 60,
		['cash'] = 10000,
		['skill'] = 250,
	},
	[4] = {
		['explorePoint'] = 100,
		['cash'] = 20000,
		['skill'] = 450,
	},
	[5] = {
		['explorePoint'] = 150,
		['cash'] = 40000,
		['skill'] = 720,
	},
}

return relic_star_info