-- ------------------------------
-- desc: generated by xls2data.py
-- source: ships.xls
-- sheet: ships
-- ------------------------------


local ship_begin_info = {
	[1] = {
		['ship_id'] = 0,
		['name'] = '',
		['prop_id'] = 0,
		['tag'] = '玩家',
		['ai_id'] = {1},
		['level'] = 0,
		['walk_Id'] = 1,
		['is_enter'] = 0,
		['is_player'] = 1,
		['is_leader'] = 1,
		['isFormation'] = 0,
		['formationId'] = 0,
		['formationPos'] = 0,
		['fleet_dir'] = 7,
		['sailor_id'] = 0,
		['team_id'] = 1,
		['rota'] = 3,
		['x'] = 768,
		['y'] = 640,
		['max_sh'] = 0,
		['gun_count1'] = 0,
		['gun_count2'] = 0,
		['gun_value1'] = 0,
		['gun_value2'] = 0,
		['gun_value3'] = 0,
		['gun_range1'] = 0,
		['gun_range2'] = 0,
		['gun_range3'] = 0,
		['target_hit1'] = 100,
		['target_hit2'] = 100,
		['target_hit3'] = 100,
		['boat_damage'] = 0,
		['goods_plunder'] = 0,
		['turn_speed'] = 0,
		['speed_control'] = 0,
		['miss_attack'] = 0,
		['max_hp'] = 0,
		['fireClose'] = 0,
		['ship_defense'] = 0,
		['speed'] = 0,
		['radar_show'] = 0,
	},
}

return ship_begin_info