-- ------------------------------
-- desc: generated by xls2data.py
-- source: config.xls
-- sheet: 科技描述
-- ------------------------------


tech_description = {
	['fightFar'] = {
		['name'] = '远程火力',
	},
	['fightMid'] = {
		['name'] = '中程火力',
	},
	['fightClose'] = {
		['name'] = '近程火力',
	},
	['fightSpeed'] = {
		['name'] = '射速',
	}, 
	['durable'] = {
		['name'] = '耐久',
	},
	['consume_capacity'] = {
		['name'] = '占用载重',
	},
	['addCapacity'] = {
		['name'] = '增加载重',
	},
	['speed'] = {
		['name'] = '基本速度',
	},
	['rateHonour'] = {
		['name'] = '增加荣誉',
	},
	['rateRobAdd'] = {
		['name'] = '增加掠夺',
	},
	['rateRobCut'] = {
		['name'] = '减少被掠夺',
	},
	['rateFightSpeed'] = {
		['name'] = '增加战斗内速度',
	},
	['rateTradeSpeed'] = {
		['name'] = '经商速度',
	},
	['rateExploreSpeed'] = {
		['name'] = '探索速度',
	},
	['rateExploreEvent'] = {
		['name'] = '降低探索突发事件几率',
	},
	['rateCargoAdd'] = {
		['name'] = '增加货物产量',
	},
	['ratePrice'] = {
		['name'] = '提升销售价钱',
	},
	['rateProfit'] = {
		['name'] = '提升分红比例',
	},
}
