-- ------------------------------
-- desc: generated by xls2data.py
-- source: 音乐音效配置总表.xls
-- sheet: 语音对白
-- ------------------------------


local voice_info = {
	['VOICE_PLOT_1000'] = {
		['res'] = 'voice/market_welcome',
		['time'] = 0,
	},
	['VOICE_PLOT_1001'] = {
		['res'] = 'voice/market_full_male',
		['time'] = 3,
	},
	['VOICE_PLOT_1002'] = {
		['res'] = 'voice/market_empty_male',
		['time'] = 2,
	},
	['VOICE_PLOT_1003'] = {
		['res'] = 'voice/market_full_female',
		['time'] = 2,
	},
	['VOICE_PLOT_1004'] = {
		['res'] = 'voice/market_empty_female',
		['time'] = 2,
	},
	['VOICE_PLOT_1005'] = {
		['res'] = 'voice/hotel_welcome',
		['time'] = 0,
	},
	['VOICE_PLOT_1006'] = {
		['res'] = 'voice/hotel_cruit_male',
		['time'] = 0,
	},
	['VOICE_PLOT_1007'] = {
		['res'] = 'voice/hotel_train_male',
		['time'] = 0,
	},
	['VOICE_PLOT_1008'] = {
		['res'] = 'voice/hotel_cruit_female',
		['time'] = 0,
	},
	['VOICE_PLOT_1009'] = {
		['res'] = 'voice/hotel_train_female',
		['time'] = 0,
	},
	['VOICE_PLOT_1010'] = {
		['res'] = 'voice/port_battle_male',
		['time'] = 0,
	},
	['VOICE_PLOT_1011'] = {
		['res'] = 'voice/port_battle_male',
		['time'] = 0,
	},
	['VOICE_PLOT_1012'] = {
		['res'] = 'voice/port_arena_male',
		['time'] = 0,
	},
	['VOICE_PLOT_1013'] = {
		['res'] = 'voice/port_battle_female',
		['time'] = 0,
	},
	['VOICE_PLOT_1014'] = {
		['res'] = 'voice/port_battle_female',
		['time'] = 0,
	},
	['VOICE_PLOT_1015'] = {
		['res'] = 'voice/port_arena_female',
		['time'] = 0,
	},
	['VOICE_BOAT_1000'] = {
		['res'] = 'voice/appoint_select_male',
		['time'] = 0,
	},
	['VOICE_BOAT_1001'] = {
		['res'] = 'voice/appoint_confirm_male',
		['time'] = 0,
	},
	['VOICE_BOAT_1002'] = {
		['res'] = 'voice/appoint_select_female',
		['time'] = 0,
	},
	['VOICE_BOAT_1003'] = {
		['res'] = 'voice/appoint_confirm_female',
		['time'] = 0,
	},
	['VOICE_BATTLE_1000'] = {
		['res'] = 'voice/battle_1',
		['time'] = 0,
	},
	['VOICE_BATTLE_1001'] = {
		['res'] = 'voice/battle_2',
		['time'] = 0,
	},
	['VOICE_BATTLE_1002'] = {
		['res'] = 'voice/battle_3',
		['time'] = 0,
	},
	['VOICE_BATTLE_1003'] = {
		['res'] = 'voice/battle_4',
		['time'] = 0,
	},
	['VOICE_BATTLE_1004'] = {
		['res'] = 'voice/battle_5',
		['time'] = 0,
	},
	['VOICE_BATTLE_1005'] = {
		['res'] = 'voice/battle_6',
		['time'] = 0,
	},
	['VOICE_BATTLE_1006'] = {
		['res'] = 'voice/battle_7',
		['time'] = 0,
	},
	['VOICE_BATTLE_1007'] = {
		['res'] = 'voice/battle_8',
		['time'] = 0,
	},
	['VOICE_BATTLE_1008'] = {
		['res'] = 'voice/battle_9',
		['time'] = 0,
	},
	['VOICE_BATTLE_1009'] = {
		['res'] = 'voice/battle_10',
		['time'] = 0,
	},
	['VOICE_BATTLE_1010'] = {
		['res'] = 'voice/battle_11',
		['time'] = 0,
	},
	['VOICE_BATTLE_1011'] = {
		['res'] = 'voice/battle_12',
		['time'] = 0,
	},
	['VOICE_BATTLE_1012'] = {
		['res'] = 'voice/battle_13',
		['time'] = 0,
	},
	['VOICE_BATTLE_1013'] = {
		['res'] = 'voice/battle_14',
		['time'] = 0,
	},
	['VOICE_BATTLE_1014'] = {
		['res'] = 'voice/battle_15',
		['time'] = 0,
	},
	['VOICE_BATTLE_1015'] = {
		['res'] = 'voice/battle_16',
		['time'] = 0,
	},
	['VOICE_BATTLE_1016'] = {
		['res'] = 'voice/battle_17',
		['time'] = 0,
	},
	['VOICE_BATTLE_1017'] = {
		['res'] = 'voice/battle_18',
		['time'] = 0,
	},
	['VOICE_BATTLE_1018'] = {
		['res'] = 'voice/battle_19',
		['time'] = 0,
	},
	['VOICE_BATTLE_1019'] = {
		['res'] = 'voice/battle_20',
		['time'] = 0,
	},
	['VOICE_BATTLE_1020'] = {
		['res'] = 'voice/battle_21',
		['time'] = 0,
	},
	['VOICE_BATTLE_1021'] = {
		['res'] = 'voice/battle_22',
		['time'] = 0,
	},
	['VOICE_BATTLE_1022'] = {
		['res'] = 'voice/battle_23',
		['time'] = 0,
	},
	['VOICE_BATTLE_1023'] = {
		['res'] = 'voice/battle_24',
		['time'] = 0,
	},
	['VOICE_BATTLE_1024'] = {
		['res'] = 'voice/battle_25',
		['time'] = 0,
	},
	['VOICE_BATTLE_1025'] = {
		['res'] = 'voice/battle_26',
		['time'] = 0,
	},
	['VOICE_BATTLE_1026'] = {
		['res'] = 'voice/battle_27',
		['time'] = 0,
	},
	['VOICE_BATTLE_1027'] = {
		['res'] = 'voice/battle_28',
		['time'] = 0,
	},
	['VOICE_BATTLE_1028'] = {
		['res'] = 'voice/battle_29',
		['time'] = 0,
	},
	['VOICE_BATTLE_1029'] = {
		['res'] = 'voice/battle_30',
		['time'] = 0,
	},
	['VOICE_BATTLE_1030'] = {
		['res'] = 'voice/battle_31',
		['time'] = 0,
	},
	['VOICE_BATTLE_1031'] = {
		['res'] = 'voice/battle_32',
		['time'] = 0,
	},
	['VOICE_BATTLE_1032'] = {
		['res'] = 'voice/battle_33',
		['time'] = 0,
	},
	['VOICE_BATTLE_1033'] = {
		['res'] = 'voice/battle_34',
		['time'] = 0,
	},
	['VOICE_BATTLE_1034'] = {
		['res'] = 'voice/battle_35',
		['time'] = 0,
	},
	['VOICE_BATTLE_1035'] = {
		['res'] = 'voice/battle_36',
		['time'] = 0,
	},
	['VOICE_BATTLE_1036'] = {
		['res'] = 'voice/battle_37',
		['time'] = 0,
	},
	['VOICE_BATTLE_1037'] = {
		['res'] = 'voice/battle_38',
		['time'] = 0,
	},
	['VOICE_BATTLE_1038'] = {
		['res'] = 'voice/battle_39',
		['time'] = 0,
	},
	['VOICE_BATTLE_1039'] = {
		['res'] = 'voice/battle_40',
		['time'] = 0,
	},
	['VOICE_BATTLE_1040'] = {
		['res'] = 'voice/battle_41',
		['time'] = 0,
	},
	['VOICE_BATTLE_1041'] = {
		['res'] = 'voice/battle_42',
		['time'] = 0,
	},
	['VOICE_BATTLE_1042'] = {
		['res'] = 'voice/battle_43',
		['time'] = 0,
	},
	['VOICE_BATTLE_1043'] = {
		['res'] = 'voice/battle_44',
		['time'] = 0,
	},
	['VOICE_BATTLE_1044'] = {
		['res'] = 'voice/battle_45',
		['time'] = 0,
	},
	['VOICE_BATTLE_1045'] = {
		['res'] = 'voice/battle_46',
		['time'] = 0,
	},
	['VOICE_BATTLE_1046'] = {
		['res'] = 'voice/battle_47',
		['time'] = 0,
	},
	['VOICE_BATTLE_1047'] = {
		['res'] = 'voice/battle_48',
		['time'] = 0,
	},
	['VOICE_BATTLE_1048'] = {
		['res'] = 'voice/battle_49',
		['time'] = 0,
	},
	['VOICE_BATTLE_1049'] = {
		['res'] = 'voice/battle_50',
		['time'] = 0,
	},
	['VOICE_BATTLE_1050'] = {
		['res'] = 'voice/battle_51',
		['time'] = 0,
	},
	['VOICE_BATTLE_1051'] = {
		['res'] = 'voice/battle_52',
		['time'] = 0,
	},
	['VOICE_BATTLE_1052'] = {
		['res'] = 'voice/battle_53',
		['time'] = 0,
	},
	['VOICE_BATTLE_1053'] = {
		['res'] = 'voice/battle_54',
		['time'] = 0,
	},
	['VOICE_STORY_1000'] = {
		['res'] = 'voice/mission_1',
		['time'] = 0,
	},
	['VOICE_STORY_1001'] = {
		['res'] = 'voice/mission_2',
		['time'] = 0,
	},
	['VOICE_STORY_1002'] = {
		['res'] = 'voice/mission_3',
		['time'] = 0,
	},
	['VOICE_STORY_1003'] = {
		['res'] = 'voice/mission_4',
		['time'] = 0,
	},
	['VOICE_STORY_1004'] = {
		['res'] = 'voice/mission_5',
		['time'] = 0,
	},
	['VOICE_STORY_1005'] = {
		['res'] = 'voice/mission_6',
		['time'] = 0,
	},
	['VOICE_STORY_1006'] = {
		['res'] = 'voice/mission_7',
		['time'] = 0,
	},
	['VOICE_STORY_1007'] = {
		['res'] = 'voice/mission_8',
		['time'] = 0,
	},
	['VOICE_STORY_1008'] = {
		['res'] = 'voice/mission_9',
		['time'] = 0,
	},
	['VOICE_STORY_1009'] = {
		['res'] = 'voice/mission_10',
		['time'] = 0,
	},
	['VOICE_STORY_1010'] = {
		['res'] = 'voice/mission_11',
		['time'] = 0,
	},
	['VOICE_STORY_1011'] = {
		['res'] = 'voice/mission_12',
		['time'] = 0,
	},
	['VOICE_STORY_1012'] = {
		['res'] = 'voice/mission_13',
		['time'] = 0,
	},
	['VOICE_STORY_1013'] = {
		['res'] = 'voice/mission_14',
		['time'] = 0,
	},
	['VOICE_STORY_1014'] = {
		['res'] = 'voice/mission_15',
		['time'] = 0,
	},
	['VOICE_STORY_1015'] = {
		['res'] = 'voice/mission_16',
		['time'] = 0,
	},
	['VOICE_STORY_1016'] = {
		['res'] = 'voice/mission_17',
		['time'] = 0,
	},
	['VOICE_STORY_1017'] = {
		['res'] = 'voice/mission_18',
		['time'] = 0,
	},
	['VOICE_STORY_1018'] = {
		['res'] = 'voice/mission_19',
		['time'] = 0,
	},
	['VOICE_STORY_1019'] = {
		['res'] = 'voice/mission_20',
		['time'] = 0,
	},
	['VOICE_STORY_1020'] = {
		['res'] = 'voice/mission_21',
		['time'] = 0,
	},
	['VOICE_STORY_1021'] = {
		['res'] = 'voice/mission_22',
		['time'] = 0,
	},
	['VOICE_STORY_1022'] = {
		['res'] = 'voice/mission_23',
		['time'] = 0,
	},
	['VOICE_STORY_1023'] = {
		['res'] = 'voice/mission_24',
		['time'] = 0,
	},
	['VOICE_STORY_1024'] = {
		['res'] = 'voice/mission_25',
		['time'] = 0,
	},
	['VOICE_STORY_1025'] = {
		['res'] = 'voice/mission_26',
		['time'] = 0,
	},
	['VOICE_STORY_1026'] = {
		['res'] = 'voice/mission_27',
		['time'] = 0,
	},
	['VOICE_STORY_1027'] = {
		['res'] = 'voice/mission_28',
		['time'] = 0,
	},
	['VOICE_STORY_1028'] = {
		['res'] = 'voice/mission_29',
		['time'] = 0,
	},
	['VOICE_STORY_1029'] = {
		['res'] = 'voice/mission_30',
		['time'] = 0,
	},
	['VOICE_STORY_1030'] = {
		['res'] = 'voice/mission_31',
		['time'] = 0,
	},
	['VOICE_STORY_1031'] = {
		['res'] = 'voice/mission_32',
		['time'] = 0,
	},
	['VOICE_STORY_1032'] = {
		['res'] = 'voice/mission_33',
		['time'] = 0,
	},
	['VOICE_STORY_1033'] = {
		['res'] = 'voice/mission_34',
		['time'] = 0,
	},
	['VOICE_STORY_1034'] = {
		['res'] = 'voice/mission_35',
		['time'] = 0,
	},
	['VOICE_STORY_1035'] = {
		['res'] = 'voice/mission_36',
		['time'] = 0,
	},
	['VOICE_STORY_1036'] = {
		['res'] = 'voice/mission_37',
		['time'] = 0,
	},
	['VOICE_STORY_1037'] = {
		['res'] = 'voice/mission_38',
		['time'] = 0,
	},
	['VOICE_STORY_1038'] = {
		['res'] = 'voice/mission_39',
		['time'] = 0,
	},
	['VOICE_STORY_1039'] = {
		['res'] = 'voice/mission_40',
		['time'] = 0,
	},
	['VOICE_STORY_1040'] = {
		['res'] = 'voice/mission_41',
		['time'] = 0,
	},
	['VOICE_STORY_1041'] = {
		['res'] = 'voice/mission_42',
		['time'] = 0,
	},
	['VOICE_STORY_1042'] = {
		['res'] = 'voice/mission_43',
		['time'] = 0,
	},
	['VOICE_STORY_1043'] = {
		['res'] = 'voice/mission_44',
		['time'] = 0,
	},
	['VOICE_PLOT_1016'] = {
		['res'] = 'voice/port_relogin_m',
		['time'] = 0,
	},
	['VOICE_PLOT_1017'] = {
		['res'] = 'voice/port_relogin_w',
		['time'] = 0,
	},
	['VOICE_PLOT_1018'] = {
		['res'] = 'voice/port_marketquotations_m',
		['time'] = 0,
	},
	['VOICE_PLOT_1019'] = {
		['res'] = 'voice/port_marketquotations_w',
		['time'] = 0,
	},
	['VOICE_PLOT_1020'] = {
		['res'] = 'voice/port_appoint_m',
		['time'] = 0,
	},
	['VOICE_PLOT_1021'] = {
		['res'] = 'voice/port_appoint_w',
		['time'] = 0,
	},
	['VOICE_PLOT_1022'] = {
		['res'] = 'voice/port_reward',
		['time'] = 0,
	},
	['VOICE_PLOT_1023'] = {
		['res'] = 'voice/port_equipment',
		['time'] = 0,
	},
	['VOICE_PLOT_1024'] = {
		['res'] = 'voice/port_fleet',
		['time'] = 0,
	},
	['VOICE_STORY_1044'] = {
		['res'] = 'voice/mission_45',
		['time'] = 0,
	},
	['VOICE_STORY_1045'] = {
		['res'] = 'voice/mission_46',
		['time'] = 0,
	},
	['VOICE_BATTLE_1054'] = {
		['res'] = 'voice/demo_battle_1',
		['time'] = 0,
	},
	['VOICE_BATTLE_1055'] = {
		['res'] = 'voice/demo_battle_2',
		['time'] = 0,
	},
	['VOICE_BATTLE_1056'] = {
		['res'] = 'voice/demo_battle_3',
		['time'] = 0,
	},
	['VOICE_BATTLE_1057'] = {
		['res'] = 'voice/demo_battle_4',
		['time'] = 0,
	},
	['VOICE_BATTLE_1058'] = {
		['res'] = 'voice/demo_battle_5',
		['time'] = 0,
	},
	['VOICE_BATTLE_1059'] = {
		['res'] = 'voice/demo_battle_6',
		['time'] = 0,
	},
	['VOICE_BATTLE_1060'] = {
		['res'] = 'voice/demo_battle_7',
		['time'] = 0,
	},
	['VOICE_BATTLE_1061'] = {
		['res'] = 'voice/demo_battle_8',
		['time'] = 0,
	},
	['VOICE_BATTLE_1062'] = {
		['res'] = 'voice/demo_battle_9',
		['time'] = 0,
	},
	['VOICE_BATTLE_1063'] = {
		['res'] = 'voice/demo_battle_10',
		['time'] = 0,
	},
	['VOICE_BATTLE_1064'] = {
		['res'] = 'voice/demo_battle_11',
		['time'] = 0,
	},
	['VOICE_BATTLE_1065'] = {
		['res'] = 'voice/demo_battle_12',
		['time'] = 0,
	},
	['VOICE_BATTLE_1066'] = {
		['res'] = 'voice/demo_battle_13',
		['time'] = 0,
	},
	['VOICE_BATTLE_1067'] = {
		['res'] = 'voice/demo_battle_14',
		['time'] = 0,
	},
	['VOICE_BATTLE_1068'] = {
		['res'] = 'voice/novice_battle_1',
		['time'] = 0,
	},
	['VOICE_BATTLE_1069'] = {
		['res'] = 'voice/novice_battle_2',
		['time'] = 0,
	},
	['VOICE_BATTLE_1070'] = {
		['res'] = 'voice/novice_battle_3',
		['time'] = 0,
	},
	['VOICE_BATTLE_1071'] = {
		['res'] = 'voice/novice_battle_4',
		['time'] = 0,
	},
	['VOICE_BATTLE_1072'] = {
		['res'] = 'voice/novice_battle_5',
		['time'] = 0,
	},
	['VOICE_BATTLE_1073'] = {
		['res'] = 'voice/novice_battle_6',
		['time'] = 0,
	},
	['VOICE_BATTLE_1074'] = {
		['res'] = 'voice/novice_battle_7',
		['time'] = 0,
	},
	['VOICE_BATTLE_1075'] = {
		['res'] = 'voice/novice_battle_8',
		['time'] = 0,
	},
	['VOICE_BATTLE_1076'] = {
		['res'] = 'voice/novice_battle_9',
		['time'] = 0,
	},
	['VOICE_BATTLE_1077'] = {
		['res'] = 'voice/novice_battle_10',
		['time'] = 0,
	},
	['VOICE_BATTLE_1078'] = {
		['res'] = 'voice/novice_battle_11',
		['time'] = 0,
	},
	['VOICE_BATTLE_1079'] = {
		['res'] = 'voice/novice_battle_12',
		['time'] = 0,
	},
	['VOICE_BATTLE_1080'] = {
		['res'] = 'voice/novice_battle_13',
		['time'] = 0,
	},
	['VOICE_BATTLE_1081'] = {
		['res'] = 'voice/novice_battle_14',
		['time'] = 0,
	},
	['VOICE_BATTLE_1082'] = {
		['res'] = 'voice/novice_battle_15',
		['time'] = 0,
	},
	['VOICE_PLOT_1025'] = {
		['res'] = 'voice/town_enter',
		['time'] = 0,
	},
	['VOICE_PLOT_1026'] = {
		['res'] = 'voice/shipyard_enter',
		['time'] = 0,
	},
	['VOICE_PLOT_1027'] = {
		['res'] = 'voice/shipyard_remake',
		['time'] = 0,
	},
	['VOICE_PLOT_1028'] = {
		['res'] = 'voice/port_sail',
		['time'] = 0,
	},
	['VOICE_PLOT_1029'] = {
		['res'] = 'voice/camp_enter',
		['time'] = 0,
	},
	['VOICE_PLOT_1030'] = {
		['res'] = 'voice/hotel_activity',
		['time'] = 0,
	},
	['VOICE_PLOT_1031'] = {
		['res'] = 'voice/hotel_reward',
		['time'] = 0,
	},
	['VOICE_BOAT_1004'] = {
		['res'] = 'voice/boat_enter',
		['time'] = 0,
	},
	['VOICE_BOAT_1005'] = {
		['res'] = 'voice/boat_backpack',
		['time'] = 0,
	},
	['VOICE_EXPLORE_1000'] = {
		['res'] = 'voice/ex_stop_m',
		['time'] = 0,
	},
	['VOICE_EXPLORE_1001'] = {
		['res'] = 'voice/ex_manual_m',
		['time'] = 0,
	},
	['VOICE_EXPLORE_1002'] = {
		['res'] = 'voice/ex_sailing1_m',
		['time'] = 0,
	},
	['VOICE_EXPLORE_1003'] = {
		['res'] = 'voice/ex_sailing2_m',
		['time'] = 0,
	},
	['VOICE_EXPLORE_1004'] = {
		['res'] = 'voice/ex_no_food_m',
		['time'] = 0,
	},
	['VOICE_EXPLORE_1005'] = {
		['res'] = 'voice/battle_18',
		['time'] = 0,
	},
	['VOICE_EXPLORE_1006'] = {
		['res'] = 'voice/ex_no_ops_m',
		['time'] = 0,
	},
	['VOICE_EXPLORE_1007'] = {
		['res'] = 'voice/ex_storm1_m',
		['time'] = 0,
	},
	['VOICE_EXPLORE_1008'] = {
		['res'] = 'voice/ex_storm2_m',
		['time'] = 0,
	},
	['VOICE_EXPLORE_1009'] = {
		['res'] = 'voice/ex_storm3_m',
		['time'] = 0,
	},
	['VOICE_EXPLORE_1010'] = {
		['res'] = 'voice/ex_fog1_m',
		['time'] = 0,
	},
	['VOICE_EXPLORE_1011'] = {
		['res'] = 'voice/ex_fog2_m',
		['time'] = 0,
	},
	['VOICE_EXPLORE_1012'] = {
		['res'] = 'voice/ex_fog3_m',
		['time'] = 0,
	},
	['VOICE_EXPLORE_1013'] = {
		['res'] = 'voice/battle_25',
		['time'] = 0,
	},
	['VOICE_EXPLORE_1014'] = {
		['res'] = 'voice/ex_headwind_m',
		['time'] = 0,
	},
	['VOICE_EXPLORE_1015'] = {
		['res'] = 'voice/ex_box1_m',
		['time'] = 0,
	},
	['VOICE_EXPLORE_1016'] = {
		['res'] = 'voice/ex_rock1_m',
		['time'] = 0,
	},
	['VOICE_EXPLORE_1017'] = {
		['res'] = 'voice/ex_box2_m',
		['time'] = 0,
	},
	['VOICE_EXPLORE_1018'] = {
		['res'] = 'voice/ex_rock2_m',
		['time'] = 0,
	},
	['VOICE_EXPLORE_1019'] = {
		['res'] = 'voice/battle_11',
		['time'] = 0,
	},
	['VOICE_EXPLORE_1020'] = {
		['res'] = 'voice/ex_stop_f',
		['time'] = 0,
	},
	['VOICE_EXPLORE_1021'] = {
		['res'] = 'voice/ex_manual_f',
		['time'] = 0,
	},
	['VOICE_EXPLORE_1022'] = {
		['res'] = 'voice/ex_sailing1_f',
		['time'] = 0,
	},
	['VOICE_EXPLORE_1023'] = {
		['res'] = 'voice/ex_sailing2_f',
		['time'] = 0,
	},
	['VOICE_EXPLORE_1024'] = {
		['res'] = 'voice/ex_no_food_f',
		['time'] = 0,
	},
	['VOICE_EXPLORE_1025'] = {
		['res'] = 'voice/battle_33',
		['time'] = 0,
	},
	['VOICE_EXPLORE_1026'] = {
		['res'] = 'voice/ex_no_ops_f',
		['time'] = 0,
	},
	['VOICE_EXPLORE_1027'] = {
		['res'] = 'voice/ex_storm1_f',
		['time'] = 0,
	},
	['VOICE_EXPLORE_1028'] = {
		['res'] = 'voice/ex_storm2_f',
		['time'] = 0,
	},
	['VOICE_EXPLORE_1029'] = {
		['res'] = 'voice/ex_storm3_f',
		['time'] = 0,
	},
	['VOICE_EXPLORE_1030'] = {
		['res'] = 'voice/ex_fog1_f',
		['time'] = 0,
	},
	['VOICE_EXPLORE_1031'] = {
		['res'] = 'voice/ex_fog2_f',
		['time'] = 0,
	},
	['VOICE_EXPLORE_1032'] = {
		['res'] = 'voice/ex_fog3_f',
		['time'] = 0,
	},
	['VOICE_EXPLORE_1033'] = {
		['res'] = 'voice/battle_42',
		['time'] = 0,
	},
	['VOICE_EXPLORE_1034'] = {
		['res'] = 'voice/ex_headwind_f',
		['time'] = 0,
	},
	['VOICE_EXPLORE_1035'] = {
		['res'] = 'voice/ex_box1_f',
		['time'] = 0,
	},
	['VOICE_EXPLORE_1036'] = {
		['res'] = 'voice/ex_rock1_f',
		['time'] = 0,
	},
	['VOICE_EXPLORE_1037'] = {
		['res'] = 'voice/ex_box2_f',
		['time'] = 0,
	},
	['VOICE_EXPLORE_1038'] = {
		['res'] = 'voice/ex_rock2_f',
		['time'] = 0,
	},
	['VOICE_EXPLORE_1039'] = {
		['res'] = 'voice/battle_26',
		['time'] = 0,
	},
}

return voice_info