-- ------------------------------
-- desc: generated by xls2data.py
-- source: ai.xls
-- sheet: ai
-- ------------------------------


local ai_17_info = {
	[1] = {
		['event'] = 'battle_start',
		['event_param'] = nil,
		['target_id'] = '',
		['target_x'] = 0,
		['target_y'] = 0,
		['target_range'] = 0,
		['next_ai'] = 0,
		['ai_event'] = 'playPlot',
		['ai_param'] = {1,2,3,4,5,6},
		['des'] = '',
	},
	[2] = {
		['event'] = 'goto',
		['event_param'] = nil,
		['target_id'] = '',
		['target_x'] = 1600,
		['target_y'] = 1300,
		['target_range'] = 30,
		['next_ai'] = 0,
		['ai_event'] = 'playPlot',
		['ai_param'] = {7},
		['des'] = '',
	},
	[3] = {
		['event'] = 'goto',
		['event_param'] = nil,
		['target_id'] = '',
		['target_x'] = 1400,
		['target_y'] = 1200,
		['target_range'] = 30,
		['next_ai'] = 0,
		['ai_event'] = '',
		['ai_param'] = nil,
		['des'] = '',
	},
	[4] = {
		['event'] = 'set_ai',
		['event_param'] = nil,
		['target_id'] = '',
		['target_x'] = 0,
		['target_y'] = 0,
		['target_range'] = 0,
		['next_ai'] = 0,
		['ai_event'] = 'battle_end',
		['ai_param'] = {1},
		['des'] = '',
	},
	[5] = {
		['event'] = 'hp_ratio_less',
		['event_param'] = {95},
		['target_id'] = '',
		['target_x'] = 0,
		['target_y'] = 0,
		['target_range'] = 0,
		['next_ai'] = 0,
		['ai_event'] = 'say',
		['ai_param'] = {name = "哈里森", txt = "想捡我的现成！追上去狠狠的打！"},
		['des'] = '',
	},
	[6] = {
		['event'] = 'sh_ratio_less',
		['event_param'] = {20},
		['target_id'] = '',
		['target_x'] = 0,
		['target_y'] = 0,
		['target_range'] = 0,
		['next_ai'] = 0,
		['ai_event'] = 'say',
		['ai_param'] = {name = "埃米利奥.菲隆", txt = "危险！赶紧与敌人保持安全距离！"},
		['des'] = '',
	},
}

return ai_17_info