-- ------------------------------
-- desc: generated by xls2data.py
-- source: plot.xls
-- sheet: Sheet1
-- ------------------------------


local plot_45_info = {
	[1] = {
		['plot'] = 'camera',
		['param'] = {{500,800,0},{1200,1000,2},},
	},
	[2] = {
		['plot'] = 'dialog',
		['param'] = {0,"",2,"敌人的喽啰并不可怕，我们应该可以消灭他们。"},
	},
	[3] = {
		['plot'] = 'camera',
		['param'] = {{1200,1000,0},{2200,800,1},},
	},
	[4] = {
		['plot'] = 'dialog',
		['param'] = {0,"",2,"可怕的是海雷丁！他会在他手下血量剩下一半的时候，从这边出现并赶来救援他的部下，必须在他赶到之前结束战斗。"},
	},
	[5] = {
		['plot'] = 'mask_fadeIn',
		['param'] = {0.8},
	},
	[6] = {
		['plot'] = 'camera',
		['param'] = {{500,800,0}},
	},
	[7] = {
		['plot'] = 'mask_fadeOut',
		['param'] = {0.8},
	},
	[8] = {
		['plot'] = 'dialog',
		['param'] = {0,"",2,"警报！海雷丁正在向这边赶来，必须尽快结束战斗！"},
	},
}

return plot_45_info