-- ------------------------------
-- desc: generated by xls2data.py
-- source: plot.xls
-- sheet: Sheet1
-- ------------------------------


local plot_71_jy_info = {
	[1] = {
		['plot'] = 'camera',
		['param'] = {{400,640,0},{2500,640,2},},
	},
	[2] = {
		['plot'] = 'dialog',
		['param'] = {34,"英国军官",2,"把那些奴隶给我抓回来，击沉不服从我们的非洲船！",ship_id=7},
	},
	[3] = {
		['plot'] = 'camera',
		['param'] = {{2082,640,1},{1380,1043,1},},
	},
	[4] = {
		['plot'] = 'text_display',
		['param'] = {{"保护那些手寸铁的非洲人，即使他们已屈服于英国人……"}},
	},
	[5] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,"靠近那些非洲船只，表明我们的来意，别让英国人得逞。"},
	},
	[6] = {
		['plot'] = 'text_display',
		['param'] = {{"一艘逃亡的非洲船被击沉，任务失败"}},
	},
	[7] = {
		['plot'] = 'text_display',
		['param'] = {{"英国人在沿海岸疯狂地绑架非洲人……"}},
	},
}

return plot_71_jy_info