-- ------------------------------
-- desc: generated by xls2data.py
-- source: plot.xls
-- sheet: Sheet1
-- ------------------------------


local plot_122_info = {
	[1] = {
		['plot'] = 'camera',
		['param'] = {{1400,650,1}},
	},
	[2] = {
		['plot'] = 'cameraScale',
		['param'] = {{1400,650},0.5,1},
	},
	[3] = {
		['plot'] = 'cameraScale',
		['param'] = {{800,650},1,1},
	},
	[4] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,"有受伤的明朝水军船只，赶快掩护他们撤退。"},
	},
	[5] = {
		['plot'] = 'dialog',
		['param'] = {38,"海盗突击队",2,"消灭他们，一个不留！"},
	},
	[6] = {
		['plot'] = 'dialog',
		['param'] = {86,"大明水军",2,"我们收到撤退回来船只的信息，赶过来支援你们！"},
	},
	[7] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,"太好了，大家齐心合力一起赶走他们。"},
	},
	[8] = {
		['plot'] = 'dialog',
		['param'] = {38,"海盗先遣队",2,"后续部队终于跟上了，让他们见识见识我们火炮的厉害！"},
	},
}

return plot_122_info