-- ------------------------------
-- desc: generated by xls2data.py
-- source: plot.xls
-- sheet: Sheet1
-- ------------------------------


local plot_21_jy_info = {
	[1] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,"港湾内的海盗一定还不知道外围防线已经被我们剿灭了！正在肆无忌惮的饮酒作乐呢！",ship_id=1},
	},
	[2] = {
		['plot'] = 'camera',
		['param'] = {{500,800,0},{1200,900,1},},
	},
	[3] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,"趁他们毫无戒备，快速逐个击破！",ship_id=1},
	},
}

return plot_21_jy_info