-- ------------------------------
-- desc: generated by xls2data.py
-- source: plot.xls
-- sheet: Sheet1
-- ------------------------------


local plot_23_jy_info = {
	[1] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,"终于攻入摩尔海盗的老巢！",3,fail,"VOICE_BATTLE_1072","VOICE_BATTLE_1076",ship_id=1},
	},
	[2] = {
		['plot'] = 'camera',
		['param'] = {{600,600,0},{1800,600,1},},
	},
	[3] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,"这些犬牙交错的岛礁不仅可以掩护伏击，也可以分散船阵！",6,fail,"VOICE_BATTLE_1073","VOICE_BATTLE_1077",ship_id=1},
	},
	[4] = {
		['plot'] = 'camera',
		['param'] = {{1800,600,0},{600,600,1},},
	},
	[5] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,"敌人舰队装备精良，让我们利用岛礁障碍，分散海盗阵形逐个击破，再集中火力攻击【海盗首领】",7,fail,"VOICE_BATTLE_1074","VOICE_BATTLE_1078",ship_id=1},
	},
}

return plot_23_jy_info