-- ------------------------------
-- desc: generated by xls2data.py
-- source: ai.xls
-- sheet: ai
-- ------------------------------


local ai_36_info = {
	[1] = {
		['event'] = 'battle_start',
		['event_param'] = nil,
		['target_id'] = '',
		['target_x'] = 0,
		['target_y'] = 0,
		['target_range'] = 0,
		['next_ai'] = 0,
		['ai_event'] = 'playPlot',
		['ai_param'] = {1,2,8,3,9,4,5,10,6},
		['des'] = '',
	},
	[2] = {
		['event'] = 'kill',
		['event_param'] = nil,
		['target_id'] = '敌二',
		['target_x'] = 0,
		['target_y'] = 0,
		['target_range'] = 0,
		['next_ai'] = 5,
		['ai_event'] = '',
		['ai_param'] = nil,
		['des'] = '',
	},
	[3] = {
		['event'] = 'kill',
		['event_param'] = nil,
		['target_id'] = '敌三',
		['target_x'] = 0,
		['target_y'] = 0,
		['target_range'] = 0,
		['next_ai'] = 5,
		['ai_event'] = '',
		['ai_param'] = nil,
		['des'] = '',
	},
	[4] = {
		['event'] = 'kill',
		['event_param'] = nil,
		['target_id'] = '敌四',
		['target_x'] = 0,
		['target_y'] = 0,
		['target_range'] = 0,
		['next_ai'] = 5,
		['ai_event'] = '',
		['ai_param'] = nil,
		['des'] = '',
	},
	[5] = {
		['event'] = 'set_ai',
		['event_param'] = nil,
		['target_id'] = '',
		['target_x'] = 0,
		['target_y'] = 0,
		['target_range'] = 0,
		['next_ai'] = 0,
		['ai_event'] = 'playPlot',
		['ai_param'] = {7},
		['des'] = '',
	},
	[6] = {
		['event'] = 'catch',
		['event_param'] = nil,
		['target_id'] = '玩家',
		['target_x'] = 0,
		['target_y'] = 0,
		['target_range'] = 0,
		['next_ai'] = 0,
		['ai_event'] = 'bomb',
		['ai_param'] = {100},
		['des'] = '',
	},
}

return ai_36_info