-- ------------------------------
-- desc: generated by xls2data.py
-- source: plot.xls
-- sheet: Sheet1
-- ------------------------------


local plot_41_info = {
	[1] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,"维京海盗封锁了海峡，企图垄断往北欧的贸易航线！",ship_id=1},
	},
	[2] = {
		['plot'] = 'camera',
		['param'] = {{660,600,0},{2164,600,2},},
	},
	[3] = {
		['plot'] = 'mask_fadeIn',
		['param'] = {0.8},
	},
	[4] = {
		['plot'] = 'camera',
		['param'] = {{660,600,0}},
	},
	[5] = {
		['plot'] = 'mask_fadeOut',
		['param'] = {0.8},
	},
	[6] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,"他们发现我们了，准备作战！",ship_id=1},
	},
	[7] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,"敌人的船速度很快，火炮很难造成有力的伤害，想办法让他们和我们接舷作战！",ship_id=1},
	},
	[8] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,"漩涡消失了！"},
	},
	[9] = {
		['plot'] = 'dialog',
		['param'] = {0,"瞭望手",1,"漩涡出现，操控师注意!!被卷进去别想活命！"},
	},
	[10] = {
		['plot'] = 'dialog',
		['param'] = {0,"瞭望手",1,"出现了更多的敌人。"},
	},
	[11] = {
		['plot'] = 'camera',
		['param'] = {{1452,558,1}},
	},
	[12] = {
		['plot'] = 'camera',
		['param'] = {{549,339,2},{549,848,2}},
	},
	[13] = {
		['plot'] = 'cameraScale',
		['param'] = {{2364,600},0.6,3},
	},
	[14] = {
		['plot'] = 'dialog',
		['param'] = {0,"瞭望手",1,"或许我们可以利用礁石作遮掩，将他们引至漩涡。"},
	},
	[15] = {
		['plot'] = 'camera',
		['param'] = {{560,848,1},{1090,546,1}},
	},
}

return plot_41_info