-- ------------------------------
-- desc: generated by xls2data.py
-- source: plot.xls
-- sheet: Sheet1
-- ------------------------------


local plot_1_info = {
	[1] = {
		['plot'] = 'mask_fadeIn',
		['param'] = {0.5},
	},
	[2] = {
		['plot'] = 'text_display',
		['param'] = {{"1415年，在亨利王子率领下，伊比利亚人民与摩尔侵略者的决战展开了……"},7,false,"VOICE_BATTLE_1000"},
	},
	[3] = {
		['plot'] = 'effect',
		['param'] = {"tx_6005", {200,540} },
	},
	[4] = {
		['plot'] = 'layer',
		['param'] = { 1 },
	},
	[5] = {
		['plot'] = 'sprite',
		['param'] = { {"landscop_battle/battle_bg.jpg"}, {0,0}, 1,1.1,1},
	},
	[6] = {
		['plot'] = 'add_armature',
		['param'] = {"10", {480,275}, 2, 0.2, 1},
	},
	[7] = {
		['plot'] = 'add_armature',
		['param'] = {"10", {630,275}, 2, 0.2, 1},
	},
	[8] = {
		['plot'] = 'add_armature',
		['param'] = {"10", {780,275}, 2, 0.2, 1},
	},
	[9] = {
		['plot'] = 'add_armature',
		['param'] = {"10", {930,275}, 2, 0.2, 1},
	},
	[10] = {
		['plot'] = 'add_armature',
		['param'] = {"10", {330,275}, 2, 0.2, 1},
	},
	[11] = {
		['plot'] = 'add_armature',
		['param'] = {"10", {180,275}, 2, 0.2, 1},
	},
	[12] = {
		['plot'] = 'add_armature',
		['param'] = {"10", {30,275}, 2, 0.2, 1},
	},
	[13] = {
		['plot'] = 'mask_fadeOut',
		['param'] = {0.5},
	},
	[14] = {
		['plot'] = 'delay',
		['param'] = {1},
	},
	[15] = {
		['plot'] = 'layerScale',
		['param'] = {1,1.3,2},
	},
	[16] = {
		['plot'] = 'dialog',
		['param'] = {61,"亨利王子",1,"敌人的船队阵型紧密，谁能想办法破解！",4,true,"VOICE_BATTLE_1001"},
	},
	[17] = {
		['plot'] = 'mask_fadeIn',
		['param'] = {0.5},
	},
	[18] = {
		['plot'] = 'camera',
		['param'] = {{1150,1000,0}},
	},
	[19] = {
		['plot'] = 'mask_fadeOut',
		['param'] = {0.5},
	},
	[20] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,"让我率队突击！只要能冲散敌人船队，就能逐一击破！",5,true,"VOICE_BATTLE_1002"},
	},
	[21] = {
		['plot'] = 'mask_fadeIn',
		['param'] = {0.5},
	},
	[22] = {
		['plot'] = 'camera',
		['param'] = {{1400,1100,0}},
	},
	[23] = {
		['plot'] = 'mask_fadeOut',
		['param'] = {0.5},
	},
	[24] = {
		['plot'] = 'cameraScale',
		['param'] = {{1400,1100},0.7, 3},
	},
	[25] = {
		['plot'] = 'cameraScale',
		['param'] = {{1400,1100},1,0},
	},
	[26] = {
		['plot'] = 'mask_fadeIn',
		['param'] = {0.8},
	},
	[27] = {
		['plot'] = 'camera',
		['param'] = {{4350,900,0}},
	},
	[28] = {
		['plot'] = 'mask_fadeOut',
		['param'] = {1.5},
	},
	[29] = {
		['plot'] = 'btn_click',
		['param'] = {{850,80},1,{"#skill_1018.png","#skill_1018.png"},"齐射","tx_1002", true,"VOICE_BATTLE_1004"},
	},
	[30] = {
		['plot'] = 'effect',
		['param'] = {"tx_6005", {200,540} },
	},
	[31] = {
		['plot'] = 'sprite',
		['param'] = { {"landscop_battle/battle_bg.jpg"}, {0,0}, 1,1.1},
	},
	[32] = {
		['plot'] = 'layer',
		['param'] = { 1 },
	},
	[33] = {
		['plot'] = 'add_armature',
		['param'] = {"6", {900,285}, 1, 0.18, 1},
	},
	[34] = {
		['plot'] = 'effect',
		['param'] = {"tx_4007", {-200,-25}, 1 },
	},
	[35] = {
		['plot'] = 'effect',
		['param'] = {"tx_4007", {0,-40}, 1 },
	},
	[36] = {
		['plot'] = 'effect',
		['param'] = {"tx_4007", {100,-45}, 1 },
	},
	[37] = {
		['plot'] = 'add_armature',
		['param'] = {"5", {440,280}, 2, 0.2, 1},
	},
	[38] = {
		['plot'] = 'effect',
		['param'] = {"tx_4007", {-80,-10}, 2 },
	},
	[39] = {
		['plot'] = 'effect',
		['param'] = {"tx_4007", {0,5}, 2 },
	},
	[40] = {
		['plot'] = 'effect',
		['param'] = {"tx_4007", {50,0}, 2 },
	},
	[41] = {
		['plot'] = 'add_armature',
		['param'] = {"16", {700,275}, 3, 0.5, 1},
	},
	[42] = {
		['plot'] = 'sprite',
		['param'] = { {"landscop_battle/mask2.png"}, {0,0}},
	},
	[43] = {
		['plot'] = 'delay',
		['param'] = {0.1},
	},
	[44] = {
		['plot'] = 'layer',
		['param'] = {2},
	},
	[45] = {
		['plot'] = 'add_armature',
		['param'] = {"14", {200,280}, 4, 0.8, 2},
	},
	[46] = {
		['plot'] = 'sprite',
		['param'] = { {"landscop_battle/mask1.png"}, {0,0}},
	},
	[47] = {
		['plot'] = 'dialog',
		['param'] = {58,"哲巴尔",2,"左舷开始入水，不行了，立即撤退！",4,true,"VOICE_BATTLE_1005"},
	},
	[48] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,"消灭他们！为了家园！为了自由！",4,true,"VOICE_BATTLE_1006"},
	},
	[49] = {
		['plot'] = 'delay',
		['param'] = {0.1},
	},
	[50] = {
		['plot'] = 'shoot_boat',
		['param'] = {{"tx_4020", {650,230}}, {"proj_6001", {700,250}, {205, 205}, 1, 1 }, {"tx_4005", {{155, 205},{205, 215},{255, 205}  }} },
	},
	[51] = {
		['plot'] = 'delay',
		['param'] = {0.5},
	},
	[52] = {
		['plot'] = 'shoot_boat',
		['param'] = {{"tx_4020", {650,230}}, {"proj_6001", {700,250}, {205, 205}, 1, 1 }, {"tx_4005", {{155, 205},{205, 215},{255, 205}  }} },
	},
	[53] = {
		['plot'] = 'delay',
		['param'] = {0.5},
	},
	[54] = {
		['plot'] = 'shoot_boat',
		['param'] = {{"tx_4020", {650,230}}, {"proj_6001", {700,250}, {205, 205}, 1, 1 }, {"tx_4005", {{155, 205},{205, 215},{255, 205}  }} },
	},
	[55] = {
		['plot'] = 'delay',
		['param'] = {0.5},
	},
	[56] = {
		['plot'] = 'effect',
		['param'] = {"tx_4007", {-100,-20}, 4 },
	},
	[57] = {
		['plot'] = 'effect',
		['param'] = {"tx_4007", {0,10}, 4 },
	},
	[58] = {
		['plot'] = 'effect',
		['param'] = {"tx_4007", {100,0}, 4 },
	},
	[59] = {
		['plot'] = 'shoot_boat',
		['param'] = {{"tx_4020", {650,230}}, {"proj_6001", {700,250}, {205, 205}, 1, 1 }, {"tx_4005", {{155, 205},{205, 215},{255, 205}  }} },
	},
	[60] = {
		['plot'] = 'delay',
		['param'] = {0.5},
	},
	[61] = {
		['plot'] = 'shoot_boat',
		['param'] = {{"tx_4020", {650,230}}, {"proj_6001", {700,250}, {205, 205}, 1, 1 }, {"tx_4005", {{155, 205},{205, 215},{255, 205}  }} },
	},
	[62] = {
		['plot'] = 'delay',
		['param'] = {0.5},
	},
	[63] = {
		['plot'] = 'shoot_boat',
		['param'] = {{"tx_4020", {650,230}}, {"proj_6001", {700,250}, {205, 205}, 1, 1 }, {"tx_4005", {{155, 205},{205, 215},{255, 205}  }} },
	},
	[64] = {
		['plot'] = 'delay',
		['param'] = {0.5},
	},
	[65] = {
		['plot'] = 'xiaoren',
		['param'] = {{180, 210},{80, 210},{120, 210},{150,220},{630,230},{700,240},{750,240} },
	},
	[66] = {
		['plot'] = 'sprite_fadeout',
		['param'] = {4,2,true },
	},
	[67] = {
		['plot'] = 'sprite_moveto',
		['param'] = {4,{200,220},2,true},
	},
	[68] = {
		['plot'] = 'delay',
		['param'] = {1},
	},
	[69] = {
		['plot'] = 'mask_fadeIn',
		['param'] = nil,
	},
	[70] = {
		['plot'] = 'text_display',
		['param'] = {{"战争胜利后，受王子嘉奖的我被推荐到里斯本报投航海学院，向无尽的海洋进军！"}, 6,false,"VOICE_BATTLE_1007"},
	},
	[71] = {
		['plot'] = 'camera',
		['param'] = {{4640,2000,0}},
	},
	[72] = {
		['plot'] = 'add_armature',
		['param'] = {"5", {560,277}, 2, 0.12, 1},
	},
	[73] = {
		['plot'] = 'add_armature',
		['param'] = {"5", {710,277}, 2, 0.12, 1},
	},
	[74] = {
		['plot'] = 'add_armature',
		['param'] = {"5", {860,277}, 2, 0.12, 1},
	},
	[75] = {
		['plot'] = 'add_armature',
		['param'] = {"5", {400,277}, 2, 0.12, 1},
	},
	[76] = {
		['plot'] = 'add_armature',
		['param'] = {"5", {250,277}, 2, 0.12, 1},
	},
	[77] = {
		['plot'] = 'add_armature',
		['param'] = {"5", {100,277}, 2, 0.12, 1},
	},
}

return plot_1_info