-- ------------------------------
-- desc: generated by xls2data.py
-- source: plot.xls
-- sheet: Sheet1
-- ------------------------------


local plot_4_info = {
	[1] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,"看到苏菲的船了，她受损很严重！对方正对她穷追不舍！"},
	},
	[2] = {
		['plot'] = 'camera',
		['param'] = {{2600,1000,0},{3100,1500,2},},
	},
	[3] = {
		['plot'] = 'camera',
		['param'] = {{3100,1500,0},{3500,1500,1},},
	},
	[4] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,"我们必须阻截敌人，让苏菲尽快摆脱对方，只要回到港口，她就安全了！"},
	},
	[5] = {
		['plot'] = 'mask_fadeIn',
		['param'] = {0.8},
	},
	[6] = {
		['plot'] = 'camera',
		['param'] = {{2300,1000,0}},
	},
	[7] = {
		['plot'] = 'mask_fadeOut',
		['param'] = {0.8},
	},
	[8] = {
		['plot'] = 'dialog',
		['param'] = {"ui/role/role/role3.png","斯嘉丽.露丝",2,"苏菲已经安全了！我们怎么办？"},
	},
	[9] = {
		['plot'] = 'dialog',
		['param'] = {"ui/role/role/role2.png","达达尼昂",2,"哼，决不能放走他，用力打使劲抽！"},
	},
}

return plot_4_info