-- ------------------------------
-- desc: generated by xls2data.py
-- source: battle_slogan.xls
-- sheet: 战斗口号
-- ------------------------------


local battle_slogan = {
	[10001] = {
		['event'] = 'kill',
		['event_param'] = nil,
		['ai_event'] = 'battle_slogan',
		['ai_param'] = {male={[1]="干得好，伙计！",[2]="呼哈！继续前进！",[3]="哈哈，我喜欢这情景！"},female ={[1]="干得漂亮！",[2]="快，下一个目标！",[3]="哼，美丽的焰火！"}},
		['next_ai'] = 10001,
		['sound'] = {male={[1]="VOICE_BATTLE_1010",[2]="VOICE_BATTLE_1011",[3]="VOICE_BATTLE_1012"},female ={[1]="VOICE_BATTLE_1025",[2]="VOICE_BATTLE_1026",[3]="VOICE_BATTLE_1027"}},
	},
	[10002] = {
		['event'] = 'hp_ratio_less',
		['event_param'] = {70},
		['ai_event'] = 'battle_slogan',
		['ai_param'] = {male={[1]="舷板严重受损，危险！",[2]="继续进攻！让敌人先沉没吧！"},female ={[1]="船身受损严重，我需要援助！",[2]="拼还是撤？这是一个问题"}},
		['next_ai'] = 0,
		['sound'] = {male={[1]="VOICE_BATTLE_1013",[2]="VOICE_BATTLE_1015"},female ={[1]="VOICE_BATTLE_1028",[2]="VOICE_BATTLE_1030"}},
	},
	[10003] = {
		['event'] = 'hp_ratio_less',
		['event_param'] = {35},
		['ai_event'] = 'battle_slogan',
		['ai_param'] = {male={[1]="着火了！保护火药舱和酒桶！"},female ={[1]="别傻站着，快救火！"}},
		['next_ai'] = 0,
		['sound'] = {male={[1]="VOICE_BATTLE_1014"},female ={[1]="VOICE_BATTLE_1029"}},
	},
	[10004] = {
		['event'] = 'death',
		['event_param'] = nil,
		['ai_event'] = 'battle_slogan',
		['ai_param'] = {male={[1]="我绝不会就此认输！",[2]="我，犯了一个错误！",[3]="我会更强大！而你必将失败！"},female ={[1]="我一定会回来的！",[2]="不，这不可能！",[3]="我需要变得更强！"}},
		['next_ai'] = 0,
		['sound'] = {male={[1]="VOICE_BATTLE_1016",[2]="VOICE_BATTLE_1017",[3]="VOICE_BATTLE_1018"},female ={[1]="VOICE_BATTLE_1031",[2]="VOICE_BATTLE_1032",[3]="VOICE_BATTLE_1033"}},
	},
	[10005] = {
		['event'] = 'use_skill',
		['event_param'] = {1002},
		['ai_event'] = 'battle_slogan',
		['ai_param'] = {male={[1]="机会来了！瞄准！开火！"},female ={[1]="进入射程了，所有火炮准备，开火！"}},
		['next_ai'] = 10005,
		['sound'] = {male={[1]="VOICE_BATTLE_1004"},female ={[1]="VOICE_BATTLE_1034"}},
	},
	[10006] = {
		['event'] = 'use_skill',
		['event_param'] = {1010},
		['ai_event'] = 'battle_slogan',
		['ai_param'] = {male={[1]="上链弹！把敌人桅杆都给我拆咯！"},female ={[1]="瞄准桅杆！狠狠的打！"}},
		['next_ai'] = 10006,
		['sound'] = {male={[1]="VOICE_BATTLE_1019"},female ={[1]="VOICE_BATTLE_1035"}},
	},
	[10007] = {
		['event'] = 'use_skill',
		['event_param'] = {1018},
		['ai_event'] = 'battle_slogan',
		['ai_param'] = {male={[1]="抓紧绳索荡过去！呼哈！"},female ={[1]="拔出武器，到敌人甲板上解决他们！"}},
		['next_ai'] = 10007,
		['sound'] = {male={[1]="VOICE_BATTLE_1020"},female ={[1]="VOICE_BATTLE_1036"}},
	},
	[10008] = {
		['event'] = 'use_skill',
		['event_param'] = {1026},
		['ai_event'] = 'battle_slogan',
		['ai_param'] = {male={[1]="抛出钩索别让他们逃了，蠢货们！"},female ={[1]="勾住他们，笨蛋！"}},
		['next_ai'] = 10008,
		['sound'] = {male={[1]="VOICE_BATTLE_1021"},female ={[1]="VOICE_BATTLE_1037"}},
	},
	[10009] = {
		['event'] = 'use_skill',
		['event_param'] = {1030},
		['ai_event'] = 'battle_slogan',
		['ai_param'] = {male={[1]="举高护板保护船舷！把脑袋缩回去！"},female ={[1]="到舷墙边举起护板，给我顶住！"}},
		['next_ai'] = 10009,
		['sound'] = {male={[1]="VOICE_BATTLE_1022"},female ={[1]="VOICE_BATTLE_1038"}},
	},
	[10010] = {
		['event'] = 'use_skill',
		['event_param'] = {1006},
		['ai_event'] = 'battle_slogan',
		['ai_param'] = {male={[1]="堵好漏洞！不，放开那个酒桶！笨蛋！"},female ={[1]="堵住漏洞！用脑子或身子！快！"}},
		['next_ai'] = 10010,
		['sound'] = {male={[1]="VOICE_BATTLE_1023"},female ={[1]="VOICE_BATTLE_1039"}},
	},
	[10011] = {
		['event'] = 'use_skill',
		['event_param'] = {1034},
		['ai_event'] = 'battle_slogan',
		['ai_param'] = {male={[1]="危险！注意回避！"},female ={[1]="满舵，下锚，避开攻击！"}},
		['next_ai'] = 10011,
		['sound'] = {male={[1]="VOICE_BATTLE_1003"},female ={[1]="VOICE_BATTLE_1040"}},
	},
	[10012] = {
		['event'] = 'use_skill',
		['event_param'] = {1038},
		['ai_event'] = 'battle_slogan',
		['ai_param'] = {male={[1]="满帆受风，下桨，全速前进！"},female ={[1]="让侧舷吃足风力，全速前进！"}},
		['next_ai'] = 10012,
		['sound'] = {male={[1]="VOICE_BATTLE_1024"},female ={[1]="VOICE_BATTLE_1041"}},
	},
}

return battle_slogan