-- ------------------------------
-- desc: generated by xls2data.py
-- source: boat.xls
-- sheet: 改造额外消耗银币
-- ------------------------------


local boat_reform_ext_cash = {
	[1] = {
		['cash'] = 25000,
	},
	[2] = {
		['cash'] = 34000,
	},
	[3] = {
		['cash'] = 45000,
	},
	[4] = {
		['cash'] = 60000,
	},
	[5] = {
		['cash'] = 90000,
	},
	[6] = {
		['cash'] = 125000,
	},
	[7] = {
		['cash'] = 160000,
	},
}

return boat_reform_ext_cash