-- ------------------------------
-- desc: generated by xls2data.py
-- source: 港口config.xls
-- sheet: 港口建筑
-- ------------------------------


local build_info = {
	[1] = {
		['name'] = '酒  馆',
		['res'] = '#port_pub.png',
		['icon'] = '#port_icon_pub.png',
		['explain'] = '酒馆是休闲娱乐的场所，优秀的航海士常在这里聚集',
	},
	[2] = {
		['name'] = '交易所',
		['res'] = '#port_merge.png',
		['icon'] = '#port_icon_market.png',
		['explain'] = '商品货物需要在交易所贩卖来获取利润',
	},
	[3] = {
		['name'] = '造船厂',
		['res'] = '#port_ship.png',
		['icon'] = '#port_icon_ship.png',
		['explain'] = '船舶建造和装配研究',
	},
	[4] = {
		['name'] = '市政厅',
		['res'] = '#port_town.png',
		['icon'] = '#port_icon_town.png',
		['explain'] = '城市的管理机构，影响整个城市的兴旺和繁荣',
	},
	[5] = {
		['name'] = '码  头',
		['res'] = '#port_quay.png',
		['icon'] = '#port_icon_quay.png',
		['explain'] = '船舶停靠点，忙碌的水手正在为你准备下一次航行的补给',
	},
	[6] = {
		['name'] = '功能建筑',
		['res'] = '#port_building.png',
		['icon'] = '',
		['explain'] = '开放本港口的建筑按钮，包括造船厂、市政厅、酒馆、交易所等。',
	},
	[7] = {
		['name'] = '船  舶',
		['res'] = '#port_boat.png',
		['icon'] = '#port_icon_boat.png',
		['explain'] = '',
	},
	[8] = {
		['name'] = '公  会',
		['res'] = '',
		['icon'] = '#port_icon_guild.png',
		['explain'] = '',
	},
	[9] = {
		['name'] = '营  地',
		['res'] = '',
		['icon'] = '#port_icon_camp.png',
		['explain'] = '',
	},
}

return build_info