-- ------------------------------
-- desc: generated by xls2data.py
-- source: bullet.xls
-- sheet: Sheet1
-- ------------------------------


local bullet_info = {
	[1] = {
		['name'] = 'pd_01',
		['fire_effect'] = 'pd_01',
		['fire_sound_id'] = 'FIRE_SMALL',
		['hited_sound_id'] = 'HIT_SMALL',
	},
	[2] = {
		['name'] = 'pd_02',
		['fire_effect'] = 'pd_02',
		['fire_sound_id'] = 'FIRE_MEDIUM',
		['hited_sound_id'] = 'HIT_MEDIUM',
	},
	[3] = {
		['name'] = 'pd_03',
		['fire_effect'] = 'pd_03',
		['fire_sound_id'] = 'FIRE_LARGE',
		['hited_sound_id'] = 'HIT_LARGE',
	},
	[4] = {
		['name'] = 'liuxingchui',
		['fire_effect'] = 'lianchui',
		['fire_sound_id'] = 'FIRE_MEDIUM',
		['hited_sound_id'] = 'FIRE_MEDIUM',
	},
	[5] = {
		['name'] = 'liuxingchui',
		['fire_effect'] = 'paodan_ice',
		['fire_sound_id'] = 'FIRE_SMALL',
		['hited_sound_id'] = 'HIT_SMALL',
	},
}

return bullet_info