-- ------------------------------
-- desc: generated by xls2data.py
-- source: explore_whirlpool.xls
-- sheet: Sheet1
-- ------------------------------


local explore_whirlpool = {
	[1] = {
		['name'] = '直布罗陀漩涡',
		['sea_pos'] = {772,292},
		['map_pos'] = {51,19},
		['map_name_pos'] = {0,-18},
		['des'] = '位于地中海入口',
	},
	[2] = {
		['name'] = '北海巨妖巢穴',
		['sea_pos'] = {862,172},
		['map_pos'] = {57,11},
		['map_name_pos'] = {-60,0},
		['des'] = '位于北海中部',
	},
	[3] = {
		['name'] = '南大西洋蓝洞',
		['sea_pos'] = {907,697},
		['map_pos'] = {60,46},
		['map_name_pos'] = {0,-25},
		['des'] = '位于非洲最南端',
	},
	[4] = {
		['name'] = '阿拉伯海漩涡',
		['sea_pos'] = {1102,412},
		['map_pos'] = {73,27},
		['map_name_pos'] = {0,-20},
		['des'] = '位于印度洋中部',
	},
	[5] = {
		['name'] = '科科锡美丽漩涡',
		['sea_pos'] = {1327,547},
		['map_pos'] = {88,36},
		['map_name_pos'] = {0,-20},
		['des'] = '位于东南亚最南端',
	},
	[6] = {
		['name'] = '日本龙三角',
		['sea_pos'] = {1447,322},
		['map_pos'] = {96,21},
		['map_name_pos'] = {50,0},
		['des'] = '位于东亚长崎附近',
	},
	[7] = {
		['name'] = '百慕大三角',
		['sea_pos'] = {502,337},
		['map_pos'] = {33,22},
		['map_name_pos'] = {0,25},
		['des'] = '位于加勒比海北部',
	},
}

return explore_whirlpool