-- ------------------------------
-- desc: generated by xls2data.py
-- source: fleet_config.xls
-- sheet: 舰队阵形配置
-- ------------------------------


local fleet_info = {
	[1] = {
		['name'] = '雁行阵',
		['ship_num'] = 5,
		['property'] = {fire_far=20},
		['aidSeat'] = {1,2},
		['detail_info'] = {[1]={seat={1,3}, seat_type="attack",ai_list={1011,10111},anger=50}, [2]={seat={2,2},seat_type="support",ai_list={1011,10111},anger=40}, [3]={seat={2,4},seat_type="support",ai_list={1011,10111},anger=30},  [4]={seat={3,1},seat_type="defend",ai_list={1011,10111},anger=20}, [5]={seat={3,5},seat_type="defend",ai_list={1011,10111},anger=10},},
	},
	[2] = {
		['name'] = '十字阵',
		['ship_num'] = 5,
		['property'] = {armor=20},
		['aidSeat'] = {1,2},
		['detail_info'] = {[1]={seat={1,3},seat_type="attack",ai_list={1012,10121},anger=50}, [2]={seat={2,2},seat_type="attack",ai_list={1012,10121},anger=40}, [3]={seat={2,3}, seat_type="support",ai_list={1012,10121},anger=30},  [4]={seat={2,4},seat_type="attack",ai_list={1012,10121},anger=20}, [5]={seat={3,3},seat_type="defend",ai_list={1012,10121},anger=10},},
	},
	[3] = {
		['name'] = '一字阵',
		['ship_num'] = 5,
		['property'] = {fire_near=20},
		['aidSeat'] = {1,3},
		['detail_info'] = {[1]={seat={2,3},seat_type="attack",ai_list={1001},anger=50}, [2]={seat={2,2},seat_type="attack",ai_list={1001},anger=50}, [3]={seat={2,4}, seat_type="support",ai_list={1001},anger=30},  [4]={seat={2,1},seat_type="attack",ai_list={1001},anger=20}, [5]={seat={2,5},seat_type="attack",ai_list={1001},anger=10},},
	},
	[4] = {
		['name'] = '侧翼阵',
		['ship_num'] = 5,
		['property'] = {speed=20},
		['aidSeat'] = {1,3},
		['detail_info'] = {[1]={seat={2,3},seat_type="attack",ai_list={1007,10071},anger=50}, [2]={seat={1,4},seat_type="attack",ai_list={1007,10071},anger=40}, [3]={seat={1,5}, seat_type="defend",ai_list={1007,10071},anger=30},  [4]={seat={3,4},seat_type="defend",ai_list={1007,10071},anger=20}, [5]={seat={3,5},seat_type="support",ai_list={1007,10071},anger=10},},
	},
	[5] = {
		['name'] = '包围阵',
		['ship_num'] = 5,
		['property'] = {fire_far=20},
		['aidSeat'] = {1,3},
		['detail_info'] = {[1]={seat={3,3},seat_type="attack",ai_list={1006,10061},anger=50}, [2]={seat={2,2},seat_type="defend",ai_list={1006,10061},anger=40}, [3]={seat={2,4}, seat_type="support",ai_list={1006,10061},anger=30},  [4]={seat={1,5},seat_type="defend",ai_list={1006,10061},anger=20}, [5]={seat={1,1},seat_type="attack",ai_list={1006,10061},anger=10},},
	},
	[6] = {
		['name'] = '固守阵',
		['ship_num'] = 5,
		['property'] = {armor=20},
		['aidSeat'] = {1,3},
		['detail_info'] = {[1]={seat={2,3},seat_type="attack",ai_list={1012},anger=50}, [2]={seat={1,2},seat_type="attack",ai_list={1012},anger=40}, [3]={seat={1,4}, seat_type="support",ai_list={1012},anger=30},  [4]={seat={3,2},seat_type="defend",ai_list={1012},anger=20}, [5]={seat={3,4},seat_type="defend",ai_list={1012},anger=10},},
	},
	[7] = {
		['name'] = '奇袭阵',
		['ship_num'] = 5,
		['property'] = {fire_near=20},
		['aidSeat'] = {1,3},
		['detail_info'] = {[1]={seat={3,3},seat_type="defend",ai_list={1003},anger=50}, [2]={seat={3,2},seat_type="attack",ai_list={1004},anger=40}, [3]={seat={3,4}, seat_type="support",ai_list={1004},anger=30},  [4]={seat={2,3},seat_type="defend",ai_list={1003},anger=20}, [5]={seat={1,5},seat_type="attack",ai_list={10074},anger=10},},
	},
	[8] = {
		['name'] = '随机应变阵',
		['ship_num'] = 5,
		['property'] = {speed=20},
		['aidSeat'] = {1,3},
		['detail_info'] = {[1]={seat={2,3},seat_type="attack",ai_list={1010,10101,10102},anger=50}, [2]={seat={2,2},seat_type="attack",ai_list={1010,10101,10102},anger=40}, [3]={seat={2,4}, seat_type="attack",ai_list={1010,10101,10102},anger=30},  [4]={seat={1,5},seat_type="attack",ai_list={1010,10101,10102},anger=50}, [5]={seat={3,1},seat_type="attack",ai_list={1010,10101,10102},anger=50},},
	},
}

return fleet_info