-- ------------------------------
-- desc: generated by xls2data.py
-- source: config.xls
-- sheet: 需求品
-- ------------------------------


local goods_info = {
	[1] = {
		['name'] = '艺术品',
		['res'] = 'ui/port/goods/port_cargo_169.png',
	},
	[2] = {
		['name'] = '食物',
		['res'] = 'ui/port/goods/port_cargo_143.png',
	},
	[3] = {
		['name'] = '纺织品',
		['res'] = 'ui/port/goods/port_cargo_127.png',
	},
	[4] = {
		['name'] = '香料',
		['res'] = 'ui/port/goods/port_cargo_158.png',
	},
	[5] = {
		['name'] = '奢侈品',
		['res'] = 'ui/port/goods/port_cargo_258.png',
	},
	[6] = {
		['name'] = '工业品',
		['res'] = 'ui/port/goods/port_cargo_133.png',
	},
	[7] = {
		['name'] = '嗜好品',
		['res'] = 'ui/port/goods/port_cargo_106.png',
	},
}

return goods_info