-- ------------------------------
-- desc: generated by xls2data.py
-- source: 洞府配置.xls
-- sheet: 建筑等级经验
-- ------------------------------


local courtyard_grade_exp_info = {
	[1] = {
		['GradeLmt'] = 15,
		['ZBuildingUpLimit'] = 40,
		['desc'] = TEXT('建设妖仆之屋，灵兽训练室，世界树之屋。'),
	},
	[2] = {
		['GradeLmt'] = 15,
		['ZBuildingUpLimit'] = 42,
		['desc'] = TEXT('建设妖仆酒家；在世界树之屋内进行科技研究。'),
	},
	[3] = {
		['GradeLmt'] = 20,
		['ZBuildingUpLimit'] = 44,
		['desc'] = TEXT('建设祈灵石之池；在妖仆酒家内进行科技研究。'),
	},
	[4] = {
		['GradeLmt'] = 25,
		['ZBuildingUpLimit'] = 46,
		['desc'] = TEXT('无'),
	},
	[5] = {
		['GradeLmt'] = 25,
		['ZBuildingUpLimit'] = 48,
		['desc'] = TEXT('在祈灵石之池内进行科技研究。'),
	},
	[6] = {
		['GradeLmt'] = 30,
		['ZBuildingUpLimit'] = 50,
		['desc'] = TEXT('在妖仆酒家内进行科技研究。'),
	},
	[7] = {
		['GradeLmt'] = 30,
		['ZBuildingUpLimit'] = 52,
		['desc'] = TEXT('建设法宝祭炼阵，法宝温养炉。'),
	},
	[8] = {
		['GradeLmt'] = 30,
		['ZBuildingUpLimit'] = 54,
		['desc'] = TEXT('无'),
	},
	[9] = {
		['GradeLmt'] = 35,
		['ZBuildingUpLimit'] = 56,
		['desc'] = TEXT('无'),
	},
	[10] = {
		['GradeLmt'] = 35,
		['ZBuildingUpLimit'] = 58,
		['desc'] = TEXT('在世界树之屋内进行科技研究。'),
	},
	[11] = {
		['GradeLmt'] = 35,
		['ZBuildingUpLimit'] = 60,
		['desc'] = TEXT('在祈灵石之池内进行科技研究。'),
	},
	[12] = {
		['GradeLmt'] = 35,
		['ZBuildingUpLimit'] = 62,
		['desc'] = TEXT('无'),
	},
	[13] = {
		['GradeLmt'] = 35,
		['ZBuildingUpLimit'] = 64,
		['desc'] = TEXT('建设宠物房。'),
	},
	[14] = {
		['GradeLmt'] = 40,
		['ZBuildingUpLimit'] = 66,
		['desc'] = TEXT('建设建筑研究院。'),
	},
	[15] = {
		['GradeLmt'] = 40,
		['ZBuildingUpLimit'] = 68,
		['desc'] = TEXT('在建筑研究院内进行科技研究。'),
	},
	[16] = {
		['GradeLmt'] = 40,
		['ZBuildingUpLimit'] = 70,
		['desc'] = TEXT('升级妖仆之屋'),
	},
	[17] = {
		['GradeLmt'] = 40,
		['ZBuildingUpLimit'] = 72,
		['desc'] = TEXT('在建筑研究院内进行科技研究。'),
	},
	[18] = {
		['GradeLmt'] = 40,
		['ZBuildingUpLimit'] = 74,
		['desc'] = TEXT('升级世界树之屋'),
	},
	[19] = {
		['GradeLmt'] = 45,
		['ZBuildingUpLimit'] = 76,
		['desc'] = TEXT('在建筑研究院，世界树之屋内进行科技研究。'),
	},
	[20] = {
		['GradeLmt'] = 45,
		['ZBuildingUpLimit'] = 78,
		['desc'] = TEXT('升级法宝祭练阵'),
	},
	[21] = {
		['GradeLmt'] = 45,
		['ZBuildingUpLimit'] = 80,
		['desc'] = TEXT('在建筑研究院内进行科技研究。'),
	},
	[22] = {
		['GradeLmt'] = 45,
		['ZBuildingUpLimit'] = 82,
		['desc'] = TEXT('升级妖仆酒家'),
	},
	[23] = {
		['GradeLmt'] = 45,
		['ZBuildingUpLimit'] = 84,
		['desc'] = TEXT('在建筑研究院，妖仆酒家内进行科技研究。'),
	},
	[24] = {
		['GradeLmt'] = 50,
		['ZBuildingUpLimit'] = 86,
		['desc'] = TEXT('升级祈灵石之池'),
	},
	[25] = {
		['GradeLmt'] = 50,
		['ZBuildingUpLimit'] = 88,
		['desc'] = TEXT('在建筑研究院内进行科技研究。'),
	},
	[26] = {
		['GradeLmt'] = 50,
		['ZBuildingUpLimit'] = 90,
		['desc'] = TEXT('升级灵兽训练室'),
	},
	[27] = {
		['GradeLmt'] = 50,
		['ZBuildingUpLimit'] = 92,
		['desc'] = TEXT('在建筑研究院内进行科技研究。'),
	},
	[28] = {
		['GradeLmt'] = 50,
		['ZBuildingUpLimit'] = 94,
		['desc'] = TEXT('升级法宝温养炉'),
	},
	[29] = {
		['GradeLmt'] = 55,
		['ZBuildingUpLimit'] = 96,
		['desc'] = TEXT('在世界树之屋内进行科技研究。'),
	},
	[30] = {
		['GradeLmt'] = 55,
		['ZBuildingUpLimit'] = 98,
		['desc'] = TEXT('在祈灵石之池内进行科技研究。'),
	},
	[31] = {
		['GradeLmt'] = 55,
		['ZBuildingUpLimit'] = 100,
		['desc'] = TEXT('在妖仆酒家内进行科技研究。'),
	},
	[32] = {
		['GradeLmt'] = 55,
		['ZBuildingUpLimit'] = 102,
		['desc'] = TEXT('在建筑研究院内进行科技研究。'),
	},
	[33] = {
		['GradeLmt'] = 55,
		['ZBuildingUpLimit'] = 104,
		['desc'] = TEXT('升级宠物房'),
	},
	[34] = {
		['GradeLmt'] = 60,
		['ZBuildingUpLimit'] = 106,
		['desc'] = TEXT('在建筑研究院内进行科技研究。'),
	},
	[35] = {
		['GradeLmt'] = 60,
		['ZBuildingUpLimit'] = 108,
		['desc'] = TEXT('升级建筑研究院'),
	},
	[36] = {
		['GradeLmt'] = 60,
		['ZBuildingUpLimit'] = 110,
		['desc'] = TEXT('在建筑研究院内进行科技研究。'),
	},
	[37] = {
		['GradeLmt'] = 60,
		['ZBuildingUpLimit'] = 112,
		['desc'] = TEXT('升级妖仆之屋'),
	},
	[38] = {
		['GradeLmt'] = 65,
		['ZBuildingUpLimit'] = 114,
		['desc'] = TEXT('在建筑研究院内进行科技研究。'),
	},
	[39] = {
		['GradeLmt'] = 65,
		['ZBuildingUpLimit'] = 116,
		['desc'] = TEXT('升级世界树之屋'),
	},
	[40] = {
		['GradeLmt'] = 65,
		['ZBuildingUpLimit'] = 118,
		['desc'] = TEXT('在建筑研究院，世界树之屋内进行科技研究。'),
	},
	[41] = {
		['GradeLmt'] = 70,
		['ZBuildingUpLimit'] = 120,
		['desc'] = TEXT('升级法宝祭练阵'),
	},
	[42] = {
		['GradeLmt'] = 70,
		['ZBuildingUpLimit'] = 122,
		['desc'] = TEXT('在建筑研究院内进行科技研究。'),
	},
	[43] = {
		['GradeLmt'] = 70,
		['ZBuildingUpLimit'] = 124,
		['desc'] = TEXT('升级妖仆酒家'),
	},
	[44] = {
		['GradeLmt'] = 75,
		['ZBuildingUpLimit'] = 126,
		['desc'] = TEXT('在建筑研究院，妖仆酒家内进行科技研究。'),
	},
	[45] = {
		['GradeLmt'] = 75,
		['ZBuildingUpLimit'] = 128,
		['desc'] = TEXT('升级祈灵石之池'),
	},
	[46] = {
		['GradeLmt'] = 75,
		['ZBuildingUpLimit'] = 130,
		['desc'] = TEXT('在建筑研究院内进行科技研究。'),
	},
	[47] = {
		['GradeLmt'] = 80,
		['ZBuildingUpLimit'] = 132,
		['desc'] = TEXT('升级灵兽训练室'),
	},
	[48] = {
		['GradeLmt'] = 80,
		['ZBuildingUpLimit'] = 134,
		['desc'] = TEXT('在建筑研究院内进行科技研究。'),
	},
	[49] = {
		['GradeLmt'] = 80,
		['ZBuildingUpLimit'] = 136,
		['desc'] = TEXT('升级法宝温养炉'),
	},
	[50] = {
		['GradeLmt'] = 80,
		['ZBuildingUpLimit'] = 138,
		['desc'] = TEXT('在世界树之屋内进行科技研究。'),
	},
	[51] = {
		['GradeLmt'] = 85,
		['ZBuildingUpLimit'] = 140,
		['desc'] = TEXT('在祈灵石之池内进行科技研究。'),
	},
	[52] = {
		['GradeLmt'] = 85,
		['ZBuildingUpLimit'] = 142,
		['desc'] = TEXT('在妖仆酒家内进行科技研究。'),
	},
	[53] = {
		['GradeLmt'] = 85,
		['ZBuildingUpLimit'] = 144,
		['desc'] = TEXT('在建筑研究院内进行科技研究。'),
	},
	[54] = {
		['GradeLmt'] = 90,
		['ZBuildingUpLimit'] = 146,
		['desc'] = TEXT('在建筑研究院内进行科技研究,升级宠物房'),
	},
	[55] = {
		['GradeLmt'] = 90,
		['ZBuildingUpLimit'] = 148,
		['desc'] = TEXT('升级建筑研究院'),
	},
	[56] = {
		['GradeLmt'] = 90,
		['ZBuildingUpLimit'] = 150,
		['desc'] = TEXT('在建筑研究院内进行科技研究。'),
	},
	[57] = {
		['GradeLmt'] = 90,
		['ZBuildingUpLimit'] = 152,
		['desc'] = TEXT('升级妖仆之屋'),
	},
	[58] = {
		['GradeLmt'] = 95,
		['ZBuildingUpLimit'] = 154,
		['desc'] = TEXT('在建筑研究院内进行科技研究。'),
	},
	[59] = {
		['GradeLmt'] = 95,
		['ZBuildingUpLimit'] = 156,
		['desc'] = TEXT('升级世界树之屋'),
	},
	[60] = {
		['GradeLmt'] = 95,
		['ZBuildingUpLimit'] = 158,
		['desc'] = TEXT('在建筑研究院，世界树之屋内进行科技研究。'),
	},
	[61] = {
		['GradeLmt'] = 100,
		['ZBuildingUpLimit'] = 160,
		['desc'] = TEXT('升级法宝祭练阵'),
	},
	[62] = {
		['GradeLmt'] = 100,
		['ZBuildingUpLimit'] = 162,
		['desc'] = TEXT('在建筑研究院内进行科技研究。'),
	},
	[63] = {
		['GradeLmt'] = 100,
		['ZBuildingUpLimit'] = 164,
		['desc'] = TEXT('升级妖仆酒家'),
	},
	[64] = {
		['GradeLmt'] = 105,
		['ZBuildingUpLimit'] = 166,
		['desc'] = TEXT('在建筑研究院，妖仆酒家内进行科技研究。'),
	},
	[65] = {
		['GradeLmt'] = 105,
		['ZBuildingUpLimit'] = 168,
		['desc'] = TEXT('升级祈灵石之池'),
	},
	[66] = {
		['GradeLmt'] = 105,
		['ZBuildingUpLimit'] = 170,
		['desc'] = TEXT('在建筑研究院内进行科技研究。'),
	},
	[67] = {
		['GradeLmt'] = 110,
		['ZBuildingUpLimit'] = 172,
		['desc'] = TEXT('升级灵兽训练室'),
	},
	[68] = {
		['GradeLmt'] = 110,
		['ZBuildingUpLimit'] = 174,
		['desc'] = TEXT('在建筑研究院内进行科技研究。'),
	},
	[69] = {
		['GradeLmt'] = 110,
		['ZBuildingUpLimit'] = 176,
		['desc'] = TEXT('升级法宝温养炉'),
	},
	[70] = {
		['GradeLmt'] = 110,
		['ZBuildingUpLimit'] = 178,
		['desc'] = TEXT('在世界树之屋内进行科技研究。'),
	},
	[71] = {
		['GradeLmt'] = 115,
		['ZBuildingUpLimit'] = 180,
		['desc'] = TEXT('在祈灵石之池内进行科技研究。'),
	},
	[72] = {
		['GradeLmt'] = 115,
		['ZBuildingUpLimit'] = 182,
		['desc'] = TEXT('在妖仆酒家内进行科技研究。'),
	},
	[73] = {
		['GradeLmt'] = 115,
		['ZBuildingUpLimit'] = 184,
		['desc'] = TEXT('在建筑研究院内进行科技研究。'),
	},
	[74] = {
		['GradeLmt'] = 120,
		['ZBuildingUpLimit'] = 186,
		['desc'] = TEXT('升级宠物房'),
	},
	[75] = {
		['GradeLmt'] = 120,
		['ZBuildingUpLimit'] = 188,
		['desc'] = TEXT('无'),
	},
}

return courtyard_grade_exp_info