-- ------------------------------
-- desc: generated by xls2data.py
-- source: 水手config.xls
-- sheet: 水手信物
-- ------------------------------


local keepsake_info = {
	[1] = {
		['name'] = 'E级航海士信物',
		['shortName'] = 'E级信物',
		['res'] = 'keepsake_E.png',
		['star'] = 1,
		['explain'] = '朋友给予您的信物，它能引荐您去招募一个E级航海士。',
		['maxNum'] = 1,
	},
	[2] = {
		['name'] = 'D级航海士信物',
		['shortName'] = 'D级信物',
		['res'] = 'keepsake_D.png',
		['star'] = 2,
		['explain'] = '朋友给予您的信物，它能引荐您去招募一个D级航海士。',
		['maxNum'] = 1,
	},
	[3] = {
		['name'] = 'C级航海士信物',
		['shortName'] = 'C级信物',
		['res'] = 'keepsake_C.png',
		['star'] = 3,
		['explain'] = '朋友给予您的信物，它能引荐您去招募一个C级航海士。',
		['maxNum'] = 1,
	},
	[4] = {
		['name'] = 'B级航海士信物',
		['shortName'] = 'B级信物',
		['res'] = 'keepsake_B.png',
		['star'] = 4,
		['explain'] = '一份诚意满满的信物，它能为您招募到一个强大的B级航海士。',
		['maxNum'] = 1,
	},
	[5] = {
		['name'] = 'A级航海士信物',
		['shortName'] = 'A级信物',
		['res'] = 'keepsake_A.png',
		['star'] = 5,
		['explain'] = '一份十分贵重的信物，有了它，才能说服那些有名的A级航海士加入您。',
		['maxNum'] = 1,
	},
	[6] = {
		['name'] = 'S级航海士信物',
		['shortName'] = 'S级信物',
		['res'] = 'keepsake_S.png',
		['star'] = 6,
		['explain'] = '天啊，船长，您是怎么得到这份贵重的信物的？上面竟然引荐您去招募一个S级的传奇航海士。',
		['maxNum'] = 1,
	},
}

return keepsake_info