-- ------------------------------
-- desc: generated by xls2data.py
-- source: login_reward.xls
-- sheet: 登录奖励
-- ------------------------------


local landReward = {
	[1] = {
		['reward_2'] = {{"#silver.png",1000},{"#silver.png",12000}},
		['kind'] = {1,1},
		['subType'] = {1,1},
	},
	[2] = {
		['reward_2'] = {{"#honour.png",200},{11,100}},
		['kind'] = {3},
		['subType'] = {1,3},
	},
	[3] = {
		['reward_2'] = {{"#silver.png",1000},{71,35}},
		['kind'] = {1},
		['subType'] = {1,2},
	},
	[4] = {
		['reward_2'] = {{"#honour.png",200},{14,90}},
		['kind'] = {3},
		['subType'] = {1,3},
	},
	[5] = {
		['reward_2'] = {{"#silver.png",1000},{78,35}},
		['kind'] = {1},
		['subType'] = {1,2},
	},
	[6] = {
		['reward_2'] = {{"#honour.png",200},{59,20}},
		['kind'] = {3},
		['subType'] = {1,2},
	},
	[7] = {
		['reward_2'] = {{"#silver.png",1000},{26,60}},
		['kind'] = {1},
		['subType'] = {1,3},
	},
}

return landReward