-- ------------------------------
-- desc: generated by xls2data.py
-- source: 音乐音效配置总表.xls
-- sheet: 界面音效
-- ------------------------------


local music_info = {
	['COMMON_BUTTON'] = {
		['res'] = 'ui/ui_click',
	},
	['COMMON_CASH'] = {
		['res'] = 'ui/ui_silver',
	},
	['COMMON_GOLD'] = {
		['res'] = 'ui/ui_gold',
	},
	['COMMON_HONOUR'] = {
		['res'] = 'ui/ui_exp',
	},
	['MISSION_ACCEPT'] = {
		['res'] = 'ui/ui_mission_new',
	},
	['MISSION_COMPLETE'] = {
		['res'] = 'ui/ui_mission_complete',
	},
	['LEVEL_UP'] = {
		['res'] = 'ui/ui_level_up',
	},
	['COMMON_NUMBER'] = {
		['res'] = 'ui/ui_number',
	},
	['PAPER_STRETCH'] = {
		['res'] = 'ui/ui_paper_stretch',
	},
	['COMMON_CLOSE'] = {
		['res'] = 'ui/ui_close',
	},
	['OPEN_BOX'] = {
		['res'] = 'ui/ui_box',
	},
	['SKILL_TRIGGER'] = {
		['res'] = 'ui/ui_skill_trigger',
	},
	['LOGIN_BGM'] = {
		['res'] = 'bg/bg_login',
	},
	['PLOT_SERIOUS'] = {
		['res'] = 'bg/bg_plot_serious',
	},
	['PLOT_ANGRY'] = {
		['res'] = 'bg/bg_plot_angry',
	},
	['PLOT_SAD'] = {
		['res'] = 'bg/bg_plot_sad',
	},
	['PLOT_CALM'] = {
		['res'] = 'bg/bg_plot_calm',
	},
	['PLOT_HAPPY'] = {
		['res'] = 'bg/bg_plot_happy',
	},
	['BGM_MED'] = {
		['res'] = 'bg/bg_port_med',
	},
	['BGM_ARAB'] = {
		['res'] = 'bg/bg_port_arab',
	},
	['BGM_NORTH'] = {
		['res'] = 'bg/bg_port_north',
	},
	['BGM_AFRICA'] = {
		['res'] = 'bg/bg_port_africa',
	},
	['BGM_INDIA'] = {
		['res'] = 'bg/bg_port_india',
	},
	['BGM_SEASIA'] = {
		['res'] = 'bg/bg_port_seasia',
	},
	['BGM_CHINA'] = {
		['res'] = 'bg/bg_port_china',
	},
	['BGM_JAPAN'] = {
		['res'] = 'bg/bg_port_japan',
	},
	['BGM_LATIN'] = {
		['res'] = 'bg/bg_port_latin',
	},
	['PORT_GOTOSEA'] = {
		['res'] = 'ui/ui_quay_sail',
	},
	['PORT_BATTLE'] = {
		['res'] = 'ui/ui_quay_battle',
	},
	['PORT_ROB'] = {
		['res'] = 'ui/ui_quay_rob',
	},
	['PORT_PK'] = {
		['res'] = 'ui/ui_quay_pk',
	},
	['PORT_WOOD_DOWN'] = {
		['res'] = 'ui/ui_wood_down',
	},
	['PORT_WOOD_UP'] = {
		['res'] = 'ui/ui_wood_up',
	},
	['PORT_CLICK_WOOD'] = {
		['res'] = 'ui/ui_wood_click',
	},
	['ENTER_PORT_FOG'] = {
		['res'] = 'ui/ui_enterport_fog',
	},
	['ENTER_PORT_NAME'] = {
		['res'] = 'ui/ui_enterport_name',
	},
	['ENTER_PORT_CHIEF'] = {
		['res'] = 'ui/ui_enterport_chief',
	},
	['PORT_INFO_DOWN'] = {
		['res'] = 'ui/ui_info_down',
	},
	['PORT_INFO_UP'] = {
		['res'] = 'ui/ui_info_up',
	},
	['SHIPYARD_MARKET'] = {
		['res'] = 'ui/ui_boat_make',
	},
	['SHIPYARD_DARWING'] = {
		['res'] = 'ui/ui_boat_darwing',
	},
	['SHIPYARD_MAKE_BOAT'] = {
		['res'] = 'ui/ui_boat_make',
	},
	['SHIPYARD_MAKE_END'] = {
		['res'] = 'ui/ui_boat_make_finished',
	},
	['SHIPYARD_DISMANTLE'] = {
		['res'] = 'ui/ui_boat_dismantle',
	},
	['SHIPYARD_DISMANTLE_AWARD'] = {
		['res'] = 'ui/ui_boat_dismantle_award',
	},
	['SHIPYARD_FLAGSHIP'] = {
		['res'] = 'ui/ui_boat_flagship',
	},
	['SHIPYARD_CHANGE_BOAT'] = {
		['res'] = 'ui/ui_boat_change',
	},
	['ASSEMBLE_STRENGTHEN'] = {
		['res'] = 'ui/ui_equip_strengthen',
	},
	['ASSEMBLE_LEVEL_UP'] = {
		['res'] = 'ui/ui_equip_level_up',
	},
	['SHIPYARD_REMAKE'] = {
		['res'] = 'ui/ui_remake',
	},
	['FITTING_OPEN'] = {
		['res'] = 'ui/ui_fitting_open',
	},
	['FITTING_EQUIP'] = {
		['res'] = 'ui/ui_fitting_equip',
	},
	['FITTING_REMOVE'] = {
		['res'] = 'ui/ui_fitting_remove',
	},
	['TOWN_INVEST'] = {
		['res'] = 'ui/ui_progressbar',
	},
	['TOWN_UNLOCK'] = {
		['res'] = 'ui/ui_unlock',
	},
	['TOWN_UNLOCK_CARD'] = {
		['res'] = 'ui/ui_unlock_card',
	},
	['TOWN_CARD'] = {
		['res'] = 'ui/ui_card',
	},
	['MARKET_OK'] = {
		['res'] = 'ui/ui_trade',
	},
	['PUB_TICK'] = {
		['res'] = 'ui/ui_tick',
	},
	['PUB_DRINK'] = {
		['res'] = 'ui/ui_drink',
	},
	['PUB_RECRUIT'] = {
		['res'] = 'ui/ui_recruit',
	},
	['PAPER_BURNING'] = {
		['res'] = 'ui/ui_paper_burn',
	},
	['BOAT_ROOM'] = {
		['res'] = 'ui/ui_helm',
	},
	['BOAT_DOOR'] = {
		['res'] = 'ui/ui_door',
	},
	['BOAT_FIRE'] = {
		['res'] = 'ui/ui_fire',
	},
	['BOAT_WOOD'] = {
		['res'] = 'ui/ui_wood',
	},
	['BOAT_CABIN'] = {
		['res'] = 'ui/ui_cabin',
	},
	['BOAT_APPOINT'] = {
		['res'] = 'ui/ui_appoint',
	},
	['NAVIGATOR_EXP_UP'] = {
		['res'] = 'ui/ui_navigator_exp_up',
	},
	['SKILL_LEVEL_UP'] = {
		['res'] = 'ui/ui_skill_level_up',
	},
	['SKILL_FAIL'] = {
		['res'] = 'ui/ui_skill_fail',
	},
	['UI_ITEM_REFINERY'] = {
		['res'] = 'ui/ui_refinery',
	},
	['UI_ITEM_SAVE'] = {
		['res'] = 'ui/ui_save',
	},
	['UI_FRIE'] = {
		['res'] = 'ui/ui_burning',
	},
	['ROOM_BOOK2'] = {
		['res'] = 'ui/ui_page_fast',
	},
	['UI_GLOBE'] = {
		['res'] = 'ui/ui_globe',
	},
	['UI_SWITCH'] = {
		['res'] = 'ui/ui_switch',
	},
	['UI_DRAWER'] = {
		['res'] = 'ui/ui_drawer',
	},
	['BOTTLE_ENLARGE'] = {
		['res'] = 'ui/ui_bottle_enlarge',
	},
	['UNLOCK_RELIC'] = {
		['res'] = 'ui/ui_relic',
	},
	['EQUIP_REWARD'] = {
		['res'] = 'ui/ui_equip_reward',
	},
	['BATTLE_OPEN_BOOK'] = {
		['res'] = 'ui/ui_book_open',
	},
	['BATTLE_CLOSE_BOOK'] = {
		['res'] = 'ui/ui_book_close',
	},
	['ROOM_BOOK'] = {
		['res'] = 'ui/ui_page_slow',
	},
	['BATTLE_BG'] = {
		['res'] = 'bg/bg_battle',
	},
	['BATTLE_BG2'] = {
		['res'] = 'bg/bg_battle2',
	},
	['UI_SKIN'] = {
		['res'] = 'ui/bt_sink',
	},
	['BATTLE_WIN'] = {
		['res'] = 'ui/bt_win',
	},
	['BATTLE_FAIL'] = {
		['res'] = 'ui/bt_lose',
	},
	['FIRE_SMALL'] = {
		['res'] = 'skill/bt_fire_small',
	},
	['FIRE_MEDIUM'] = {
		['res'] = 'skill/bt_fire_medium',
	},
	['FIRE_LARGE'] = {
		['res'] = 'skill/bt_fire_large',
	},
	['HIT_SMALL'] = {
		['res'] = 'skill/bt_hit_small',
	},
	['HIT_MEDIUM'] = {
		['res'] = 'skill/bt_hit_medium',
	},
	['HIT_LARGE'] = {
		['res'] = 'skill/bt_hit_large',
	},
	['BT_ATTACK_1'] = {
		['res'] = 'skill/bt_attack1',
	},
	['BT_ATTACK_2'] = {
		['res'] = 'skill/bt_attack2',
	},
	['BT_ATTACK_3'] = {
		['res'] = 'skill/bt_attack3',
	},
	['BT_SALVO_CASTING'] = {
		['res'] = 'skill/bt_salvo_casting',
	},
	['BT_SALVO_SHOT'] = {
		['res'] = 'skill/bt_salvo_shot',
	},
	['BT_SALVO_HIT'] = {
		['res'] = 'skill/bt_salvo_hit',
	},
	['BT_CHAIN_CASTING'] = {
		['res'] = 'skill/bt_chain_casting',
	},
	['BT_CHAIN_SHOT'] = {
		['res'] = 'skill/bt_chain_shot',
	},
	['BT_CHAIN_HIT'] = {
		['res'] = 'skill/bt_chain_hit',
	},
	['BT_SORTIE'] = {
		['res'] = 'skill/bt_sortie',
	},
	['BT_SORTIE_HIT'] = {
		['res'] = 'skill/bt_sortie_hit',
	},
	['BT_HOOK_CASTING'] = {
		['res'] = 'skill/bt_hook_casting',
	},
	['BT_HOOK'] = {
		['res'] = 'skill/bt_hook',
	},
	['BT_DEFENSE'] = {
		['res'] = 'skill/bt_defense',
	},
	['BT_REINFORCE'] = {
		['res'] = 'skill/bt_reinforce',
	},
	['BT_AVOID'] = {
		['res'] = 'skill/bt_avoid',
	},
	['BT_ADVANCE'] = {
		['res'] = 'skill/bt_advance',
	},
	['BATTLE_RESULT_WIN'] = {
		['res'] = 'ui/bt_result_win',
	},
	['BATTLE_RESULT_LOSE'] = {
		['res'] = 'ui/bt_result_lose',
	},
	['BATTLE_START'] = {
		['res'] = 'ui/bt_star',
	},
	['EX_BGM'] = {
		['res'] = 'bg/bg_explore',
	},
	['EX_DRAGMAP'] = {
		['res'] = 'ui/ui_map',
	},
	['EX_WIND'] = {
		['res'] = 'ui/ex_wind',
	},
	['EX_THUNDER'] = {
		['res'] = 'ui/ex_thunder',
	},
	['EX_STORM'] = {
		['res'] = 'ui/ex_storm',
	},
	['EX_WHALE_DIVE'] = {
		['res'] = 'ui/ex_dive_whale',
	},
	['EX_MERMAID_DIVE'] = {
		['res'] = 'ui/ex_dive_mermaid',
	},
	['EX_SAIL_UP'] = {
		['res'] = 'ui/ex_sail_up',
	},
	['EX_SAIL_DOWN'] = {
		['res'] = 'ui/ex_sail_down',
	},
	['EX_THROW'] = {
		['res'] = 'skill/ex_net_throw',
	},
	['EX_STICK'] = {
		['res'] = 'skill/ex_net_fall',
	},
	['EX_SALVAGE'] = {
		['res'] = 'skill/ex_salvage',
	},
	['EX_ROCK_HIT'] = {
		['res'] = 'skill/ex_hit_rock',
	},
	['EX_ICE_HIT'] = {
		['res'] = 'skill/ex_hit_ice',
	},
	['EX_SEAGULL'] = {
		['res'] = 'ui/ex_seagull',
	},
	['EX_TWEEDLE1'] = {
		['res'] = 'ui/ex_tweedle1',
	},
	['EX_TWEEDLE2'] = {
		['res'] = 'ui/ex_tweedle2',
	},
	['EX_TWEEDLE3'] = {
		['res'] = 'ui/ex_tweedle3',
	},
	['EX_FOG'] = {
		['res'] = 'skill/ex_fog',
	},
	['EX_MONSTER1'] = {
		['res'] = 'skill/ex_monster1',
	},
	['EX_MONSTER2'] = {
		['res'] = 'skill/ex_monster2',
	},
	['EX_MONSTER3'] = {
		['res'] = 'skill/ex_monster3',
	},
	['UI_CLICK_BOX'] = {
		['res'] = 'ui/ex_box',
	},
	['EX_TORNADO'] = {
		['res'] = 'ui/ex_tornado',
	},
	['EX_ROB'] = {
		['res'] = 'ui/ex_rob',
	},
	['CAPTURE_BASE'] = {
		['res'] = 'ui/ex_capture',
	},
	['BUY_COIN_FEW'] = {
		['res'] = 'ui/ui_buycoin1',
	},
	['BUY_COIN_MEDIUM'] = {
		['res'] = 'ui/ui_buycoin2',
	},
	['BUY_COIN_LARGE'] = {
		['res'] = 'ui/ui_buycoin3',
	},
}

return music_info