-- ------------------------------
-- desc: generated by xls2data.py
-- source: 新加东西统一用此提示信息总表.xls
-- sheet: 提示文字
-- ------------------------------


local news = {
	['NOT_CASH'] = {
		['msg'] = '银币不足',
	},
	['MAIN_CANCLE'] = {
		['msg'] = '您确定取消吗?',
	},
	['SENSITIVE_NAME'] = {
		['msg'] = '输入内容包含非法字符，请您重新输入',
	},
	['SENSITIVE_SET_NAME'] = {
		['msg'] = '输入内容包含非法字符，请您重新输入',
	},
	['SENSITIVE_CHAT_CONTENT'] = {
		['msg'] = '输入内容包含非法字符，请您重新输入',
	},
	['LOGIN_IPUT_NAME'] = {
		['msg'] = '名字不能少于三个字符!',
	},
	['NO_CASH'] = {
		['msg'] = '您带的银币太少了，去交易所赚点钱再来吧！嫌麻烦的话，直接去商城兑换银币最方便。',
	},
	['NO_GOLD'] = {
		['msg'] = '您带的金币太少了，是否去商城换点金币？',
	},
	['NO_HONOR'] = {
		['msg'] = '荣誉不足，成功讨伐其他玩家可以获得大量荣誉，去试试吧！',
	},
	['NO_POWER'] = {
		['msg'] = '您的体力不足，每过20分钟恢复1点体力，要不要去商城全部补满？',
	},
	['NO_BOATTRASFORM_MATERIAL'] = {
		['msg'] = '您携带的改造资材不足，是否使用%d金币购买%d个？（讨伐、海上打捞、投资工业港口等有几率出现改造资材）',
	},
	['NO_MATERIAL'] = {
		['msg'] = '强化材料不足，在以下战役中获胜可以得到这些材料。',
	},
	['LACK_OF_LEVEL'] = {
		['msg'] = '尚未达到造船所需的势力等级，前往任意港口的市政厅进行投资，可以提升势力等级。',
	},
	['ACCELE_GOLD'] = {
		['msg'] = '您确定消耗%d金币来快速完成吗？',
	},
	['ACCELE_CASH'] = {
		['msg'] = '您确定消耗%d银币加速12小时吗？',
	},
	['ACCELE_CANCLE'] = {
		['msg'] = '终止升级过程只能返还给你%d荣誉、%d银币，确定要终止吗？',
	},
	['BOAT_CHANGE_USING'] = {
		['msg'] = '这只船正在使用',
	},
	['BOAT_CHANGE_SET_USE_1'] = {
		['msg'] = '【%s】还有未改造部分，将无法装配对应的装备，是否确定启用？',
	},
	['BOAT_CHANGE_SET_USE_2'] = {
		['msg'] = '其它船舶改造中，当前改造无效，是否确定启用？',
	},
	['BOAT_CHANGE_SET_USE_3'] = {
		['msg'] = '是否确定启用【%s】?',
	},
	['BOAT_CHANGE_SET_USE_RESULT'] = {
		['msg'] = '成功启用【%s】',
	},
	['BOAT_CHANGE_CHANGE_1'] = {
		['msg'] = '正在使用中的船舶无法进行改造，请您先把要改造的船舶闲置后再进行操作。',
	},
	['BOAT_CHANGE_CHANGE_2'] = {
		['msg'] = '此类装备达到上限，无法改造',
	},
	['BOAT_CHANGE_CHANGE_3'] = {
		['msg'] = '是否确定当前改造?',
	},
	['BOAT_CHANGE_CHANGE_4'] = {
		['msg'] = '您的【%s】还有未改造部分，将无法装配对应的装备，是否确定改造？',
	},
	['BOAT_CHANGE_CHANGE_5'] = {
		['msg'] = '此装备格子无法改造',
	},
	['BOAT_CHANGE_CHANGE_6'] = {
		['msg'] = '此类装备达到上限，无法改造',
	},
	['BOAT_NAME_TOO_LOOG_ALTER'] = {
		['msg'] = '船名不能超过7个汉字',
	},
	['EQUIP_MASTER_PROMOTE_ACCELE'] = {
		['msg'] = '你确定花费%d金币来完成升级吗?',
	},
	['EQUIP_MASTER_PROMOTE_1'] = {
		['msg'] = '【%s】专精已经达到等级上限，请收集更多装备提升等级上限。',
	},
	['EQUIP_MASTER_PROMOTE_2'] = {
		['msg'] = '确定要将【%s】专精升级到%d级吗？',
	},
	['EQUIP_MASTER_FARMER_COST'] = {
		['msg'] = '购买工匠需要消耗【%s】',
	},
	['EQUIP_MASTER_BUY_FARMER'] = {
		['msg'] = '你购买了一个工匠。',
	},
	['EQUIP_MASTER_EXPLAIN'] = {
		['msg'] = '臼炮专精：学习后加深对臼炮的理解，加强臼炮的作用\n长管炮专精：学习后加深对长管炮的理解，加强长管炮的作用\n加农炮专精：学习后加深对加农炮的理解，加强加农炮的作用\n刀剑专精：学习后加深对刀剑的理解，加强刀剑的作用\n长柄专精：学习后加深对长柄武器的理解，加强长柄武器的作用\n弓弩专精：学习后加深对弓弩的理解，加强弓弩的作用\n风帆专精：学习后加深对风帆的理解，加强风帆的作用\n船桨专精：学习后加深对船桨的理解，加强船桨的作用\n船首像专精：学习后加深对船首像的理解，加强船首像的作用\n盾牌专精：学习后加深对盾牌的理解，加强盾牌的作用\n桅杆专精：学习后加深对桅杆的理解，加强桅杆的作用\n装甲专精：学习后加深对装甲的理解，加强装甲的作用',
	},
	['REWARD_GET'] = {
		['msg'] = '领取成功',
	},
	[''] = {
		['msg'] = '高级航海士【%s】已加入，可立即任命',
	},
	[''] = {
		['msg'] = '获得船舶【%s】，请前往船厂启用',
	},
	['SAILOR_STUDY_TEACHER_UNLOCK'] = {
		['msg'] = '你还没达到解锁条件',
	},
	['SAILOR_STUDY_BUY_SEAT'] = {
		['msg'] = '购买第%d个研究席位需要花费%d金币，确定要购买吗？',
	},
	['SAILOR_STUDY_TIPS_1'] = {
		['msg'] = '该航海士已经在别处任命,无法参与研究',
	},
	['SAILOR_STUDY_TIPS_2'] = {
		['msg'] = '你还没有派遣航海士参与研究',
	},
	['SAILOR_STUDY_TIPS_3'] = {
		['msg'] = '正在研究中,暂时无法派遣航海士',
	},
	['SAILOR_STUDY_BUY_SEAT_RESULT'] = {
		['msg'] = '你购买了一个工匠。',
	},
	['SAILOR_STUDY_START'] = {
		['msg'] = '开始研究%s技能',
	},
	['SAILOR_RECRUIT'] = {
		['msg'] = '确定要花费%s招募【%s】吗？',
	},
	['SAILOR_RECRUIT_RESULT'] = {
		['msg'] = '成功招募【%s】',
	},
	['SAILOR_RECRUIT_TARVEN'] = {
		['msg'] = '水手们都还没来酒馆，请在下个整点时间再来。',
	},
	['SAILOR_APPOINT_1'] = {
		['msg'] = '【%s】已经任命于%s，是否先将他卸任再另行任命？',
	},
	['SAILOR_APPOINT_2'] = {
		['msg'] = '确定任命【%s】到%s职位',
	},
	['SAILOR_APPOINT_3'] = {
		['msg'] = '水手已经任命于%s',
	},
	['SAILOR_APPOINT_4'] = {
		['msg'] = '是否让%s替换%s为%s?替换成功后两人职务将发生变化。',
	},
	['SAILOR_APPOINT_5'] = {
		['msg'] = '是否让%s替换%s为%s号船长?替换成功后两人职务将发生变化。',
	},
	['SAILOR_APPOINT_RESULT_1'] = {
		['msg'] = '任命成功',
	},
	['SAILOR_APPOINT_RESULT_2'] = {
		['msg'] = '卸任成功',
	},
	['APPOINT_SKILL_TIPS_1'] = {
		['msg'] = '已经招募',
	},
	['APPOINT_SKILL_TIPS_2'] = {
		['msg'] = '航海士拥有的所有技能,取最高级的技能生效!',
	},
	['APPOINT_SKILL_EXPLAIN_1'] = {
		['msg'] = '提升',
	},
	['APPOINT_SKILL_EXPLAIN_2'] = {
		['msg'] = '你还没为该职位任命航海士，无法获得职位加成效果',
	},
	['APPOINT_SKILL_EXPLAIN_3'] = {
		['msg'] = '(任命航海士的航海术等级影响任命后的加成效果)',
	},
	['PORT_BOOM_NOT_ENOUGH'] = {
		['msg'] = '未解锁',
	},
	['PORT_COUNT_NOT_ENOUGH'] = {
		['msg'] = '已售完',
	},
	['PORT_MARKET_CLICK_EXPLAIN'] = {
		['msg'] = '操作后点击确认按钮使交易生效',
	},
	['PORT_MARKET_BUY_1'] = {
		['msg'] = '货仓已满',
	},
	['PORT_MARKET_GOOD_FLAG_1'] = {
		['msg'] = '本港口【%s】增产50%%',
	},
	['PORT_MARKET_GOOD_FLAG_2'] = {
		['msg'] = '本港口【%s】增产100%%',
	},
	['PORT_MARKET_GOOD_FLAG_3'] = {
		['msg'] = '本港口【%s】降价50%%',
	},
	['PORT_MARKET_GOOD_FLAG_4'] = {
		['msg'] = '【%s】的【%s】降价50%%',
	},
	['PORT_MARKET_AC_TIPS_1'] = {
		['msg'] = '任命会计师可自动交易',
	},
	['PORT_MARKET_AC_TIPS_2'] = {
		['msg'] = '我来帮您出售有利润的商品',
	},
	['PORT_MARKET_AC_TIPS_3'] = {
		['msg'] = '我来帮您选购利润最高的商品',
	},
	['PORT_MARKET_AC_TIPS_5'] = {
		['msg'] = '购买%d件【%s】',
	},
	['PORT_MARKET_AC_TIPS_7'] = {
		['msg'] = '卖出%d件【%s】',
	},
	['PORT_MARKET_AC_TIPS_8'] = {
		['msg'] = '取消购买【%s】',
	},
	['PORT_MARKET_AC_TIPS_9'] = {
		['msg'] = '去其他港口出售商品利润更高',
	},
	['PORT_MARKET_SUCCESS'] = {
		['msg'] = '交易成功',
	},
	['PORT_MARKET_NOT_GOODS'] = {
		['msg'] = '商品已售完',
	},
	['PORT_MARKET_NOT_SELL'] = {
		['msg'] = '交易所不需要这种商品',
	},
	['PORT_MARKET_HOT_SELL_1'] = {
		['msg'] = '【%s】正在【%s】热卖',
	},
	['PORT_MARKET_HOT_SELL_2'] = {
		['msg'] = '【%s】正在【当前港口】热卖',
	},
	['PORT_MARKET_NOT_HOT_SELL'] = {
		['msg'] = '现在没有热卖商品，去其他港口看看吧。',
	},
	['PORT_SHIPYARD_LOCK_1'] = {
		['msg'] = '解锁条件：港口阶段%d（当前%d）',
	},
	['PORT_SHIPYARD_BUILD_1'] = {
		['msg'] = '建造条件：工业声望Lv.%d',
	},
	['PORT_SHIPYARD_BUILD_2'] = {
		['msg'] = '投资任意工业港口均可增加工业声望',
	},
	['PORT_APPOINT_EXPLAIN'] = {
		['msg'] = '任命会计师后才能开始委任经商。每日00:00系统将免费赠送4次委任，点击加号按钮可购买更多次数，购买后每日有效。委任开始后，船舶将在两个海域间自动进行商品交易，下线后仍可获得经商收益。每次委任历时30分钟，最多可连续进行20次委任。',
	},
	['PORT_APPOINT_SAILOR'] = {
		['msg'] = '未任命会计师，无法委任',
	},
	['PORT_APPOINT_BUY_TIME'] = {
		['msg'] = '是否用%d金币增加一次委任？购买后每天都能多委任一次。',
	},
	['PORT_APPOINT_INCOME'] = {
		['msg'] = '%d次委任共收益%d银币',
	},
	['PORT_APPOINT_BACK'] = {
		['msg'] = '是否回到出发港【%s】？',
	},
	['PORT_APPOINT_REDUCE_TIMES'] = {
		['msg'] = '结束委任不会扣除剩余的%d次委任。',
	},
	['PORT_APPOINT_FULL'] = {
		['msg'] = '货仓已满，先去交易所卖点东西再委任吧！',
	},
	['PORT_APPOINT_EMPTY'] = {
		['msg'] = '【%s】商品数量不足，请选择其他海域。',
	},
	['PORT_APPOINT_NOT_ENOUGH'] = {
		['msg'] = '委任数次不足',
	},
	['PORT_APPOINT_NEED_MONEY'] = {
		['msg'] = '你带的银币太少了，多赚点钱再来委任吧！',
	},
	['PORT_TOWN_SKILLBOOK'] = {
		['msg'] = '文化港口专属投资奖励，用于在船员界面升级航海士技能。',
	},
	['PORT_TOWN_HONOUR'] = {
		['msg'] = '商业港口专属投资奖励，用于在酒馆招募航海士。',
	},
	['PORT_TOWN_MATERIAL'] = {
		['msg'] = '工业港口专属投资奖励，用于在造船厂进行装配研究。',
	},
	['PORT_TOWN_TRANSFORM'] = {
		['msg'] = '工业港口专属投资奖励，用于在造船厂进行船体改造。',
	},
	['PORT_TOWN_CONFIRM'] = {
		['msg'] = '是否花费%d银币投资%s',
	},
	['PORT_TOWN_UNLOCKED_1'] = {
		['msg'] = '投资当前港口到第',
	},
	['PORT_TOWN_UNLOCKED_2'] = {
		['msg'] = '阶段即可解锁',
	},
	['EXPLORER_EXPLAIN'] = {
		['msg'] = '船上至少需要一半水手、食物才能出海探索，食物不足会使水手饿死，水手不足则船舶无法全速前进。水手数量为0时，船舶会自动返航，回到探索开始的港口。',
	},
	['EXPLORER_SUPPLY_CASH'] = {
		['msg'] = '补满食物和水手花了%d银币，准备扬帆出海！',
	},
	['EXPLORER_OUT_SEA'] = {
		['msg'] = '没钱补满食物和水手，只好就这样出海了。',
	},
	['EXPLORER_NOT_OUT_SEA'] = {
		['msg'] = '没钱补满食物和水手，船上补给太少，现在不能出海。',
	},
	['EXPLORER_EMPTY'] = {
		['msg'] = '我总觉得还缺点啥，要不到交易所里看看吧',
	},
	['ACTIVITY_ACTIVITY_NOT'] = {
		['msg'] = '亲，活动暂未开启！',
	},
	['ACTIVITY_ACTIVITY_SEND_1'] = {
		['msg'] = '还有货箱没有填满，可以求助好友帮忙完成，开船需要消耗60点体力，确定开船吗？',
	},
	['ACTIVITY_ACTIVITY_SEND_2'] = {
		['msg'] = '开船需要消耗60点体力，确定开船吗？',
	},
	['ACTIVITY_ACTIVITY_EXPLAIN'] = {
		['msg'] = '活动期间每消耗60点体力开启一轮船运活动，装满船运货箱后开船即可获得大量的银币、荣誉奖励。',
	},
	['ACTIVITY_ACTIVITY_INFO'] = {
		['msg'] = '选定一个货箱，按照货箱的货物要求进行装仓（黄色货箱为必选完成，棕色货箱为可选完成）',
	},
	['GUILD_INPUT_NAME'] = {
		['msg'] = '请输入一个有效的公会名字!',
	},
	['GUILD_APPLY_NUM'] = {
		['msg'] = '入会申请数量不能超过10个！',
	},
	['GUILD_FIND_RESULT'] = {
		['msg'] = '找不到相关公会',
	},
	['GUILD_DONATE_TIPS'] = {
		['msg'] = '公会个人捐献+%d,公会全海域威望+%d',
	},
	['GUILD_DONATE_SUCESS'] = {
		['msg'] = '捐献了金币%d成功!你为公会繁荣做出了贡献',
	},
	['GUILD_SALUTE'] = {
		['msg'] = '你向公会之星致敬后受到激励，增加20点体力!',
	},
	['FLEET_ADD_BOAT'] = {
		['msg'] = '%s已经编入舰队',
	},
	['BATTLE_NOT_OPEN'] = {
		['msg'] = '战役暂未开启!',
	},
	['BATTLE_SAODAN'] = {
		['msg'] = '正在扫荡中,请稍后.....',
	},
	['BATTLE_OPEN_SAODAN'] = {
		['msg'] = '你获得了战役【%s】的扫荡资格!',
	},
	['ROLE_NAME_LONG'] = {
		['msg'] = '名称太长显示有误，请重新输入',
	},
	['PVE_FIGHT'] = {
		['msg'] = '该据点属于敌方势力',
	},
	['PVE_FIGHT_1'] = {
		['msg'] = '驻军战力：%d（%s）',
	},
	['PVE_LOCK_ALL'] = {
		['msg'] = '尚未向该港口所属势力宣战\n驻军战力：%d（%s） ',
	},
	['PVE_LOCK_CUR'] = {
		['msg'] = '该据点位于敌方腹地\n请先攻占【%s】',
	},
	['PVE_LOCK_ACHIEVE'] = {
		['msg'] = '海域霸主任务还未开启，请完成主线任务',
	},
	['PVE_ACHIEVE_FINISH'] = {
		['msg'] = '我们已经击败了对手%s,提升了名望和地位，赶快领取奖励迎接新的挑战吧！',
	},
	['PVE_GET_TOWN'] = {
		['msg'] = '%s是个大都市！可以在船只、航海士、贸易方面带来多项好处！',
	},
	['PVE_GET_MARKET'] = {
		['msg'] = '%s是一座商业港口，可以提升我们的贸易利润。',
	},
	['PVE_GET_SHIP'] = {
		['msg'] = '%s是一座工业港口，可以获取装配升级材料、建造船只。',
	},
	['PVE_GET_PUB'] = {
		['msg'] = '%s是一座文化港口，可以获得招募新航海士的信物。',
	},
	['PVE_FIGHT_FAIL'] = {
		['msg'] = '我们被打败了，提升船只、装配或者航海士的能力后重新挑战吧！',
	},
	['PVE_ACHIEVE_ALLCOMPLETE'] = {
		['msg'] = '我们已经击败了%s，成为%s霸主，试着去挑战其他海域吧！',
	},
	['PVE_NEUTRAL'] = {
		['msg'] = '该港口为中立港口',
	},
	['PVE_CAPTURE'] = {
		['msg'] = '该港口为友善状态',
	},
	['PVE_PORT_NEED_LEVEL'] = {
		['msg'] = '等级不足，需要等级达到%d级！',
	},
	['PVE_SH_NEED_LEVEL'] = {
		['msg'] = '等级不足，需要等级达到%d级！',
	},
	['BATTLE_ACCOUNT_EQUIP'] = {
		['msg'] = '强化船舶装配 提升舰队战力',
	},
	['BATTLE_ACCOUNT_LEVEL'] = {
		['msg'] = '完成悬赏任务 提升船长等级',
	},
	['BATTLE_ACCOUNT_RECRUIT'] = {
		['msg'] = '招募新航海士 获得高级技能',
	},
	['FRIENDS_ENOUGH'] = {
		['msg'] = '您的朋友太多了',
	},
	['FRIENDS_LOGIN_MINUTE'] = {
		['msg'] = '%s分钟前登陆过',
	},
	['FRIENDS_LOGIN_HOUR'] = {
		['msg'] = '%s小时前登陆过',
	},
	['FRIENDS_LOGIN_DAY'] = {
		['msg'] = '%s天前登陆过',
	},
	['FRIENDS_LOGIN_MONTH'] = {
		['msg'] = '%s月前登陆过',
	},
	['FRIENDS_LOGIN_YEAR'] = {
		['msg'] = '%s年前登陆过',
	},
	['FRIENDS_DELETE_CONFIRM'] = {
		['msg'] = '确定删除好友【%s】？',
	},
	['FRIENDS_SYSTEM_RECOMMEMDATION'] = {
		['msg'] = '以下是系统推荐：',
	},
	['FRIENDS_NOT_FOUND'] = {
		['msg'] = '您要找的人还没出现，以下是系统推荐：',
	},
	['FRIENDS_HAVE_FOUND'] = {
		['msg'] = '为您找到以下玩家：',
	},
	['FRIENDS_SEARCH_SELF'] = {
		['msg'] = '请不要搜索自己，以下是系统推荐：',
	},
	['FRIENDS_SEARCH_NOTHING'] = {
		['msg'] = '您还没输入玩家昵称，看看系统推荐的玩家吧：',
	},
	['FRIENDS_POWER'] = {
		['msg'] = '系统赠送5点体力',
	},
	['FRIENDS_SILVER_TOTALLY'] = {
		['msg'] = '【%s】等%d位好友响应了你的求助，一共获赠银币%d',
	},
	['FRIENDS_HAVE_ADD'] = {
		['msg'] = '【%s】已经是您的好友，看看其他人吧：',
	},
	['FRIENDS_HELP_FULL'] = {
		['msg'] = '今天已帮助好友6次',
	},
	['CHAT_SEND_SILVER'] = {
		['msg'] = '玩家【%s】送给你银币%d',
	},
	['CHAT_TALKING_NOW'] = {
		['msg'] = '正在和玩家【%s】聊天',
	},
	['FRIENDS_SEARCH_3WORDS'] = {
		['msg'] = '请至少输入3个字',
	},
}

return news