-- ------------------------------
-- desc: generated by xls2data.py
-- source: plot.xls
-- sheet: Sheet1
-- ------------------------------


local plot_35_info = {
	[1] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,"终于找到抢劫“金路易号”的海盗头子巴拉克。"},
	},
	[2] = {
		['plot'] = 'mask_fadeIn',
		['param'] = {0.8},
	},
	[3] = {
		['plot'] = 'camera',
		['param'] = {{1300,1000,0}},
	},
	[4] = {
		['plot'] = 'mask_fadeOut',
		['param'] = {0.8},
	},
	[5] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,"巴拉克是个欺软怕硬的家伙，应该不难对付。"},
	},
	[6] = {
		['plot'] = 'camera',
		['param'] = {{1900,700,0},},
	},
	[7] = {
		['plot'] = 'cameraScale',
		['param'] = {{1900,700},0.4, 2},
	},
	[8] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,"可是狡诈的家伙把大箱大箱的货物推到海里，想减轻负重并让我们分心！"},
	},
	[9] = {
		['plot'] = 'mask_fadeIn',
		['param'] = {0.8},
	},
	[10] = {
		['plot'] = 'cameraScale',
		['param'] = {{1900,700},1,0},
	},
	[11] = {
		['plot'] = 'camera',
		['param'] = {{500,800,0}},
	},
	[12] = {
		['plot'] = 'mask_fadeOut',
		['param'] = {0.8},
	},
	[13] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,"2分钟内，在保证干掉海盗的前提下，尽量【靠近】回收落水的货物以挽回损失。"},
	},
}

return plot_35_info