-- ------------------------------
-- desc: generated by xls2data.py
-- source: 水手config.xls
-- sheet: 职业
-- ------------------------------


local sailor_job = {
	[1] = {
		['name'] = '瞭望手',
		['job'] = 'watch',
		['msg'] = '发现宝物的几率。',
		['skill'] = '瞭望手技能',
		['skillRes'] = '#skill_1066.png',
	},
	[2] = {
		['name'] = '大副',
		['job'] = 'captain',
		['msg'] = '水手上限。',
		['skill'] = '大副技能',
		['skillRes'] = '#skill_1002.png',
	},
	[3] = {
		['name'] = '火炮手',
		['job'] = 'guns',
		['msg'] = '远程伤害。',
		['skill'] = '火炮手技能',
		['skillRes'] = '#skill_1018.png',
	},
	[4] = {
		['name'] = '水手长',
		['job'] = 'sailor',
		['msg'] = '近战伤害和水手血量。',
		['skill'] = '水手长技能',
		['skillRes'] = '#skill_1034.png',
	},
	[5] = {
		['name'] = '操控师',
		['job'] = 'control',
		['msg'] = '船舶速度。',
		['skill'] = '操控师技能',
		['skillRes'] = '#skill_1110.png',
	},
	[6] = {
		['name'] = '木工',
		['job'] = 'measure',
		['msg'] = '船舶耐久。',
		['skill'] = '木工技能',
		['skillRes'] = '#skill_1058.png',
	},
	[7] = {
		['name'] = '会计师',
		['job'] = 'account',
		['msg'] = '交易利润。',
		['skill'] = '会计师技能',
		['skillRes'] = '#skill_1082.png',
	},
}

return sailor_job