-- ------------------------------
-- desc: generated by xls2data.py
-- source: share_config.xls
-- sheet: Sheet1
-- ------------------------------


local sharelimit_info = {
}

return sharelimit_info