-- ------------------------------
-- desc: generated by xls2data.py
-- source: 水手config.xls
-- sheet: 技能施放警告
-- ------------------------------


local skill_warning = {
	['UNKNOW'] = {
		['msg'] = '未知原因',
	},
	['OK'] = {
		['msg'] = '可使用',
	},
	['DEADED'] = {
		['msg'] = '目标已死亡',
	},
	['CD'] = {
		['msg'] = '技能尚未冷却',
	},
	['COMMON_CD'] = {
		['msg'] = '技能施放间隔太短，请稍后再尝试',
	},
	['HP'] = {
		['msg'] = '气血不足',
	},
	['ANGER'] = {
		['msg'] = '怒气不足',
	},
	['IN_DIS'] = {
		['msg'] = '目标距离太近无法施放',
	},
	['OUT_DIS'] = {
		['msg'] = '目标距离太远无法施放',
	},
	['NO_TARGET'] = {
		['msg'] = '没有目标或目标不在范围内',
	},
	['NO_SPEED'] = {
		['msg'] = '没有移动速度，操作失败',
	},
	['NO_NEAR'] = {
		['msg'] = '没有近战伤害，操作失败',
	},
	['NONE'] = {
		['msg'] = '没有该技能',
	},
	['STATUS_LIMIT'] = {
		['msg'] = '状态限制中，无法操作',
	},
}

return skill_warning