-- ------------------------------
-- desc: generated by xls2data.py
-- source: status.xls
-- sheet: 数值
-- ------------------------------


local status_info = {
	['relic_buff_BattleHonourRaise'] = {
		['name'] = '',
		['BattleHonourRaise'] = 100,
		['SellGoodsProfitRaise'] = 0,
		['ExploreDriveSpeedRaise'] = 0,
		['RoleExpRaise'] = 0,
		['ExploreSailorExpRaise'] = 0,
		['fight_buff'] = {},
		['tips'] = '荣誉收益提升%s',
	},
	['relic_buff_SellGoodsProfitRaise'] = {
		['name'] = '',
		['BattleHonourRaise'] = 0,
		['SellGoodsProfitRaise'] = 100,
		['ExploreDriveSpeedRaise'] = 0,
		['RoleExpRaise'] = 0,
		['ExploreSailorExpRaise'] = 0,
		['fight_buff'] = {},
		['tips'] = '商品交易收益提升%s',
	},
	['relic_buff_ExploreDriveSpeedRaise'] = {
		['name'] = '',
		['BattleHonourRaise'] = 0,
		['SellGoodsProfitRaise'] = 0,
		['ExploreDriveSpeedRaise'] = 100,
		['RoleExpRaise'] = 0,
		['ExploreSailorExpRaise'] = 0,
		['fight_buff'] = {},
		['tips'] = '探索行驶速度提升%s',
	},
	['relic_buff_RoleExpRaise'] = {
		['name'] = '',
		['BattleHonourRaise'] = 0,
		['SellGoodsProfitRaise'] = 0,
		['ExploreDriveSpeedRaise'] = 0,
		['RoleExpRaise'] = 100,
		['ExploreSailorExpRaise'] = 0,
		['fight_buff'] = {},
		['tips'] = '主角获得经验提升%s',
	},
	['relic_buff_ExploreSailorExpRaise'] = {
		['name'] = '',
		['BattleHonourRaise'] = 0,
		['SellGoodsProfitRaise'] = 0,
		['ExploreDriveSpeedRaise'] = 0,
		['RoleExpRaise'] = 0,
		['ExploreSailorExpRaise'] = 100,
		['fight_buff'] = {},
		['tips'] = '航海士获得经验提升%s',
	},
	['relic_buff_fight_buff'] = {
		['name'] = '',
		['BattleHonourRaise'] = 0,
		['SellGoodsProfitRaise'] = 0,
		['ExploreDriveSpeedRaise'] = 0,
		['RoleExpRaise'] = 0,
		['ExploreSailorExpRaise'] = 0,
		['fight_buff'] = {12,13,14,15,16,17,18,19,20,21,22,23,24,25,26},
		['tips'] = '',
	},
	['explore_boat_speed'] = {
		['name'] = '',
		['BattleHonourRaise'] = 0,
		['SellGoodsProfitRaise'] = 0,
		['ExploreDriveSpeedRaise'] = 130,
		['RoleExpRaise'] = 0,
		['ExploreSailorExpRaise'] = 0,
		['fight_buff'] = {},
		['tips'] = '探索行驶速度提升%s',
	},
}

return status_info