-- ------------------------------
-- desc: generated by xls2data.py
-- source: 定制藏宝图.xls
-- sheet: 定制藏宝图
-- ------------------------------


local treasure_info = {
	[1] = {
		['big_cd1'] = {782,261} ,
		['small_cd1'] = {463,564,2},
	},
}

return treasure_info