-- ------------------------------
-- desc: generated by xls2data.py
-- source: plot.xls
-- sheet: Sheet1
-- ------------------------------


local plot_3_info = {
	[1] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,"达达尼昂！他可是剑术好手！怎么办？"},
	},
	[2] = {
		['plot'] = 'camera',
		['param'] = {{800,800,0},{1200,800,1},},
	},
	[3] = {
		['plot'] = 'dialog',
		['param'] = {"ui/role/role/role2.png","达达尼昂",2,"小渔夫，放心，我不会砍坏你的鱼叉的！哈哈！"},
	},
	[4] = {
		['plot'] = 'camera',
		['param'] = {{800,800,0},},
	},
	[5] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,"达达尼昂！他可是剑术好手！接舷战我肯定会吃亏的!尽量保持距离，用火炮来解决战斗吧。"},
	},
	[6] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,"达达尼昂的剑术太厉害了，和他接舷战斗的话，真的毫无胜算。"},
	},
	[7] = {
		['plot'] = 'mask_fadeIn',
		['param'] = {0.8},
	},
	[8] = {
		['plot'] = 'camera',
		['param'] = {{800,800,0}},
	},
	[9] = {
		['plot'] = 'mask_fadeOut',
		['param'] = {0.8},
	},
}

return plot_3_info