-- ------------------------------
-- desc: generated by xls2data.py
-- source: plot.xls
-- sheet: Sheet1
-- ------------------------------


local plot_12_info = {
	[1] = {
		['plot'] = 'dialog',
		['param'] = {5,"汉娜",2,"摩尔海盗正在攻击商船……升帆！准备冲锋，让我把他们的甲板轰成蜂巢！",9,fail,"VOICE_BATTLE_1044"},
	},
	[2] = {
		['plot'] = 'camera',
		['param'] = {{800,600,0},{1400,600,1},},
	},
	[3] = {
		['plot'] = 'cameraScale',
		['param'] = {{1400,600},0.7,2},
	},
	[4] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,"喂！我才是船长！不要代替我下达命令。",5,fail,"VOICE_BATTLE_1042","VOICE_BATTLE_1043"},
	},
	[5] = {
		['plot'] = 'dialog',
		['param'] = {5,"汉娜",2,"别慢慢吞吞的，你们这群娘娘腔！快划桨！",5,fail,"VOICE_BATTLE_1045"},
	},
	[6] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,"(算了……)"},
	},
	[7] = {
		['plot'] = 'mask_fadeIn',
		['param'] = {0.8},
	},
	[8] = {
		['plot'] = 'cameraScale',
		['param'] = {{800,600},1,0},
	},
	[9] = {
		['plot'] = 'camera',
		['param'] = {{800,600,0}},
	},
	[10] = {
		['plot'] = 'mask_fadeOut',
		['param'] = {0.8},
	},
	[11] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,"跟我一起战斗吧，汉娜，我们有共同的敌人！"},
	},
	[12] = {
		['plot'] = 'dialog',
		['param'] = {5,"汉娜",2,"只要你们不成为我的累赘，我会把拦路的都轰掉。"},
	},
	[13] = {
		['plot'] = 'dialog',
		['param'] = {5,"汉娜",2,"一个出色的火炮手可以指挥水手进行【齐射】，给对手致命一击。",6,fail,"VOICE_BATTLE_1046"},
	},
	[14] = {
		['plot'] = 'dialog',
		['param'] = {5,"汉娜",2,"你只需要确保对手在射程内然后下命令，剩下的就交给我吧！",7,fail,"VOICE_BATTLE_1047"},
	},
	[15] = {
		['plot'] = 'guide',
		['param'] = {40,{825,30}},
	},
}

return plot_12_info