-- ------------------------------
-- desc: generated by xls2data.py
-- source: plot.xls
-- sheet: Sheet1
-- ------------------------------


local plot_133_jy_info = {
	[1] = {
		['plot'] = 'camera',
		['param'] = {{1600,640,2}},
	},
	[2] = {
		['plot'] = 'dialog',
		['param'] = {50,"徐海",2,"你们一次又一次找麻烦……",ship_id=2},
	},
	[3] = {
		['plot'] = 'dialog',
		['param'] = {50,"徐海",2,"今天就让你们葬身在这海底！",ship_id=2},
	},
}

return plot_133_jy_info