-- ------------------------------
-- desc: generated by xls2data.py
-- source: plot.xls
-- sheet: Sheet1
-- ------------------------------


local plot_111_jy_info = {
	[1] = {
		['plot'] = 'dialog',
		['param'] = {71,"杰克·斯帕罗",2,"看，我们马上就到马尼拉了。"},
	},
	[2] = {
		['plot'] = 'camera',
		['param'] = {{1312,660,2}},
	},
	[3] = {
		['plot'] = 'dialog',
		['param'] = {71,"杰克·斯帕罗",2,"奇怪，本来这片海域到处都是啸风的手下才对呀。"},
	},
	[4] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,"海上飘来烧焦的木板，情况不对！全员警惕、保持阵型。"},
	},
	[5] = {
		['plot'] = 'camera',
		['param'] = {{400,640,2}},
	},
}

return plot_111_jy_info