-- ------------------------------
-- desc: generated by xls2data.py
-- source: plot.xls
-- sheet: Sheet1
-- ------------------------------


local plot_121_info = {
	[1] = {
		['plot'] = 'camera',
		['param'] = {{1300,600,2}},
	},
	[2] = {
		['plot'] = 'dialog',
		['param'] = {83,"大明水军",2,"誓死捍卫家园！冲啊，消灭这些入侵者。"},
	},
	[3] = {
		['plot'] = 'camera',
		['param'] = {{900,600,2}},
	},
	[4] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,"由于长期的海禁政策，这些海军装备老旧实力不济。弓箭难以与火炮抗衡，必须尽快支援他们。"},
	},
}

return plot_121_info