-- ------------------------------
-- desc: generated by xls2data.py
-- source: plot.xls
-- sheet: Sheet1
-- ------------------------------


local plot_32_jy_info = {
	[1] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,"看，是上次那艘下令攻击我们的海盗船，还有………巴巴罗萨的海军！？",ship_id=1},
	},
	[2] = {
		['plot'] = 'camera',
		['param'] = {{1937,940,2},{1937,740,2}},
	},
	[3] = {
		['plot'] = 'cameraScale',
		['param'] = {{1937,740},0.8,2},
	},
	[4] = {
		['plot'] = 'mask_fadeIn',
		['param'] = {0.5},
	},
	[5] = {
		['plot'] = 'mask_fadeOut',
		['param'] = {0.5},
	},
	[6] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,"看来奥斯曼的海军和海盗早已是合作关系，统治了地中海。",ship_id=1},
	},
	[7] = {
		['plot'] = 'dialog',
		['param'] = {7,"水手",1,"连海军都在掠夺商船，我们不能坐视不管。",ship_id=1},
	},
}

return plot_32_jy_info