-- ------------------------------
-- desc: generated by xls2data.py
-- source: plot.xls
-- sheet: Sheet1
-- ------------------------------


local plot_43_info = {
	[1] = {
		['plot'] = 'camera',
		['param'] = {{250,640,0},{1724,640,3},},
	},
	[2] = {
		['plot'] = 'dialog',
		['param'] = {0,"",2,"维京海盗封锁了厄勒海峡，突破他们的防线，击沉卢卡斯的旗舰。",ship_id=1},
	},
	[3] = {
		['plot'] = 'mask_fadeIn',
		['param'] = {0.8},
	},
	[4] = {
		['plot'] = 'camera',
		['param'] = {{1200,640,0}},
	},
	[5] = {
		['plot'] = 'mask_fadeOut',
		['param'] = {0.8},
	},
	[6] = {
		['plot'] = 'cameraScale',
		['param'] = {{1200,640},0.6,3},
	},
	[7] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,"避开战舰前方巡逻的远炮船，那可不是好惹的，我们的目标是躲在防线后方的卢卡斯。",ship_id=1},
	},
	[8] = {
		['plot'] = 'mask_fadeIn',
		['param'] = {0.8},
	},
	[9] = {
		['plot'] = 'cameraScale',
		['param'] = {{1200,640},1,0},
	},
	[10] = {
		['plot'] = 'camera',
		['param'] = {{250,640,0}},
	},
	[11] = {
		['plot'] = 'mask_fadeOut',
		['param'] = {0.8},
	},
	[12] = {
		['plot'] = 'dialog',
		['param'] = {64,"卢卡斯",2,"一群废物，竟然让他们溜过来了。什么？戴维·琼斯！该死的，果然是你！",ship_id=6},
	},
	[13] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,"你们认识？戴维·琼斯，你欠我一个解释！",ship_id=1},
	},
	[14] = {
		['plot'] = 'dialog',
		['param'] = {72,"戴维·琼斯",2,"卢卡斯偷走了我最重要的东西！所以我要复仇，而如果你想在这听故事，那么你就等着他的手下送你去喂鱼吧。",ship_id=1},
	},
	[15] = {
		['plot'] = 'dialog',
		['param'] = {64,"卢卡斯",2,"来吧，戴维！看看我们谁才真正配得起当“飞翔的荷兰人”的船长！",ship_id=6},
	},
}

return plot_43_info