-- ------------------------------
-- desc: generated by xls2data.py
-- source: plot.xls
-- sheet: Sheet1
-- ------------------------------


local plot_31_jy_info = {
	[1] = {
		['plot'] = 'camera',
		['param'] = {{1270,829,2}},
	},
	[2] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,"据说奥斯曼海军在爱琴海上处处针对西欧的商船，纵容本国海盗私掠，提高警惕。",ship_id=1},
	},
	[3] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,"那艘海盗船大摇大摆的过去了，他们连登船检查都没有！",ship_id=1},
	},
}

return plot_31_jy_info