-- ------------------------------
-- desc: generated by xls2data.py
-- source: plot.xls
-- sheet: Sheet1
-- ------------------------------


local plot_65_info = {
	[1] = {
		['plot'] = 'camera',
		['param'] = {{500,600,0},{1400,600,2},},
	},
	[2] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,"达伽马亲自出手了！他的旗舰装备精良，这会是一场艰难的战斗。"},
	},
	[3] = {
		['plot'] = 'camera',
		['param'] = {{950,600,0},},
	},
	[4] = {
		['plot'] = 'cameraScale',
		['param'] = {{1200,550},0.6,1},
	},
	[5] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,"卡利卡特守军是无畏的勇士，但他们抵挡不了多久的。"},
	},
	[6] = {
		['plot'] = 'mask_fadeIn',
		['param'] = {0.8},
	},
	[7] = {
		['plot'] = 'cameraScale',
		['param'] = {{1200,550},1,0},
	},
	[8] = {
		['plot'] = 'camera',
		['param'] = {{500,600,0}},
	},
	[9] = {
		['plot'] = 'mask_fadeOut',
		['param'] = {0.8},
	},
	[10] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,"击退达伽马能让他的手下军心涣散，自行撤退。但先解决掉他的手下或许是更安全的做法！"},
	},
	[11] = {
		['plot'] = 'dialog',
		['param'] = {68,"达伽马",2,"$(usename)你这碍手碍脚的家伙！真的以为能阻止我占领卡利卡特吗？"},
	},
}

return plot_65_info