-- ------------------------------
-- desc: generated by xls2data.py
-- source: plot.xls
-- sheet: Sheet1
-- ------------------------------


local plot_42_jy_info = {
	[1] = {
		['plot'] = 'camera',
		['param'] = {{494,600,0},{1674,636,2}},
	},
	[2] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,"又是维京海盗！他们正在抢劫手无寸铁的商船！",ship_id=1},
	},
	[3] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,"我们必须给他们一个教训。",ship_id=1},
	},
}

return plot_42_jy_info