-- ------------------------------
-- desc: generated by xls2data.py
-- source: plot.xls
-- sheet: Sheet1
-- ------------------------------


local plot_17_info = {
	[1] = {
		['plot'] = 'camera',
		['param'] = {{1300,1800,0},{2500,2200,1},},
	},
	[2] = {
		['plot'] = 'dialog',
		['param'] = {4,"埃米利奥.菲隆",2,"里奥，藏宝图指示的地方到了，可是有人捷足先登了呢！"},
	},
	[3] = {
		['plot'] = 'mask_fadeIn',
		['param'] = {0.8},
	},
	[4] = {
		['plot'] = 'camera',
		['param'] = {{800,650,0},},
	},
	[5] = {
		['plot'] = 'mask_fadeOut',
		['param'] = {0.8},
	},
	[6] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,"护卫船的速度比较快，要不我们跟上去，等它走远了再攻击寻宝船！"},
	},
	[7] = {
		['plot'] = 'dialog',
		['param'] = {0,"",1,"不好，对方的护卫船发现我们了！先引开它击沉，然后再对付寻宝船吧。"},
	},
}

return plot_17_info