-- ------------------------------
-- desc: generated by xls2data.py
-- source: plot.xls
-- sheet: Sheet1
-- ------------------------------


local plot_132_jy_info = {
	[1] = {
		['plot'] = 'camera',
		['param'] = {{1400,640,2}},
	},
	[2] = {
		['plot'] = 'dialog',
		['param'] = {3,"武装冲锋船",2,"别天真的以为，我们就只有这点能力。",ship_id=3},
	},
	[3] = {
		['plot'] = 'dialog',
		['param'] = {3,"武装冲锋船",2,"没点本事,我们怎么能在东亚光明正大走私？",ship_id=3},
	},
}

return plot_132_jy_info